//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSLock, NSMapTable, NSMutableDictionary, NSOperationQueue;

@interface AsynLoadImageManager : NSObject
{
    NSOperationQueue *_operationQueue;
    NSLock *_downloadListLock;
    NSMutableDictionary *_downloadList;
    NSLock *_observerListLock;
    NSMapTable *_observerTable;
}

+ (id)getInstance;
- (void).cxx_destruct;
- (void)downloadImage:(id)arg1 finish:(CDUnknownBlockType)arg2 failed:(CDUnknownBlockType)arg3;
- (void)downloadImage:(id)arg1 withObserver:(id)arg2 imageSource:(int)arg3 exInfo:(id)arg4;
- (void)downloadImage:(id)arg1 withObserver:(id)arg2 imageSource:(int)arg3;
- (void)addOperation:(id)arg1;
- (void)setConcurrentOperationMinCount;
- (void)setConcurrentOperationMaxCount;
- (id)init;

@end

