//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSMutableArray, NSString, UILabel;

@interface CmShowGameBanner : UIView
{
    UIView *_currentContentView;
    UILabel *_currentTitleLabel;
    UIView *_nextContentView;
    UILabel *_nextTitleLabel;
    _Bool _isAnimating;
    NSString *_title;
    id <CmShowGameBannerDelegate> _delegate;
    NSMutableArray *_joinTipsArray;
}

@property(retain, nonatomic) UILabel *nextTitleLabel; // @synthesize nextTitleLabel=_nextTitleLabel;
@property(retain, nonatomic) UIView *nextContentView; // @synthesize nextContentView=_nextContentView;
@property(retain, nonatomic) UILabel *currentTitleLabel; // @synthesize currentTitleLabel=_currentTitleLabel;
@property(retain, nonatomic) UIView *currentContentView; // @synthesize currentContentView=_currentContentView;
@property(retain, nonatomic) NSMutableArray *joinTipsArray; // @synthesize joinTipsArray=_joinTipsArray;
@property(nonatomic) _Bool isAnimating; // @synthesize isAnimating=_isAnimating;
@property(nonatomic) id <CmShowGameBannerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (void)dealloc;
- (void)showAnimation;
- (void)receiveJoinRoomTips:(id)arg1;
- (void)tapOnBanner:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

