//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSMutableDictionary, NSString, QQAvatarView, UIButton, UIColor, UIImage, UIImageView, UILabel;

@interface ContentNotifyControl : UIView
{
    UIButton *_notifyBtn;
    UILabel *_lable;
    UIImageView *_iconView;
    QQAvatarView *_headerView;
    int _buttonAlgin;
    int _notifyID;
    struct CGRect _contentRect;
    _Bool _bNotifyShow;
    _Bool _showAnimating;
    NSMutableDictionary *_dicCloseCount;
    UIImageView *_bgImageView;
    struct CGPoint _lastPoint;
    UIColor *_textColor;
    NSString *_title;
    UIImage *_icon;
    double _origY;
    NSString *_uin;
    _Bool _bIconReverted;
    int _xo;
}

@property(nonatomic) _Bool showAnimating; // @synthesize showAnimating=_showAnimating;
@property(nonatomic) _Bool bNotifyShow; // @synthesize bNotifyShow=_bNotifyShow;
- (void).cxx_destruct;
- (void)adjustY:(double)arg1;
- (int)getCloseCount:(int)arg1;
- (void)setCloseCount:(int)arg1 count:(int)arg2;
- (void)setUin:(id)arg1 isQQFriend:(_Bool)arg2;
@property(copy, nonatomic) NSString *uin; // @dynamic uin;
- (void)revertIconOnce;
@property(retain, nonatomic) UIImage *icon; // @dynamic icon;
- (void)close;
- (void)popUp;
- (void)touchUpOutsideButton;
- (void)touchDownButton;
- (void)handlePanGesture:(id)arg1;
- (void)clickButton;
@property(copy, nonatomic) NSString *title; // @dynamic title;
- (struct CGRect)calcViewRect;
- (void)setSkinColor;
@property(retain, nonatomic) UIColor *textColor; // @dynamic textColor;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(nonatomic) int buttonAlgin; // @dynamic buttonAlgin;
@property(nonatomic) int notifyID; // @dynamic notifyID;
@property(nonatomic) double origY; // @dynamic origY;

@end

