//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface FAPreviewConfigInfo : NSObject
{
    int _previewMode;
    int _fileType;
    NSString *_interfacePage;
    NSString *_httpsInterfacePage;
}

@property(nonatomic) int fileType; // @synthesize fileType=_fileType;
@property(nonatomic) int previewMode; // @synthesize previewMode=_previewMode;
@property(retain, nonatomic) NSString *httpsInterfacePage; // @synthesize httpsInterfacePage=_httpsInterfacePage;
@property(retain, nonatomic) NSString *interfacePage; // @synthesize interfacePage=_interfacePage;
- (id)description;
- (void)dealloc;
- (id)initWithPage:(id)arg1 mode:(int)arg2 type:(int)arg3;

@end

