//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FTSBaseSearchFilter.h"

@interface FTSDiscussGroupMsgSearchFilter : FTSBaseSearchFilter
{
}

- (id)convertSqlResultToQQMessageMogel:(id)arg1 uin:(id)arg2;
- (unsigned int)getMsgNum:(id)arg1 keyword:(id)arg2 inDb:(id)arg3;
- (unsigned int)getMsgNum:(id)arg1 keyword:(id)arg2;
- (id)getFtsSessionName:(id)arg1;
- (id)getMsgDBname:(id)arg1;
- (long long)sessionType;
- (id)GetSearchSqlWithDBName:(id)arg1 MsgIndex:(long long)arg2 count:(long long)arg3;
- (id)init;

@end

