//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FTSResultMoreBaseViewController.h"

@class FTSMsgDetailSearchCondition;

@interface FTSResultMsgDetailViewController : FTSResultMoreBaseViewController
{
    long long _currentPageMsgId;
}

- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)reloadTableInMainThreadWithResults:(id)arg1 pageMsgIdx:(long long)arg2;
- (void)actionSearch;
- (void)clearDataSource;
- (void)addDatasource:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)_setDiscussGroupDetailTitle;
- (void)viewDidLoad;
- (id)initWithSearchCondition:(id)arg1;

// Remaining properties
@property(retain, nonatomic) FTSMsgDetailSearchCondition *searchCondition; // @dynamic searchCondition;

@end

