//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GAKeyboardHelper : NSObject
{
}

+ (void)textView:(id)arg1 insertString:(id)arg2 selectedRange:(struct _NSRange *)arg3 textViewDelegate:(id)arg4;
+ (_Bool)textView:(id)arg1 deletedRange:(struct _NSRange)arg2 selectedRange:(struct _NSRange *)arg3 textViewDelegate:(id)arg4;
+ (long long)keyboardAnimationCurve:(id)arg1;
+ (double)keyboardAnimationDuration:(id)arg1;
+ (struct CGRect)keyboardFrameEnd:(id)arg1;
+ (struct CGRect)keyboardFrameBegin:(id)arg1;
+ (double)KeyboardChangeHeightOffset:(id)arg1;
+ (_Bool)isKeyboardChangeFrame:(id)arg1;
+ (double)keyboardHeight:(id)arg1;

@end

