//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JceObjectV2.h"

@class NSArray, NSString;

@interface GetRecordNumResp : JceObjectV2
{
    long long jcev2_p_0_r_result;
    NSArray *jcev2_p_1_r_serverStat__b0x9i_VODBStatus;
    NSString *jcev2_p_2_r_supportURL;
    NSString *jcev2_p_3_r_msg;
}

+ (id)jceType;
+ (void)initialize;
@property(retain, nonatomic, getter=jce_msg, setter=setJce_msg:) NSString *jcev2_p_3_r_msg; // @synthesize jcev2_p_3_r_msg;
@property(retain, nonatomic, getter=jce_supportURL, setter=setJce_supportURL:) NSString *jcev2_p_2_r_supportURL; // @synthesize jcev2_p_2_r_supportURL;
@property(retain, nonatomic, getter=jce_serverStat, setter=setJce_serverStat:) NSArray *jcev2_p_1_r_serverStat__b0x9i_VODBStatus; // @synthesize jcev2_p_1_r_serverStat__b0x9i_VODBStatus;
@property(nonatomic, getter=jce_result, setter=setJce_result:) long long jcev2_p_0_r_result; // @synthesize jcev2_p_0_r_result;
- (void)dealloc;
- (id)init;

@end

