//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQGroupPropertyModel.h"

@interface NearByColorModel : QQGroupPropertyModel
{
}


// Remaining properties
@property(nonatomic) int B; // @dynamic B;
@property(nonatomic) int G; // @dynamic G;
@property(nonatomic) int R; // @dynamic R;
@end

