//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "CAAnimationDelegate.h"

@class CABasicAnimation, CAShapeLayer, NSString, QQAvatarView, UIColor;

@interface NearbyVideoChatAvatarView : UIView <CAAnimationDelegate>
{
    QQAvatarView *_avatarView;
    CAShapeLayer *_borderLayer;
    CDUnknownBlockType _updateAvatarCompletBlock;
    double _borderWidth;
    UIColor *_borderColor;
    CABasicAnimation *_strokeAnimation;
}

@property(retain, nonatomic) CABasicAnimation *strokeAnimation; // @synthesize strokeAnimation=_strokeAnimation;
@property(retain, nonatomic) UIColor *borderColor; // @synthesize borderColor=_borderColor;
@property(nonatomic) double borderWidth; // @synthesize borderWidth=_borderWidth;
@property(copy, nonatomic) CDUnknownBlockType updateAvatarCompletBlock; // @synthesize updateAvatarCompletBlock=_updateAvatarCompletBlock;
@property(retain, nonatomic) CAShapeLayer *borderLayer; // @synthesize borderLayer=_borderLayer;
@property(retain, nonatomic) QQAvatarView *avatarView; // @synthesize avatarView=_avatarView;
- (void).cxx_destruct;
- (void)clearAllState;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)startCircleAnimationWithTime:(double)arg1 AndRepeatCount:(double)arg2;
- (void)setCircleColor:(id)arg1;
- (void)loadAvatarByUrl:(id)arg1;
- (void)loadQQAvatar:(id)arg1;
- (void)loadEncounterAvatarByUin:(id)arg1;
- (void)updateAvatarViewWithParamDic:(id)arg1 CompletionBlock:(CDUnknownBlockType)arg2;
- (void)loadDefaultView;
- (void)loadDefaultStyle;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

