//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQViewController.h"

#import "CFFootViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class CFFootView, NSString, NearbyNOVisitorsView, NearbyVisitorsModel, ODRefreshControl, UITableView;

@interface NearbyRecentVisitorsViewController : QQViewController <UITableViewDataSource, UITableViewDelegate, CFFootViewDelegate>
{
    NearbyNOVisitorsView *_noVisitorsView;
    _Bool _reloading;
    UITableView *_tableView;
    ODRefreshControl *_refreshControl;
    _Bool _isRefesh;
    CFFootView *_loadMoreFooterView;
    unsigned int _qzoneFeedShowControl;
    NSString *_downloadAppUrl;
    NearbyVisitorsModel *_model;
}

@property(retain, nonatomic) NearbyVisitorsModel *model; // @synthesize model=_model;
@property(nonatomic) unsigned int qzoneFeedShowControl; // @synthesize qzoneFeedShowControl=_qzoneFeedShowControl;
@property(copy, nonatomic) NSString *downloadAppUrl; // @synthesize downloadAppUrl=_downloadAppUrl;
- (void).cxx_destruct;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)configCellSeparator:(id)arg1 cell:(id)arg2 indexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)initListStyleCellView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (id)getVisitor:(id)arg1;
- (void)openDownloadTribeApp;
- (id)getCompletedView;
- (void)refeshFootView;
- (void)startRefresh:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (long long)visibleCount;
- (void)jumpToCharmPage:(id)arg1;
- (id)convertToNearbyFriend:(id)arg1;
- (_Bool)requestVisitors;
- (void)dropViewDidBeginRefreshing:(id)arg1;
- (_Bool)getMoreData:(id)arg1;
- (void)saveVisitors;
- (void)resetControllerTitle;
- (void)viewDidLoad;
- (void)loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

