//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "ARScanViewDelegate.h"
#import "AVCaptureVideoDataOutputSampleBufferDelegate.h"

@class AVCaptureDevice, AVCaptureDeviceFormat, AVCaptureDeviceInput, AVCaptureSession, AVCaptureStillImageOutput, AVCaptureVideoDataOutput, AVCaptureVideoPreviewLayer, CIContext, EAGLContext, GLKView, NSString, NSTimer, UIImage, UIImageView;

@interface OCRHQScanView : UIView <ARScanViewDelegate, AVCaptureVideoDataOutputSampleBufferDelegate>
{
    struct CGSize _avCaptureSize;
    unsigned int _renderBuffer;
    _Bool _isCapturing;
    _Bool _isStopped;
    struct CGRect _drawRect;
    AVCaptureDeviceFormat *_activeFormat;
    long long _lastAddFrameMillTime;
    double _scale;
    double _imgWidthOfPoint;
    double _imgHeightOfPoint;
    float _xScale;
    float _yScale;
    float _maxScale;
    struct CGAffineTransform _transform;
    _Bool _borderDetectFrame;
    NSTimer *_borderDetectTimeKeeper;
    GLKView *_glkView;
    CIContext *_coreImageContext;
    int _frameCountNoRecgFeature;
    long long _lastDetectMillTime;
    int _detectCount;
    _Bool _shouldInitTime;
    _Bool _isAnimation;
    _Bool _forceStop;
    _Bool _hasInitData;
    _Bool _enableBorderDetection;
    id <OCRHQScanViewUIDelegate> _uiDelegate;
    AVCaptureVideoPreviewLayer *_previewLayer;
    AVCaptureSession *_session;
    AVCaptureDevice *_device;
    AVCaptureDeviceInput *_input;
    AVCaptureVideoDataOutput *_output;
    CDStruct_79c71658 _videoDimensions;
    EAGLContext *_context;
    AVCaptureStillImageOutput *_stillImageOutput;
    UIView *_previewRecgView;
    UIView *_previewRecgLineView;
    UIImageView *_animationHorizonView;
    UIImageView *_animationVerticalView;
    UIImageView *_topLeftView;
    UIImageView *_topRightView;
    UIImageView *_bottomLeftView;
    UIImageView *_bottomRightView;
    UIImage *_currentCaptureImage;
    struct CGSize _intrinsicContentSize;
}

+ (void)checkCameraAvailable:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) UIImage *currentCaptureImage; // @synthesize currentCaptureImage=_currentCaptureImage;
@property(nonatomic) struct CGSize intrinsicContentSize; // @synthesize intrinsicContentSize=_intrinsicContentSize;
@property(nonatomic, getter=isBorderDetectionEnabled) _Bool enableBorderDetection; // @synthesize enableBorderDetection=_enableBorderDetection;
@property(nonatomic) _Bool hasInitData; // @synthesize hasInitData=_hasInitData;
@property(retain, nonatomic) UIImageView *bottomRightView; // @synthesize bottomRightView=_bottomRightView;
@property(retain, nonatomic) UIImageView *bottomLeftView; // @synthesize bottomLeftView=_bottomLeftView;
@property(retain, nonatomic) UIImageView *topRightView; // @synthesize topRightView=_topRightView;
@property(retain, nonatomic) UIImageView *topLeftView; // @synthesize topLeftView=_topLeftView;
@property(retain, nonatomic) UIImageView *animationVerticalView; // @synthesize animationVerticalView=_animationVerticalView;
@property(retain, nonatomic) UIImageView *animationHorizonView; // @synthesize animationHorizonView=_animationHorizonView;
@property(retain, nonatomic) UIView *previewRecgLineView; // @synthesize previewRecgLineView=_previewRecgLineView;
@property(retain, nonatomic) UIView *previewRecgView; // @synthesize previewRecgView=_previewRecgView;
@property(retain, nonatomic) AVCaptureStillImageOutput *stillImageOutput; // @synthesize stillImageOutput=_stillImageOutput;
@property(nonatomic) _Bool forceStop; // @synthesize forceStop=_forceStop;
@property(retain, nonatomic) EAGLContext *context; // @synthesize context=_context;
@property(readonly, nonatomic) CDStruct_1ef3fb1f videoDimensions; // @synthesize videoDimensions=_videoDimensions;
@property(retain, nonatomic) AVCaptureVideoDataOutput *output; // @synthesize output=_output;
@property(retain, nonatomic) AVCaptureDeviceInput *input; // @synthesize input=_input;
@property(retain, nonatomic) AVCaptureDevice *device; // @synthesize device=_device;
@property(retain, nonatomic) AVCaptureSession *session; // @synthesize session=_session;
@property(retain, nonatomic) AVCaptureVideoPreviewLayer *previewLayer; // @synthesize previewLayer=_previewLayer;
@property(nonatomic) __weak id <OCRHQScanViewUIDelegate> uiDelegate; // @synthesize uiDelegate=_uiDelegate;
- (void).cxx_destruct;
- (void)enableBorderDetectFrame;
- (void)addPathToLayerWithCropWidth:(double)arg1 cropHeight:(double)arg2 topLeft:(struct CGPoint)arg3 topRight:(struct CGPoint)arg4 bottomLeft:(struct CGPoint)arg5 bottomRight:(struct CGPoint)arg6;
- (void)setPreviewRecgLineViewRandom;
- (id)getRectangleRecognizeWithImage:(id)arg1;
- (id)highAccuracyRectangleDetector;
- (_Bool)borderDetectEnabled;
- (void)stopRecg;
- (void)onSessionServerLostNotification:(id)arg1;
- (void)onSessionNotification:(id)arg1;
- (void)doCloudRecogPerFrame:(id)arg1;
- (void)onCameraFrameCapture;
- (void)captureCurrentFrameImageCompletionHandler:(CDUnknownBlockType)arg1;
- (struct CGRect)cropRectForPreviewImage:(id)arg1;
- (void)captureOutput:(id)arg1 didOutputSampleBuffer:(struct opaqueCMSampleBuffer *)arg2 fromConnection:(id)arg3;
- (void)setFrameRate;
- (_Bool)doInitCamera;
- (void)reportARPerformanceEvent;
- (_Bool)captureSessionisRunning;
- (_Bool)stopCamera;
- (_Bool)startUpCamera;
- (_Bool)shutDownCamera;
- (void)addRecgAnimation;
- (void)addAnimation:(id)arg1;
- (void)viewDidAppear;
- (void)didBecomeActive;
- (void)delayEnableRendering;
- (void)didEnterForeground;
- (void)willMoveToWindow:(id)arg1;
- (void)dealloc;
- (void)handleSingleTap:(id)arg1;
- (void)onARCameraChanged:(long long)arg1 fromCamera:(id)arg2;
- (void)createGLKView;
- (id)initWithFrame:(struct CGRect)arg1 drawViewRect:(struct CGRect)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

