//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQModel.h"

#import "NSCopying.h"

@class NSArray, NSDictionary, NSString;

@interface OGTConfigModel : QQModel <NSCopying>
{
    NSString *_uinString;
    _Bool _tipEnable;
    long long _tipsCount;
    long long _messageCount;
    NSArray *_configTasks;
    NSArray *_configTaskIDs;
    NSDictionary *_randomWordings;
    NSDictionary *_showKeyboardSupports;
    int _xo;
    NSDictionary *_fileUrls;
    NSDictionary *_fileMD5s;
    double _lastConfigDate;
    NSArray *_failedFileUrls;
    NSArray *_failedFileMD5s;
}

@property(retain, nonatomic) NSArray *failedFileMD5s; // @synthesize failedFileMD5s=_failedFileMD5s;
@property(retain, nonatomic) NSArray *failedFileUrls; // @synthesize failedFileUrls=_failedFileUrls;
@property(nonatomic) double lastConfigDate; // @synthesize lastConfigDate=_lastConfigDate;
@property(retain, nonatomic) NSDictionary *fileMD5s; // @synthesize fileMD5s=_fileMD5s;
@property(retain, nonatomic) NSDictionary *fileUrls; // @synthesize fileUrls=_fileUrls;
- (void).cxx_destruct;
- (id)configTaskModelForTaskID:(id)arg1;
- (_Bool)containWording:(id)arg1;
- (_Bool)showKeyboardSupportForTaskID:(id)arg1;
- (id)randomWordingForTaskID:(id)arg1;
- (void)mergeFromTaskListIfNeeded:(id)arg1;
- (void)mergeForTask:(id)arg1;
- (void)mergeForTaskID:(id)arg1;
- (_Bool)isInTaskIDList:(id)arg1;
- (void)removeFromFailedListIfNeeded:(id)arg1 MD5:(id)arg2;
- (void)addToFailedList:(id)arg1 MD5:(id)arg2;
- (void)addToDictionaryWithUrl:(id)arg1 MD5:(id)arg2 taskID:(id)arg3;
- (void)addToDictionaryWithWordings:(id)arg1 taskID:(id)arg2;
- (void)addToDictionaryWithKeyboardSupport:(_Bool)arg1 taskID:(id)arg2;
- (id)parseFromDictionary:(id)arg1 withUrl:(id)arg2 MD5:(id)arg3;
- (id)copyWithZone:(struct _NSZone *)arg1;

// Remaining properties
@property(retain, nonatomic) NSArray *configTaskIDs; // @dynamic configTaskIDs;
@property(retain, nonatomic) NSArray *configTasks; // @dynamic configTasks;
@property(nonatomic) long long messageCount; // @dynamic messageCount;
@property(retain, nonatomic) NSDictionary *randomWordings; // @dynamic randomWordings;
@property(retain, nonatomic) NSDictionary *showKeyboardSupports; // @dynamic showKeyboardSupports;
@property(nonatomic) _Bool tipEnable; // @dynamic tipEnable;
@property(nonatomic) long long tipsCount; // @dynamic tipsCount;
@property(copy, nonatomic) NSString *uinString; // @dynamic uinString;

@end

