//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "ActionItemDelegate.h"
#import "PhotoBrowserViewDelegate.h"
#import "PhotoEditDelegate.h"
#import "QQAudioSessionManagerDelegate.h"
#import "QUIActionSheetDelegate.h"

@class NSArray, NSMutableArray, NSString, PhotoBrowserView, QQPageIndicator, QUIActionSheet, UIBarButtonItem, UIButton, UIImage, UINavigationBar, UIView, UIWindow;

@interface PhotoBrowserBaseViewContoller : UIViewController <QQAudioSessionManagerDelegate, PhotoEditDelegate, QUIActionSheetDelegate, PhotoBrowserViewDelegate, ActionItemDelegate>
{
    long long _initPage;
    _Bool _isControlHidden;
    _Bool _isNavigationBarHidden;
    _Bool _isMsgBarShow;
    _Bool _lastStatusBarHidden;
    _Bool _isToolBarViewResident;
    long long _lastStatusBarStyle;
    Class _photoClass;
    UIBarButtonItem *_leftButton;
    UIBarButtonItem *_rightButton;
    UINavigationBar *_navigationBar;
    PhotoBrowserView *_pagePhotosView;
    QQPageIndicator *_pageControl;
    UIView *_toolbarView;
    NSArray *_itemList;
    NSMutableArray *_photoList;
    QUIActionSheet *_actionSheet;
    UIImage *_previewImage;
    struct CGRect _sourceClipRect;
    id <PhotoBrowserViewControllerDelegate> _photoBrowserDelegate;
    UIViewController *_lastViewController;
    UIButton *_moreButton;
    UIButton *_editButton;
    long long _initPicIndex;
    _Bool _enableCorrectThumbnailRect;
    int _xo;
    UIWindow *_maskView;
    _Bool _isNeedSpecialLogicForAVFloatBar;
    _Bool _needRouteAdapterIpList;
    _Bool _isPreviewFlashPic;
    _Bool _isNeedSupportLandScape;
    _Bool _isShareDocxEntry;
    _Bool _isUsedForShowingAvatarView;
    _Bool _hasAudioSession;
    _Bool _viewHasAppear;
    int _menuFrom;
    UIImage *_firstImageViewThumbImage;
}

@property(nonatomic) _Bool viewHasAppear; // @synthesize viewHasAppear=_viewHasAppear;
@property(nonatomic) _Bool hasAudioSession; // @synthesize hasAudioSession=_hasAudioSession;
@property(nonatomic) int menuFrom; // @synthesize menuFrom=_menuFrom;
@property(retain, nonatomic) UIImage *firstImageViewThumbImage; // @synthesize firstImageViewThumbImage=_firstImageViewThumbImage;
@property(nonatomic) _Bool isUsedForShowingAvatarView; // @synthesize isUsedForShowingAvatarView=_isUsedForShowingAvatarView;
@property(nonatomic) _Bool isShareDocxEntry; // @synthesize isShareDocxEntry=_isShareDocxEntry;
@property(nonatomic) _Bool isNeedSupportLandScape; // @synthesize isNeedSupportLandScape=_isNeedSupportLandScape;
@property(nonatomic) _Bool isPreviewFlashPic; // @synthesize isPreviewFlashPic=_isPreviewFlashPic;
@property(nonatomic) _Bool needRouteAdapterIpList; // @synthesize needRouteAdapterIpList=_needRouteAdapterIpList;
@property(nonatomic) _Bool isNeedSpecialLogicForAVFloatBar; // @synthesize isNeedSpecialLogicForAVFloatBar=_isNeedSpecialLogicForAVFloatBar;
@property(retain, nonatomic) PhotoBrowserView *pagePhotosView; // @synthesize pagePhotosView=_pagePhotosView;
- (id)p_GetExistFlashOriImg:(id)arg1;
- (_Bool)shouldAutorotate;
- (_Bool)needShowTopTips;
- (void)photoEditor:(id)arg1 didFinishWithImage:(id)arg2 asset:(id)arg3 shouldOpenDoodle:(_Bool)arg4 hasEdited:(_Bool)arg5;
- (void)gotoPhotoEditControllerWithAsset:(id)arg1;
- (void)onEditButtonClick;
- (void)onMoreButtonClick;
- (void)onVideoDidSendToQzone:(id)arg1;
- (void)onSaveToAlbumRetNotify:(id)arg1;
- (void)onForwardToAllBtnClickNotify:(id)arg1;
- (void)hidePhotoBrowserAnimationDidStop:(id)arg1 finished:(id)arg2 context:(void *)arg3;
- (void)hidePhotoBrowserIfNotLongImage;
- (void)hidePhotoBrowserIfLongImage;
- (void)doDismissMySelf;
- (void)hidePhotoBrowser;
- (void)removeMaskView;
- (void)showPhotoBrowserAnimationDidStop:(id)arg1 finished:(id)arg2 context:(void *)arg3;
- (void)showPhotoBrowserInViewController:(id)arg1;
- (void)tapMaskView;
- (void)showAvatarInViewController:(id)arg1 showRect:(struct CGRect)arg2;
- (void)showPhotoBrowserInViewController:(id)arg1 showRect:(struct CGRect)arg2;
- (void)setLastViewController:(id)arg1;
- (struct CGRect)browserGetThumbImageShowRect:(id)arg1 thumbRegion:(struct CGRect)arg2 inThumbRect:(struct CGRect)arg3;
- (id)createPhotoBrowserNavigationController;
- (struct CGRect)getOriginalRectForPhoto:(id)arg1 atIndex:(int)arg2 thumbRegion:(struct CGRect *)arg3 clipRect:(struct CGRect *)arg4;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)handleUIApplicationDidEnterBackgroundNotification:(id)arg1;
- (int)getCurrentImageViewImageState;
- (void)deleteCurrentPhoto;
- (id)getCurrentPhoto;
- (id)getAllPhotos;
- (long long)getCurrentPhotoIndex;
- (id)getCurrentViewController;
- (id)getCurrentImage;
- (id)getCurrentImagePath;
- (void)onRightButtonClick:(id)arg1;
- (void)onLeftButtonClick:(id)arg1;
- (id)getForwardActionItems;
- (id)getToolbarItems;
- (id)forwardToQZoneAlbumActionItem;
- (id)getToolbar;
- (id)getPageControl;
- (void)setNavigationBarHidden:(_Bool)arg1;
- (void)setControlsHidden:(_Bool)arg1 animated:(_Bool)arg2;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (struct CGRect)frameForBackViewAtOrientation:(long long)arg1;
- (struct CGRect)frameForToolbarAtOrientation:(long long)arg1;
- (struct CGRect)frameForPageControl:(long long)arg1;
- (struct CGRect)frameForNavigationBarAtOrientation:(long long)arg1;
- (struct CGRect)frameForPagingScrollView;
- (void)deletePhotos:(long long)arg1 atIndex:(long long)arg2;
- (void)insertPhotos:(id)arg1 atIndex:(long long)arg2;
- (void)setCurrentPage:(long long)arg1;
- (void)setPhotoCaptions:(id)arg1;
- (void)setThumbRects:(id)arg1;
- (void)setPhotoAssets:(id)arg1;
- (void)setPhotoPaths:(id)arg1;
- (void)setPhotoImages:(id)arg1;
- (void)setPhotoCount:(int)arg1;
- (void)resumeTinyVideo;
- (void)pauseTinyVideo;
- (id)currentTinyVideoView;
- (void)onIntterruptEnd;
- (void)onIntterruptBegin;
- (void)onAudioSessionActive;
- (void)deactionAudioSession;
- (void)requestAudioSession;
- (void)presentTransitonDidStop;
- (_Bool)showDownloadFaidButton;
- (_Bool)photoBrowserDownloadFail;
- (void)didRotatePhoto:(id)arg1 toNewOrientation:(long long)arg2;
- (_Bool)canDownloadThisPhoto:(int)arg1 currentPage:(int)arg2;
- (void)ResetToolbarViewFrame;
- (void)setToolbarViewShow;
- (_Bool)isToolbarViewShow;
- (void)playToolbarAnimation;
- (void)setToolbarViewHidden:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setPageControlHidden:(_Bool)arg1 animated:(_Bool)arg2;
- (_Bool)shouldPlayCurrentVideo;
- (void)updatePageControl;
- (_Bool)canShowPageControl;
- (void)resetNavigationBarTitle;
- (void)didScrollToPage:(int)arg1;
- (void)longPressDetected;
- (void)popupMenu;
- (_Bool)isQQAsset:(id)arg1;
- (void)singleTapDetected;
- (id)imageAtIndex:(int)arg1;
- (int)numberOfPages;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)loadView;
- (id)allocAndInitPhotoBrowserView;
- (void)dealloc;
- (void)releaseActionItems;
- (id)initWithPreviewImage:(id)arg1;
- (id)initWithPhotoCount:(int)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(nonatomic) _Bool enableCorrectThumbnailRect; // @dynamic enableCorrectThumbnailRect;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) id <PhotoBrowserViewControllerDelegate> photoBrowserDelegate; // @dynamic photoBrowserDelegate;
@property(nonatomic) struct CGRect sourceClipRect; // @dynamic sourceClipRect;
@property(readonly) Class superclass;

@end

