//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface QOFPacketJsonInfo : NSObject
{
    long long _bid;
    double _expired;
    long long _frequency;
    long long _version;
    long long _delay;
    int _xo;
}

+ (id)packetJsonInfoWithBid:(long long)arg1 jsonFile:(id)arg2;
- (id)description;
- (void)parseJsonFile:(id)arg1;
- (id)initWithBid:(long long)arg1 jsonFile:(id)arg2;

// Remaining properties
@property(nonatomic) long long bid; // @dynamic bid;
@property(nonatomic) long long delay; // @dynamic delay;
@property(nonatomic) double expired; // @dynamic expired;
@property(nonatomic) long long frequency; // @dynamic frequency;
@property(nonatomic) long long version; // @dynamic version;

@end

