//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GroupAIONotifyControl, NSArray, NSIndexPath, QQGroupChatViewController, UITableView, UITableViewCell;

@protocol QQAIOEventDispatcherProtocol <NSObject>

@optional
- (void)controller:(QQGroupChatViewController *)arg1 remindNotifyControlClicked:(GroupAIONotifyControl *)arg2;
- (void)controllerRemindNotifyCheckDone:(QQGroupChatViewController *)arg1;
- (void)controllerCheckNotifyMsg:(QQGroupChatViewController *)arg1;
- (void)controller:(QQGroupChatViewController *)arg1 endDisplayCell:(UITableViewCell *)arg2 forRowAtIndexPath:(NSIndexPath *)arg3 byUser:(_Bool)arg4;
- (void)controller:(QQGroupChatViewController *)arg1 willDisplayCell:(UITableViewCell *)arg2 forRowAtIndexPath:(NSIndexPath *)arg3 byUser:(_Bool)arg4;
- (void)controller:(QQGroupChatViewController *)arg1 EndScrollBySetContenOffset:(UITableView *)arg2;
- (void)controller:(QQGroupChatViewController *)arg1 OnDraggingInTableView:(UITableView *)arg2;
- (void)controller:(QQGroupChatViewController *)arg1 EndDraggingInTableView:(UITableView *)arg2 speed:(double)arg3 byUser:(_Bool)arg4;
- (void)controller:(QQGroupChatViewController *)arg1 BeginDraggingInTableView:(UITableView *)arg2;
- (void)controller:(QQGroupChatViewController *)arg1 EndScrollInTableView:(UITableView *)arg2;
- (void)controller:(QQGroupChatViewController *)arg1 BeginScrollInTableView:(UITableView *)arg2;
- (void)controller:(QQGroupChatViewController *)arg1 didEndScroll:(UITableView *)arg2;
- (void)controllerDealloc:(QQGroupChatViewController *)arg1;
- (void)controllerViewDidDisappear:(QQGroupChatViewController *)arg1;
- (void)controllerOnStartPopping:(QQGroupChatViewController *)arg1 controllers:(NSArray *)arg2;
- (void)controllerViewWillDisappear:(QQGroupChatViewController *)arg1;
- (void)controllerPopViewController:(QQGroupChatViewController *)arg1;
- (void)controllerLeftButtonClick:(QQGroupChatViewController *)arg1 sender:(id)arg2;
- (void)controllerViewDidAppear:(QQGroupChatViewController *)arg1;
- (void)controllerViewDidLayoutSubviews:(QQGroupChatViewController *)arg1;
- (void)controllerViewWillAppear:(QQGroupChatViewController *)arg1;
- (void)controllerViewDidLoad:(QQGroupChatViewController *)arg1;
- (void)controllerLoadView:(QQGroupChatViewController *)arg1;
- (void)controllerInit:(QQGroupChatViewController *)arg1;
@end

