//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface QQAsyncSysNotification : NSObject
{
}

+ (void)onAppResignActive;
+ (void)onAppEnterBackground;
+ (void)onAppBecomeActive;
+ (void)onAppEnterForeground;
+ (void)addObserverToSys;
+ (void)doAsyncTask:(CDUnknownBlockType)arg1;

@end

