//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface QQFaceDataItem : NSObject
{
    int _emojiTabbarType;
    id _data;
}

@property(nonatomic) int emojiTabbarType; // @synthesize emojiTabbarType=_emojiTabbarType;
@property(retain, nonatomic) id data; // @synthesize data=_data;
- (void)dealloc;

@end

