//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class QQFileImageModel, UIImage, UIImageView;

@interface QQFileImageInterView : UIView
{
    UIImage *_image;
    UIView *_maskView;
    UIImageView *_selImage;
    _Bool _isEdit;
    _Bool _isSelected;
    QQFileImageModel *_model;
    id <QQFileImageInterViewDelegate> _delegate;
    int _xo;
}

- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)drawRect:(struct CGRect)arg1;
- (void)loadImageFromFile;
@property(retain, nonatomic) QQFileImageModel *model; // @dynamic model;
@property(nonatomic) _Bool isEdit; // @dynamic isEdit;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(nonatomic) id <QQFileImageInterViewDelegate> delegate; // @dynamic delegate;

@end

