//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQCustomActionSheet.h"

@interface QQFontSizeActionSheet : QQCustomActionSheet
{
}

- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)showInView:(id)arg1;
- (id)getSeperatorViewAtPositionX:(double)arg1;
- (id)initWithDelegate:(id)arg1;

@end

