//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "QQDragCollectionViewLayoutDataSource.h"
#import "QQDragCollectionViewLayoutDelegate.h"

@class NSMutableArray, NSString, QQDragCellFakeView, QQDragCollectionViewLayout, UICollectionView, UIColor, UIFont, UILabel;

@interface QQGroupFaceWallUI : UIView <QQDragCollectionViewLayoutDataSource, QQDragCollectionViewLayoutDelegate>
{
    UIFont *_infoTextStringFont;
    UIColor *_infoTextColor;
    UIColor *_textLabelBackgroundColor;
    NSString *_infoTextString;
    UIColor *_allBackGroundColor;
    _Bool _bIsNeedDisplayTextLabel;
    id <QQGroupFaceWallDelegate> _faceWallDelegate;
    id <QQGroupFaceWallForClickDelegate> _faceWallForClickDelegate;
    int _xo;
    UILabel *_textLabel;
    NSMutableArray *_currentData;
    struct CGSize _imageSize;
    UIView *_lineView;
    UICollectionView *_cltView;
    QQDragCollectionViewLayout *_layout;
    QQDragCellFakeView *_cellFakeView;
    long long preSelectedIndex;
    _Bool _isFromGroupProfileView;
    long long _currentPage;
}

@property(nonatomic) _Bool isFromGroupProfileView; // @synthesize isFromGroupProfileView=_isFromGroupProfileView;
@property(retain, nonatomic) NSMutableArray *currentData; // @synthesize currentData=_currentData;
@property(nonatomic) long long currentPage; // @synthesize currentPage=_currentPage;
@property(nonatomic) id <QQGroupFaceWallForClickDelegate> faceWallForClickDelegate; // @synthesize faceWallForClickDelegate=_faceWallForClickDelegate;
- (void).cxx_destruct;
- (struct CGRect)getCellRectAtIndex:(long long)arg1;
- (long long)getIndexBytag:(long long)arg1;
- (long long)getTagByIndex:(long long)arg1;
- (id)getCellBytag:(long long)arg1;
- (id)getCellAtIndex:(long long)arg1;
- (void)removeItemAtIndex:(long long)arg1;
- (void)refreshAllItem;
- (void)cancelSelectedCollectionView:(id)arg1;
- (void)setSelectedCollectionView:(id)arg1;
- (void)refreshSelecteState;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)layoutSubviews;
- (void)calcShowFrame;
- (void)reloadData;
@property(nonatomic) _Bool bIsNeedDisplayTextLabel; // @dynamic bIsNeedDisplayTextLabel;
@property(nonatomic) id <QQGroupFaceWallDelegate> faceWallDelegate; // @dynamic faceWallDelegate;
@property(retain, nonatomic) UIColor *allBackGroundColor; // @dynamic allBackGroundColor;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(copy, nonatomic) NSString *infoTextString; // @dynamic infoTextString;
@property(readonly) Class superclass;

@end

