//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQGroupFileInfo.h"

@class NSMutableArray, NSString;

@interface QQGroupFileSearchInfo : QQGroupFileInfo
{
    NSString *_groupName;
    NSString *_matchStr;
    NSString *_orgSearchStr;
    unsigned long long _matchUin;
    NSMutableArray *_matchArry;
}

@property(retain, nonatomic) NSMutableArray *matchArry; // @synthesize matchArry=_matchArry;
@property(nonatomic) unsigned long long matchUin; // @synthesize matchUin=_matchUin;
@property(copy, nonatomic) NSString *orgSearchStr; // @synthesize orgSearchStr=_orgSearchStr;
@property(copy, nonatomic) NSString *matchStr; // @synthesize matchStr=_matchStr;
@property(copy, nonatomic) NSString *groupName; // @synthesize groupName=_groupName;
- (void).cxx_destruct;

@end

