//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "QUIAlertPlusViewDelegate.h"
#import "QUIAlertViewDelegate.h"
#import "TVKLitePlaybackDelegate.h"

@class NSString, QQPublicAccountFaceImageView, QUIAlertPlusView, SSProgressView, TVKLitePlayer;

@interface QQPARNVideoView : UIView <QUIAlertPlusViewDelegate, QUIAlertViewDelegate, TVKLitePlaybackDelegate>
{
    int _playState;
    SSProgressView *_circleView;
    int _firstScreen;
    _Bool _isAlowPlayingNotWifi;
    _Bool _isRePlaying;
    _Bool _isUserStop;
    TVKLitePlayer *_player;
    NSString *_puin;
    NSString *_vid;
    NSString *_pic_url;
    QQPublicAccountFaceImageView *_bkImage;
    UIView *_bgView;
    QUIAlertPlusView *_alertViewResumePlay;
}

@property(nonatomic) _Bool isUserStop; // @synthesize isUserStop=_isUserStop;
@property(nonatomic) _Bool isRePlaying; // @synthesize isRePlaying=_isRePlaying;
@property(retain, nonatomic) QUIAlertPlusView *alertViewResumePlay; // @synthesize alertViewResumePlay=_alertViewResumePlay;
@property(nonatomic) _Bool isAlowPlayingNotWifi; // @synthesize isAlowPlayingNotWifi=_isAlowPlayingNotWifi;
@property(retain, nonatomic) UIView *bgView; // @synthesize bgView=_bgView;
@property(retain, nonatomic) QQPublicAccountFaceImageView *bkImage; // @synthesize bkImage=_bkImage;
@property(copy, nonatomic) NSString *pic_url; // @synthesize pic_url=_pic_url;
@property(copy, nonatomic) NSString *vid; // @synthesize vid=_vid;
@property(copy, nonatomic) NSString *puin; // @synthesize puin=_puin;
@property(retain, nonatomic) TVKLitePlayer *player; // @synthesize player=_player;
- (void).cxx_destruct;
- (void)onStartVideoChatNotification:(id)arg1;
- (void)RNViewClick:(id)arg1;
- (void)PACardViewControllerEvent:(id)arg1;
- (void)hideLoading;
- (void)showLoadingView;
- (_Bool)needShowLoadingView;
- (void)mediaPlayer:(id)arg1 stateChanged:(int)arg2 withError:(id)arg3;
- (void)pauseVideoRetry:(id)arg1 bStopWhenFailed:(_Bool)arg2;
- (void)rePlayVideo;
- (void)autoPlayVideo;
- (void)startPlayVideo;
- (void)alertView:(id)arg1 clickedKeyWord:(id)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (_Bool)initPlayerView;
- (void)layoutSubviews;
- (_Bool)isNetworkAvailableNow;
- (void)dealloc;
- (id)initWithProps:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

