//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIImageView;

@interface QQPPPopMenuBtn : UITableViewCell
{
    UIImageView *_backgroundImageView;
}

@property(retain, nonatomic) UIImageView *backgroundImageView; // @synthesize backgroundImageView=_backgroundImageView;
- (void)drawRect:(struct CGRect)arg1;
- (void)dealloc;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;

@end

