//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "PhotoEditDelegate.h"
#import "QQImagePickerBottomBarDelegate.h"
#import "QQImageSend2TroopAlbumBottomBarDelegate.h"
#import "QQPicScrollPreviewDelegate.h"
#import "QQRichShortVideoPreviewViewControllerDelegate.h"

@class NSMutableArray, NSString, QQAsset, QQAssetView, QQImagePickerBottomBar, QQImageSend2TroopAlbumBottomBar, QQPicScrollPreview, QzoneFeedModel, UIButton, UIImageView, UILabel;

@interface QQRecentPicPreview : UIView <QQImageSend2TroopAlbumBottomBarDelegate, QQPicScrollPreviewDelegate, QQRichShortVideoPreviewViewControllerDelegate, QQImagePickerBottomBarDelegate, PhotoEditDelegate>
{
    NSMutableArray *_assetsList;
    NSMutableArray *_allAssetsList;
    int _picNumber;
    _Bool _hasSelectedVideo;
    _Bool _hasSelectedPhoto;
    _Bool _hasAuthorize;
    UILabel *_noPhotolabel;
    QQPicScrollPreview *_preview;
    QQImagePickerBottomBar *_bottomBar;
    QQAsset *_longTappedAsset;
    _Bool _willSendOriPic;
    _Bool _hasShortVideoPreview;
    UIImageView *_backImgView;
    UIImageView *_oriBackView;
    UIButton *_tipLabel;
    QQAssetView *_oriView;
    QQAssetView *_draggedView;
    struct CGPoint _locationInPreView;
    struct CGPoint _beginP;
    struct CGPoint _endP;
    struct CGRect _originalFrame;
    float _timeUp;
    float _timeDown;
    _Bool _isFlashModel;
    _Bool _needShowTipsByDev;
    _Bool _isReadyForChangeNotification;
    _Bool _isSupportQunUpload;
    long long _minQunUploadCount;
    QQImageSend2TroopAlbumBottomBar *_troopAlbumBottomBar;
    _Bool _hasGroupAlbumUploadPermission;
    QzoneFeedModel *_choosedTroopAlbumFeedModel;
    _Bool _delayAnimStopTips;
    _Bool _shouldCancelPreupload;
    _Bool _isDraggingImageFinishSended;
    _Bool _isShareDocxEntry;
    int _maxSelectedCount;
    id <QQRecentPicPreviewDelegate> _delegate;
    NSString *_sendButtonTitle;
    NSString *_curGroupCode;
}

+ (int)preFilter;
+ (void)setPreFilter:(int)arg1;
@property(retain, nonatomic) NSString *curGroupCode; // @synthesize curGroupCode=_curGroupCode;
@property(retain, nonatomic) NSString *sendButtonTitle; // @synthesize sendButtonTitle=_sendButtonTitle;
@property(nonatomic) _Bool isShareDocxEntry; // @synthesize isShareDocxEntry=_isShareDocxEntry;
@property(nonatomic) _Bool isDraggingImageFinishSended; // @synthesize isDraggingImageFinishSended=_isDraggingImageFinishSended;
@property(nonatomic) _Bool shouldCancelPreupload; // @synthesize shouldCancelPreupload=_shouldCancelPreupload;
@property(nonatomic) int maxSelectedCount; // @synthesize maxSelectedCount=_maxSelectedCount;
@property(nonatomic) __weak id <QQRecentPicPreviewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)manualClickBottomBarSendButton;
- (struct CGRect)rectForEditBtn;
- (struct CGRect)rectForFirstPicSelectView;
- (id)getDraggedView;
- (void)recentPicPreviewHidden;
- (void)draggedViewWillBesendedActSend:(_Bool)arg1;
- (void)draggedViewWillBeSendedAct:(_Bool)arg1;
- (void)draggedViewWillBeSended;
- (void)draggedViewWillDismissAnimate:(_Bool)arg1;
- (void)animationStopTipsCompleteBlock:(CDUnknownBlockType)arg1;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)dismissAnimation:(struct CGPoint)arg1 withVelocity:(struct CGPoint)arg2 finalPoint:(struct CGPoint)arg3 scale:(float)arg4;
- (void)handlePanGesture:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)photoEditor:(id)arg1 didFinishWithImage:(id)arg2 asset:(id)arg3 shouldOpenDoodle:(_Bool)arg4 hasEdited:(_Bool)arg5;
- (void)photoEditorDidCancel:(id)arg1;
- (void)_gotoPhotoEditControllerWithAsset:(id)arg1 userInfo:(id)arg2;
- (void)_cleanIsAllSelectedPhotoLessThanCompleteBlock;
- (void)_isAllSelectedPhotoLessThan:(long long)arg1 curIndex:(int)arg2;
- (void)_isAllSelectedPhotoLessThan:(long long)arg1 completeBlock:(CDUnknownBlockType)arg2;
- (void)QQImagePickerBottomBarSendButtonDidClick;
- (void)QQImagePickerBottomBarSizeButtonDidClick:(_Bool)arg1;
- (void)QQImagePickerBottomBarEditButtonDidClick;
- (void)QQImagePickerBottomBarLibraryButtonDidClick;
- (void)previewControllerCanceledWhenProcessing:(id)arg1;
- (void)previewControllerCanceled:(id)arg1;
- (void)previewControllerDidSelected:(id)arg1;
- (void)handleLongGestrue:(id)arg1 isSelected:(_Bool)arg2;
- (void)_getSelectedPhotoSizeStringForOriginalCompleteBlock:(CDUnknownBlockType)arg1;
- (void)_cleanGetSelectedPhotoSizeCompleteBlock;
- (void)_getSelectedPhotoSizeCursize:(long long)arg1 curIndex:(int)arg2;
- (void)_getSelectedPhotoSizeCompleteBlock:(CDUnknownBlockType)arg1;
- (_Bool)canRememberUpload:(long long)arg1 groupCode:(long long)arg2;
- (void)QQImageSend2TroopAlbumBottomBarDidSelectCheckBox:(id)arg1 withFeedModel:(id)arg2;
- (void)configQunUploadBarWithSelectedCount:(long long)arg1;
- (void)refreshBottomBarAct;
- (void)refreshBottomBar:(id)arg1 isSelected:(_Bool)arg2;
- (void)loadAllAssetsList:(CDUnknownBlockType)arg1;
- (void)loadRecentAssetsList:(CDUnknownBlockType)arg1;
- (void)refreshAllViewsAfterSended;
- (void)refreshAllViews;
- (void)selectedPhotoListChanged:(id)arg1;
- (void)albumChanged;
- (_Bool)isSupportRightDragToGoBack;
- (void)_initData;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 sendButtonTitle:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setIsSizeButtonShow:(_Bool)arg1;
- (void)unsetFlashSetting;
- (void)setFlashSetting;
- (id)viewController;
- (void)setHasShortVideoPreviewFlag:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

