//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "QQMessageListRefreshControlProtocal.h"

@class NSString, QQMessageView;

@interface QQRecentViewRefreshControlModule : NSObject <QQMessageListRefreshControlProtocal>
{
    QQMessageView *_controlObject;
    double _lastReloadTime;
    _Bool _hasNewMessage;
    _Bool _isScrolling;
}

@property(nonatomic) double lastReloadTime; // @synthesize lastReloadTime=_lastReloadTime;
- (void)reloadMessagelistCurrently;
- (void)_reloadWithFrequencyControl:(id)arg1;
- (void)reloadViewForQQRecentController;
- (void)reloadMessageViewWithData;
- (void)_reloadViewForQQMessageView;
- (void)_reloadMessageView:(id)arg1;
- (_Bool)isNeedRefreshMessageList:(_Bool)arg1;
- (void)_startRefreshMessageList;
- (void)stopRefreshMessageList;
- (void)delayStartRefreshMessageList;
- (void)dealloc;
- (id)initWithView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

