//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "QQStructureMsgUtilityDelegate.h"

@class NSString, QQRichMsgPreviewDialog, QQShare2CollectRichMsgTask, QQShare2FriendWebRichMsgTask, QQShare2QZoneWebRichMsgTask, QQShare2ReadInJoyWebRichMsgTask, QQShare2SinaWeiboWebRichMsgTask, QQShare2WeChatWebRichMsgTask, QQShareAIOWebRichMsgData, UIViewController;

@interface QQShareWebRichMsgLogic : NSObject <QQStructureMsgUtilityDelegate>
{
    QQShare2QZoneWebRichMsgTask *_share2QZoneTask;
    QQShare2FriendWebRichMsgTask *_share2FriendTask;
    QQShare2WeChatWebRichMsgTask *_share2WeChatTask;
    QQShare2SinaWeiboWebRichMsgTask *_share2SinaWeiboTask;
    QQRichMsgPreviewDialog *_richPreMsgDlg;
    QQShareAIOWebRichMsgData *_richMsgData;
    _Bool _share2AIOing;
    QQShare2ReadInJoyWebRichMsgTask *_share2ReadInJoyTask;
    QQShare2CollectRichMsgTask *_share2CollectTask;
    int _xo;
    UIViewController *_ownerUI;
}

+ (id)subString:(id)arg1 withMaxlen:(long long)arg2;
+ (id)checkString:(id)arg1 WithLength:(unsigned long long)arg2;
+ (id)checkTitleAndSummary:(id)arg1 Summary:(id)arg2;
@property(retain, nonatomic) QQShare2CollectRichMsgTask *share2CollectTask; // @synthesize share2CollectTask=_share2CollectTask;
@property(retain, nonatomic) QQShare2SinaWeiboWebRichMsgTask *share2SinaWeiboTask; // @synthesize share2SinaWeiboTask=_share2SinaWeiboTask;
@property(nonatomic) UIViewController *ownerUI; // @synthesize ownerUI=_ownerUI;
- (void)shareOperationResultCode:(int)arg1 otherArgment:(id)arg2;
- (id)creatXMLMessageString:(id)arg1;
- (void)openChatUI:(id)arg1;
- (void)sendShareMsg:(id)arg1;
- (void)processPreviewImage:(id)arg1;
- (id)getThirdAppName:(id)arg1;
- (void)cancelButtonClick;
- (void)sendButtonClick:(id)arg1 msg:(id)arg2;
- (void)popQQRichPreMsgDlg:(id)arg1;
- (void)share2AIO:(id)arg1;
- (void)share2AIOWebRichMsg:(id)arg1;
- (void)share2AIOWithoutPullingSelectView:(id)arg1;
- (void)reportBeforShareCatchInfo:(id)arg1 toType:(int)arg2;
- (void)share2SinaWeiboWithWebRichMsg:(id)arg1;
- (void)share2WeChatCircleWithWebRichMsg:(id)arg1;
- (void)share2WeChatFriendWithWebRichMsg:(id)arg1;
- (void)share2ReadInJoyWebRichMsg:(id)arg1;
- (void)share2QZoneWebRichMsg:(id)arg1;
- (void)share2FriendWebRichMsg:(id)arg1;
- (void)share2Collect:(id)arg1;
@property(retain, nonatomic) QQShare2WeChatWebRichMsgTask *share2WeChatTask; // @dynamic share2WeChatTask;
- (void)dealloc;
- (id)initWithOwner:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) QQShareAIOWebRichMsgData *richMsgData; // @dynamic richMsgData;
@property(retain, nonatomic) QQRichMsgPreviewDialog *richPreMsgDlg; // @dynamic richPreMsgDlg;
@property(nonatomic) _Bool share2AIOing; // @dynamic share2AIOing;
@property(retain, nonatomic) QQShare2FriendWebRichMsgTask *share2FriendTask; // @dynamic share2FriendTask;
@property(retain, nonatomic) QQShare2QZoneWebRichMsgTask *share2QZoneTask; // @dynamic share2QZoneTask;
@property(retain, nonatomic) QQShare2ReadInJoyWebRichMsgTask *share2ReadInJoyTask; // @dynamic share2ReadInJoyTask;
@property(readonly) Class superclass;

@end

