//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface QQSportUpLoadManager : NSObject
{
    NSMutableArray *_upLoadQueue;
}

+ (id)getInstance;
@property(retain, nonatomic) NSMutableArray *upLoadQueue; // @synthesize upLoadQueue=_upLoadQueue;
- (void)onAccountChanged:(id)arg1;
- (id)getModelWithGroupID:(long long)arg1;
- (id)getProgressList;
- (id)getVideoList;
- (long long)videoCount;
- (_Bool)containsGroupModelWithGroupID:(long long)arg1;
- (void)removeGroupModelWithGroupID:(long long)arg1 needClearInfo:(_Bool)arg2;
- (void)addUploadGroupModel:(id)arg1;
- (id)init;

@end

