//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQRelationSearchFilter.h"

@interface QQTempChatFilter : QQRelationSearchFilter
{
    long long _noSearchItem;
}

- (_Bool)p_isCustomNoSearchItem:(id)arg1;
- (_Bool)p_isDefaultNoSearchItem:(id)arg1;
- (id)copyAllSearchResults:(id)arg1 excludeUinList:(id)arg2;
- (id)initWithNoSearchItem:(long long)arg1;
- (id)init;

@end

