//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class QQWalletImageDownloader, UIButton, UIImageView, UILabel;

@interface QQWalletTipsView : UIView
{
    id <QQWalletTipsViewDelegate> _delegate;
    _Bool _showCloseButton;
    id userInfo;
    UIImageView *_iconView;
    UILabel *_tipsLable;
    UIImageView *_rpIconView;
    UIImageView *_arrowView;
    UIButton *_closeButton;
    QQWalletImageDownloader *_iconDownloader;
    QQWalletImageDownloader *_rpIconDownloader;
    int _tipsType;
    id _tipsData;
}

@property(nonatomic) int tipsType; // @synthesize tipsType=_tipsType;
@property(retain, nonatomic) id tipsData; // @synthesize tipsData=_tipsData;
- (void).cxx_destruct;
- (void)downloader:(id)arg1 didFailWithError:(id)arg2 forURL:(id)arg3;
- (void)downloader:(id)arg1 didDownloadImage:(id)arg2 forURL:(id)arg3;
- (void)closeButtonDidTap:(id)arg1;
- (void)handleTapGestureRecognizer:(id)arg1;
- (void)layoutSubviews;
- (void)commonInit;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

