//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JceObjectV2.h"

@class NSDictionary, NSString, QZJFeedsSVideoremark;

@interface QZJFeedsCellVideo : JceObjectV2
{
}


// Remaining properties
@property(retain, nonatomic, getter=jce_videoid, setter=setJce_videoid:) NSString *jcev2_p_0_o_videoid; // @dynamic jcev2_p_0_o_videoid;
@property(nonatomic, getter=jce_playtype, setter=setJce_playtype:) BOOL jcev2_p_10_o_playtype; // @dynamic jcev2_p_10_o_playtype;
@property(nonatomic, getter=jce_videostatus, setter=setJce_videostatus:) int jcev2_p_11_o_videostatus; // @dynamic jcev2_p_11_o_videostatus;
@property(retain, nonatomic, getter=jce_toast, setter=setJce_toast:) NSString *jcev2_p_12_o_toast; // @dynamic jcev2_p_12_o_toast;
@property(retain, nonatomic, getter=jce_extendinfo, setter=setJce_extendinfo:) NSDictionary *jcev2_p_13_o_extendinfo__b0x9i_M09ONSStringONSString; // @dynamic jcev2_p_13_o_extendinfo__b0x9i_M09ONSStringONSString;
@property(retain, nonatomic, getter=jce_videoremark, setter=setJce_videoremark:) QZJFeedsSVideoremark *jcev2_p_14_o_videoremark; // @dynamic jcev2_p_14_o_videoremark;
@property(nonatomic, getter=jce_video_show_type, setter=setJce_video_show_type:) long long jcev2_p_15_o_video_show_type; // @dynamic jcev2_p_15_o_video_show_type;
@property(nonatomic, getter=jce_isPanorama, setter=setJce_isPanorama:) _Bool jcev2_p_16_o_isPanorama; // @dynamic jcev2_p_16_o_isPanorama;
@property(nonatomic, getter=jce_video_source, setter=setJce_video_source:) long long jcev2_p_17_o_video_source; // @dynamic jcev2_p_17_o_video_source;
@property(retain, nonatomic, getter=jce_sloc, setter=setJce_sloc:) NSString *jcev2_p_18_o_sloc; // @dynamic jcev2_p_18_o_sloc;
@property(retain, nonatomic, getter=jce_lloc, setter=setJce_lloc:) NSString *jcev2_p_19_o_lloc; // @dynamic jcev2_p_19_o_lloc;
@property(retain, nonatomic, getter=jce_videourl, setter=setJce_videourl:) NSString *jcev2_p_1_o_videourl; // @dynamic jcev2_p_1_o_videourl;
@property(nonatomic, getter=jce_report_video_feeds_type, setter=setJce_report_video_feeds_type:) int jcev2_p_20_o_report_video_feeds_type; // @dynamic jcev2_p_20_o_report_video_feeds_type;
@property(nonatomic, getter=jce_videoplaycnt, setter=setJce_videoplaycnt:) int jcev2_p_21_o_videoplaycnt; // @dynamic jcev2_p_21_o_videoplaycnt;
@property(nonatomic, getter=jce_is_share, setter=setJce_is_share:) _Bool jcev2_p_22_o_is_share; // @dynamic jcev2_p_22_o_is_share;
@property(nonatomic, getter=jce_adv_delay_time, setter=setJce_adv_delay_time:) int jcev2_p_23_o_adv_delay_time; // @dynamic jcev2_p_23_o_adv_delay_time;
@property(retain, nonatomic, getter=jce_video_webview_url, setter=setJce_video_webview_url:) NSString *jcev2_p_24_o_video_webview_url; // @dynamic jcev2_p_24_o_video_webview_url;
@property(nonatomic, getter=jce_isOnWifiPlay, setter=setJce_isOnWifiPlay:) _Bool jcev2_p_25_o_isOnWifiPlay; // @dynamic jcev2_p_25_o_isOnWifiPlay;
@property(nonatomic, getter=jce_isHadSetPlayOnWifi, setter=setJce_isHadSetPlayOnWifi:) _Bool jcev2_p_26_o_isHadSetPlayOnWifi; // @dynamic jcev2_p_26_o_isHadSetPlayOnWifi;
@property(retain, nonatomic, getter=jce_coverurl, setter=setJce_coverurl:) NSDictionary *jcev2_p_2_o_coverurl__b0x9i_M09ONSNumberOQZJFeedsSPicurl; // @dynamic jcev2_p_2_o_coverurl__b0x9i_M09ONSNumberOQZJFeedsSPicurl;
@property(nonatomic, getter=jce_actiontype, setter=setJce_actiontype:) int jcev2_p_3_o_actiontype; // @dynamic jcev2_p_3_o_actiontype;
@property(retain, nonatomic, getter=jce_actionurl, setter=setJce_actionurl:) NSString *jcev2_p_4_o_actionurl; // @dynamic jcev2_p_4_o_actionurl;
@property(retain, nonatomic, getter=jce_clientkey, setter=setJce_clientkey:) NSString *jcev2_p_5_o_clientkey; // @dynamic jcev2_p_5_o_clientkey;
@property(nonatomic, getter=jce_filetype, setter=setJce_filetype:) int jcev2_p_6_o_filetype; // @dynamic jcev2_p_6_o_filetype;
@property(nonatomic, getter=jce_videotype, setter=setJce_videotype:) BOOL jcev2_p_7_o_videotype; // @dynamic jcev2_p_7_o_videotype;
@property(nonatomic, getter=jce_videotime, setter=setJce_videotime:) unsigned int jcev2_p_8_o_videotime; // @dynamic jcev2_p_8_o_videotime;
@property(retain, nonatomic, getter=jce_videourls, setter=setJce_videourls:) NSDictionary *jcev2_p_9_o_videourls__b0x9i_M09ONSNumberOQZJFeedsSVideourl; // @dynamic jcev2_p_9_o_videourls__b0x9i_M09ONSNumberOQZJFeedsSVideourl;
@end

