//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QZPhotoReportModel.h"

@class NSString;

@interface QZPhotoUploadReportModel : QZPhotoReportModel
{
    NSString *_svrIp;
    NSString *_refer;
    NSString *_uppAppid;
    long long _cTime;
    long long _flow;
    long long _retry;
    long long _ipsrctype;
    long long _videoType;
}

@property(nonatomic) long long videoType; // @synthesize videoType=_videoType;
@property(nonatomic) long long ipsrctype; // @synthesize ipsrctype=_ipsrctype;
@property(nonatomic) long long retry; // @synthesize retry=_retry;
@property(nonatomic) long long flow; // @synthesize flow=_flow;
@property(nonatomic) long long cTime; // @synthesize cTime=_cTime;
@property(copy, nonatomic) NSString *uppAppid; // @synthesize uppAppid=_uppAppid;
@property(copy, nonatomic) NSString *refer; // @synthesize refer=_refer;
@property(copy, nonatomic) NSString *svrIp; // @synthesize svrIp=_svrIp;
- (void).cxx_destruct;

@end

