//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSString;

@interface ReadInJoySearchChannel : NSObject <NSCoding>
{
    unsigned int _channel_id;
    unsigned int _show_index;
    unsigned int _channel_type;
    unsigned int _channel_frame_color;
    unsigned int _channel_font_color;
    NSString *_channel_name;
    NSString *_channel_jump_url;
}

@property(retain, nonatomic) NSString *channel_jump_url; // @synthesize channel_jump_url=_channel_jump_url;
@property(nonatomic) unsigned int channel_font_color; // @synthesize channel_font_color=_channel_font_color;
@property(nonatomic) unsigned int channel_frame_color; // @synthesize channel_frame_color=_channel_frame_color;
@property(nonatomic) unsigned int channel_type; // @synthesize channel_type=_channel_type;
@property(nonatomic) unsigned int show_index; // @synthesize show_index=_show_index;
@property(nonatomic) unsigned int channel_id; // @synthesize channel_id=_channel_id;
@property(retain, nonatomic) NSString *channel_name; // @synthesize channel_name=_channel_name;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

