//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCFBaseCellView.h"

@class EmojiEggView, RichStateNewestFeedFastView, RichStateOneLineFastView, UIImageView, UILabel;

@interface SCFFriListCellView : SCFBaseCellView
{
    UILabel *_nicknameLabel;
    UIImageView *_vipImageView;
    UIImageView *_networkImageView;
    UILabel *_stateLabel;
    RichStateOneLineFastView *_richStateView;
    RichStateNewestFeedFastView *_newestFeedFastView;
    UIImageView *_onlineMaskView;
    UIImageView *_editArrowIcon;
    EmojiEggView *_emojiEggView;
}

- (void).cxx_destruct;
- (void)updateAccessibilityLabelWithEditStatus:(_Bool)arg1 voiceStr:(id)arg2;
- (void)layoutSubviewsForSCFManagerList;
- (void)setQZoneNewestFeedData:(id)arg1 withFrame:(struct CGRect)arg2;
- (void)setRichStateModel:(id)arg1 withFrame:(struct CGRect)arg2;
- (id)getSelfNetworkStringWithModel:(id)arg1;
- (void)layoutSubviewsForSCFriendList;
- (void)setScfCellSubviewsVisible:(id)arg1 isEditStatus:(_Bool)arg2;
- (void)loadCellWithSCFriendInfo:(id)arg1 isEditStatus:(_Bool)arg2 animated:(_Bool)arg3;
- (void)layoutSubviews;
- (void)initCellUI;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

