//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SDAVAssetExportSession;

@protocol SDAVAssetExportSessionDelegate <NSObject>
- (void)exportSession:(SDAVAssetExportSession *)arg1 renderFrame:(struct __CVBuffer *)arg2 withPresentationTime:(CDStruct_1b6d18a9)arg3 toBuffer:(struct __CVBuffer *)arg4;
@end

