//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSData, NSString, SSoVerifyViewController;

@protocol VerifyViewDelegate
- (_Bool)commitVerifyTicket:(NSData *)arg1 sessionID:(long long)arg2;
- (void)verifyCancelled:(SSoVerifyViewController *)arg1;
- (void)checkVerifyCode:(SSoVerifyViewController *)arg1 code:(NSString *)arg2;
- (void)refreshVerifyCode:(SSoVerifyViewController *)arg1;
@end

