//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CJSONSerializable.h"

@class NSData, NSString;

@interface CJSONSerializedData : NSObject <CJSONSerializable>
{
    NSData *data;
}

@property(readonly, retain, nonatomic) NSData *data; // @synthesize data;
@property(readonly, retain, nonatomic) NSData *serializedJSONData;
- (void)dealloc;
- (id)initWithData:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

