//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface CollectListMgr : NSObject
{
    NSMutableDictionary *collectLists;
    unsigned int lmVersion;
    int userID;
}

+ (id)collectLisgMgr;
- (int)listCount;
- (id)tokenCollectListItemDeleteResponse:(id)arg1;
- (id)collectListItemDeleteAll:(id)arg1;
- (id)collectListBatchItemDelete:(id)arg1 fileIDs:(id)arg2;
- (id)collectListItemDelete:(id)arg1 targetFileID:(unsigned int)arg2;
- (id)tokenCollectListItemModifyResponse:(id)arg1;
- (id)collectListBatchItemAdd:(id)arg1 targetSongInfo:(id)arg2;
- (id)collectListItemAdd:(id)arg1 targetSongInfo:(id)arg2;
- (id)tokenCollectListResponse:(id)arg1;
- (id)collectListModify:(id)arg1 targetName:(id)arg2 orderWeight:(int)arg3;
- (id)collectListDelete:(id)arg1;
- (id)collectListAdd:(id)arg1;
- (id)collectListInfoForListName:(id)arg1;
- (void)removeListInfoByListID:(unsigned int)arg1;
- (void)addListInfo:(id)arg1;
- (void)removeAllLists;
- (void)setUserID:(int)arg1;
- (int)userID;
- (void)setLmVersion:(unsigned int)arg1;
- (unsigned int)lmVersion;
- (void)dealloc;
- (id)init;

@end

