//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, UIButton, UILabel;

@interface ConcertCustomAlertView : UIView
{
    UIView *_contentView;
    UILabel *_titleLabel;
    UILabel *_messageLabel;
    UIButton *_cancelBtn;
    UIButton *_confirmBtn;
    UIView *_parentView;
    NSString *_title;
    NSString *_message;
    NSString *_cancelTitle;
    NSString *_confirmTitle;
    CDUnknownBlockType _clickedBlock;
}

@property(copy, nonatomic) CDUnknownBlockType clickedBlock; // @synthesize clickedBlock=_clickedBlock;
@property(retain, nonatomic) NSString *confirmTitle; // @synthesize confirmTitle=_confirmTitle;
@property(retain, nonatomic) NSString *cancelTitle; // @synthesize cancelTitle=_cancelTitle;
@property(retain, nonatomic) NSString *message; // @synthesize message=_message;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) UIView *parentView; // @synthesize parentView=_parentView;
@property(retain, nonatomic) UIButton *confirmBtn; // @synthesize confirmBtn=_confirmBtn;
@property(retain, nonatomic) UIButton *cancelBtn; // @synthesize cancelBtn=_cancelBtn;
@property(retain, nonatomic) UILabel *messageLabel; // @synthesize messageLabel=_messageLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
- (void).cxx_destruct;
- (void)dismiss;
- (void)show;
- (void)clickBtn:(id)arg1;
- (void)initView;
- (id)initWithParentView:(id)arg1 title:(id)arg2 message:(id)arg3 clickedBlock:(CDUnknownBlockType)arg4 cancelButtonTitle:(id)arg5 confirmButtonTitle:(id)arg6;

@end

