//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface ExtInfo : NSObject
{
    _Bool _isAdmin;
    _Bool _isVip;
    _Bool _isStarCard;
    NSString *_vipLevel;
}

@property(nonatomic) _Bool isStarCard; // @synthesize isStarCard=_isStarCard;
@property(copy, nonatomic) NSString *vipLevel; // @synthesize vipLevel=_vipLevel;
@property(nonatomic) _Bool isVip; // @synthesize isVip=_isVip;
@property(nonatomic) _Bool isAdmin; // @synthesize isAdmin=_isAdmin;
- (void).cxx_destruct;

@end

