//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FAView.h"

#import "FXDigitalAlbumCustomNumCellDelegate.h"

@class FADigitalAlbumCustomNumCell, NSArray, NSString, UIScrollView, UIView;

@interface FADigitalAlbumNumberChooseView : FAView <FXDigitalAlbumCustomNumCellDelegate>
{
    _Bool _isShowing;
    unsigned long long _numberType;
    NSString *_selectNum;
    id <FADigitalAlbumNumberChooseDelegate> _delegate;
    UIView *_bgView;
    UIScrollView *_gridView;
    NSArray *_numberArray;
    FADigitalAlbumCustomNumCell *_selectCell;
}

@property(retain, nonatomic) FADigitalAlbumCustomNumCell *selectCell; // @synthesize selectCell=_selectCell;
@property(retain, nonatomic) NSArray *numberArray; // @synthesize numberArray=_numberArray;
@property(retain, nonatomic) UIScrollView *gridView; // @synthesize gridView=_gridView;
@property(retain, nonatomic) UIView *bgView; // @synthesize bgView=_bgView;
@property(nonatomic) _Bool isShowing; // @synthesize isShowing=_isShowing;
@property(nonatomic) __weak id <FADigitalAlbumNumberChooseDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSString *selectNum; // @synthesize selectNum=_selectNum;
@property(nonatomic) unsigned long long numberType; // @synthesize numberType=_numberType;
- (void).cxx_destruct;
- (void)fxDigitalAlbumCustomNumCellSelected:(id)arg1;
- (void)cancelAction;
- (double)showHeight;
- (void)setupViews;
- (void)initData;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

