//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FAModel.h"

@class NSArray<FAMobileLiveClassify>;

@interface FAMobileLiveSuggestTopicModel : FAModel
{
    NSArray<FAMobileLiveClassify> *_suggestLabelList;
}

@property(retain, nonatomic) NSArray<FAMobileLiveClassify> *suggestLabelList; // @synthesize suggestLabelList=_suggestLabelList;
- (void).cxx_destruct;

@end

