//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FAUserLiveRoomBLL : NSObject
{
}

+ (void)ifUserIsStarWithstarKugouId:(long long)arg1 success:(CDUnknownBlockType)arg2 error:(CDUnknownBlockType)arg3;
+ (void)getUserStarRelWithRoomId:(id)arg1 roomType:(long long)arg2 succeed:(CDUnknownBlockType)arg3 fail:(CDUnknownBlockType)arg4;

@end

