//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class KGSkinButton, KGSkinLabel, UIButton;

@interface FM_MineHeader : UIView
{
    int headtype;
    KGSkinButton *logo;
    KGSkinLabel *title;
    UIButton *moreBtn;
    id <FMMineHeaderDelegate> _delegate;
}

@property(nonatomic) __weak id <FMMineHeaderDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)initWithHeaderType:(int)arg1 andFrame:(struct CGRect)arg2;
- (void)moreBtnClick:(id)arg1;
- (void)setMoreBtnHidden:(_Bool)arg1;
- (int)type;
- (id)initWithFrame:(struct CGRect)arg1;

@end

