//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImageView;

@interface FXAYPlayLikeAnimationView : UIView
{
    UIImageView *_linghtHaloImgView;
    UIImageView *_haloImgView;
    UIImageView *_lightImgView;
    UIImageView *_thumbImgView;
    UIImageView *_starImgView;
    UIImageView *_star1ImgView;
    UIImageView *_star2ImgView;
    UIImageView *_shineImgView;
    UIImageView *_shine1ImgView;
    UIImageView *_shine2ImgView;
    UIImageView *_shine3ImgView;
}

+ (void)showAnimationInView:(id)arg1;
@property(retain, nonatomic) UIImageView *shine3ImgView; // @synthesize shine3ImgView=_shine3ImgView;
@property(retain, nonatomic) UIImageView *shine2ImgView; // @synthesize shine2ImgView=_shine2ImgView;
@property(retain, nonatomic) UIImageView *shine1ImgView; // @synthesize shine1ImgView=_shine1ImgView;
@property(retain, nonatomic) UIImageView *shineImgView; // @synthesize shineImgView=_shineImgView;
@property(retain, nonatomic) UIImageView *star2ImgView; // @synthesize star2ImgView=_star2ImgView;
@property(retain, nonatomic) UIImageView *star1ImgView; // @synthesize star1ImgView=_star1ImgView;
@property(retain, nonatomic) UIImageView *starImgView; // @synthesize starImgView=_starImgView;
@property(retain, nonatomic) UIImageView *thumbImgView; // @synthesize thumbImgView=_thumbImgView;
@property(retain, nonatomic) UIImageView *lightImgView; // @synthesize lightImgView=_lightImgView;
@property(retain, nonatomic) UIImageView *haloImgView; // @synthesize haloImgView=_haloImgView;
@property(retain, nonatomic) UIImageView *linghtHaloImgView; // @synthesize linghtHaloImgView=_linghtHaloImgView;
- (void).cxx_destruct;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)startAnimation;
- (void)initViews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

