//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "KugouObject.h"

#import "NSCoding.h"

@class NSString;

@interface FXChartsListObject : KugouObject <NSCoding>
{
    int _rank;
    int _level;
    int _pop;
    int _num;
    long long _userId;
    NSString *_nickName;
    NSString *_userLogo;
    NSString *_starIcon;
    long long _roomId;
    NSString *_richIcon;
    long long _cost;
}

+ (id)transformChartsListObjectArray:(id)arg1;
+ (id)transformFromCharVo:(id)arg1;
@property(nonatomic) int num; // @synthesize num=_num;
@property(nonatomic) int pop; // @synthesize pop=_pop;
@property(nonatomic) int level; // @synthesize level=_level;
@property(nonatomic) long long cost; // @synthesize cost=_cost;
@property(copy, nonatomic) NSString *richIcon; // @synthesize richIcon=_richIcon;
@property(nonatomic) long long roomId; // @synthesize roomId=_roomId;
@property(copy, nonatomic) NSString *starIcon; // @synthesize starIcon=_starIcon;
@property(copy, nonatomic) NSString *userLogo; // @synthesize userLogo=_userLogo;
@property(copy, nonatomic) NSString *nickName; // @synthesize nickName=_nickName;
@property(nonatomic) long long userId; // @synthesize userId=_userId;
@property(nonatomic) int rank; // @synthesize rank=_rank;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

