//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImageView;

@interface FXKGLivePlayerStatusView : UIView
{
    UIImageView *_imgView;
    UIView *_contentView;
    double _hw;
}

@property(nonatomic) double hw; // @synthesize hw=_hw;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) UIImageView *imgView; // @synthesize imgView=_imgView;
- (void).cxx_destruct;
- (void)dismissStatus;
- (void)setLoadingTip:(id)arg1;
- (void)setNoLiveTip:(id)arg1;
- (void)setErrorTip:(id)arg1;
- (void)setStateWithImgName:(id)arg1 text:(id)arg2;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

