//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FXBaseJSONModel.h"

@class NSString;

@interface FXSKGLiveGiftInfo : FXBaseJSONModel
{
    int _canNotSend;
    float _exchange;
    int _extraType;
    int _fly;
    int _guardLevelLimit;
    int _isNew;
    int _isPile;
    int _mix;
    int _platformType;
    int _richLevelLimit;
    int _status;
    int _vipLimit;
    long long _category;
    NSString *_className;
    NSString *_customValue;
    long long _expire;
    NSString *_extra;
    long long _giftId;
    NSString *_image;
    NSString *_imageTrans;
    NSString *_name;
    NSString *_pic;
    long long _price;
    long long _sortIndex;
    NSString *_url;
    long long _userIdLimit;
}

+ (id)keyMapper;
@property(nonatomic) int vipLimit; // @synthesize vipLimit=_vipLimit;
@property(nonatomic) long long userIdLimit; // @synthesize userIdLimit=_userIdLimit;
@property(retain, nonatomic) NSString *url; // @synthesize url=_url;
@property(nonatomic) int status; // @synthesize status=_status;
@property(nonatomic) long long sortIndex; // @synthesize sortIndex=_sortIndex;
@property(nonatomic) int richLevelLimit; // @synthesize richLevelLimit=_richLevelLimit;
@property(nonatomic) long long price; // @synthesize price=_price;
@property(nonatomic) int platformType; // @synthesize platformType=_platformType;
@property(retain, nonatomic) NSString *pic; // @synthesize pic=_pic;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) int mix; // @synthesize mix=_mix;
@property(nonatomic) int isPile; // @synthesize isPile=_isPile;
@property(nonatomic) int isNew; // @synthesize isNew=_isNew;
@property(retain, nonatomic) NSString *imageTrans; // @synthesize imageTrans=_imageTrans;
@property(retain, nonatomic) NSString *image; // @synthesize image=_image;
@property(nonatomic) long long giftId; // @synthesize giftId=_giftId;
@property(nonatomic) int guardLevelLimit; // @synthesize guardLevelLimit=_guardLevelLimit;
@property(nonatomic) int fly; // @synthesize fly=_fly;
@property(nonatomic) int extraType; // @synthesize extraType=_extraType;
@property(retain, nonatomic) NSString *extra; // @synthesize extra=_extra;
@property(nonatomic) long long expire; // @synthesize expire=_expire;
@property(nonatomic) float exchange; // @synthesize exchange=_exchange;
@property(retain, nonatomic) NSString *customValue; // @synthesize customValue=_customValue;
@property(retain, nonatomic) NSString *className; // @synthesize className=_className;
@property(nonatomic) long long category; // @synthesize category=_category;
@property(nonatomic) int canNotSend; // @synthesize canNotSend=_canNotSend;
- (void).cxx_destruct;

@end

