//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FXKGLiveViewerNumView, KGDefaultTopView, UIButton, UILabel;

@interface InterviewTopViewVll : NSObject
{
    KGDefaultTopView *_topView;
    FXKGLiveViewerNumView *_viewerNumView;
    UIButton *_leftMaskBtn;
    UILabel *_titleLabel;
    UIButton *_shareBtn;
    UIButton *_openOrCloseBarragesBtn;
    UIButton *_hdButton;
    UIButton *_normalButton;
    UIButton *_backBtn;
}

@property(retain, nonatomic) UIButton *backBtn; // @synthesize backBtn=_backBtn;
@property(retain, nonatomic) UIButton *normalButton; // @synthesize normalButton=_normalButton;
@property(retain, nonatomic) UIButton *hdButton; // @synthesize hdButton=_hdButton;
@property(retain, nonatomic) UIButton *openOrCloseBarragesBtn; // @synthesize openOrCloseBarragesBtn=_openOrCloseBarragesBtn;
@property(retain, nonatomic) UIButton *shareBtn; // @synthesize shareBtn=_shareBtn;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIButton *leftMaskBtn; // @synthesize leftMaskBtn=_leftMaskBtn;
@property(retain, nonatomic) FXKGLiveViewerNumView *viewerNumView; // @synthesize viewerNumView=_viewerNumView;
@property(retain, nonatomic) KGDefaultTopView *topView; // @synthesize topView=_topView;
- (void).cxx_destruct;
- (void)resetFrame:(struct CGRect)arg1;
- (double)toViewOrignY;
- (void)dealloc;
- (void)destory;
@property(readonly, nonatomic) _Bool isHidden;
- (void)configAutoHideTopView;
- (void)showTopView;
- (void)hideTopView;
- (void)closeBarrageState;
- (void)openBarragesState;
- (void)halfScreenState;
- (void)fullScreenState;
- (void)setTitle:(id)arg1;
- (void)addBarragesBack:(SEL)arg1 target:(id)arg2;
- (void)addBarragesAction:(SEL)arg1 target:(id)arg2;
- (void)addShareAction:(SEL)arg1 target:(id)arg2;
- (void)addBackAction:(SEL)arg1 target:(id)arg2;
- (id)initWithTopView:(id)arg1;

@end

