//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "KGMVMenuCellDelegate.h"
#import "KGMVTableViewAdapterOperateDelegate.h"
#import "KGMyFavorMVTableCellDelegate.h"
#import "KGRecentMVCellDelegate.h"
#import "RefreshControlDelegate.h"
#import "UITableViewDataSource.h"

@class KGRefreshController, KGTableView, NSArray, NSIndexPath, NSMutableArray, NSMutableDictionary, NSString, UILongPressGestureRecognizer, UIView;

@interface KGMVTableViewAdapter : NSObject <UITableViewDataSource, KGMyFavorMVTableCellDelegate, KGMVMenuCellDelegate, RefreshControlDelegate, KGRecentMVCellDelegate, KGMVTableViewAdapterOperateDelegate>
{
    _Bool _isLoading;
    _Bool _hasMore;
    _Bool _isMoved;
    long long _editTargetSecion;
    NSMutableArray *_dataSourceSelectedItems;
    NSMutableDictionary *_dataSourceSelectedItemsMap;
    _Bool _isCheckBoxStyle;
    _Bool _needPlayAnimation;
    KGTableView *_tableView;
    id <KGMVTableViewAdapterDataSource> _dataSource;
    NSIndexPath *_menuCellIndexPath;
    long long _menuCellMenuCount;
    unsigned long long _selectCount;
    id <KGMVTableViewAdapterDelegate> _delegate;
    NSString *_tabPath;
    UIView *_tableViewHeaderView;
    UIView *_tableViewFooterView;
    double _bottomExtendHeight;
    unsigned long long _sectionCount;
    NSMutableDictionary *_rowInfosDic;
    UILongPressGestureRecognizer *_longPress;
    NSArray *_menuArray;
    KGRefreshController *_refreshControl;
    id <KGMVTableViewControllerDelegate> _controlDelegate;
}

@property(nonatomic) __weak id <KGMVTableViewControllerDelegate> controlDelegate; // @synthesize controlDelegate=_controlDelegate;
@property(retain, nonatomic) KGRefreshController *refreshControl; // @synthesize refreshControl=_refreshControl;
@property(retain, nonatomic) NSArray *menuArray; // @synthesize menuArray=_menuArray;
@property(retain, nonatomic) UILongPressGestureRecognizer *longPress; // @synthesize longPress=_longPress;
@property(retain, nonatomic) NSMutableDictionary *rowInfosDic; // @synthesize rowInfosDic=_rowInfosDic;
@property(nonatomic) unsigned long long sectionCount; // @synthesize sectionCount=_sectionCount;
@property(nonatomic) double bottomExtendHeight; // @synthesize bottomExtendHeight=_bottomExtendHeight;
@property(retain, nonatomic) UIView *tableViewFooterView; // @synthesize tableViewFooterView=_tableViewFooterView;
@property(retain, nonatomic) UIView *tableViewHeaderView; // @synthesize tableViewHeaderView=_tableViewHeaderView;
@property(nonatomic) _Bool needPlayAnimation; // @synthesize needPlayAnimation=_needPlayAnimation;
@property(retain, nonatomic) NSString *tabPath; // @synthesize tabPath=_tabPath;
@property(nonatomic) __weak id <KGMVTableViewAdapterDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) unsigned long long selectCount; // @synthesize selectCount=_selectCount;
@property(nonatomic) _Bool isCheckBoxStyle; // @synthesize isCheckBoxStyle=_isCheckBoxStyle;
@property(readonly, nonatomic) long long menuCellMenuCount; // @synthesize menuCellMenuCount=_menuCellMenuCount;
@property(readonly, nonatomic) NSIndexPath *menuCellIndexPath; // @synthesize menuCellIndexPath=_menuCellIndexPath;
@property(nonatomic) __weak id <KGMVTableViewAdapterDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(readonly, nonatomic) KGTableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (void)p_refreshCacheIcon:(id)arg1;
- (void)p_removeDownloadNotify;
- (void)p_addDownloadNotify;
- (void)reload;
- (void)setEnableLongPressMode:(_Bool)arg1;
- (void)addSubViewToTableView:(id)arg1;
- (_Bool)tableViewIsCheckBoxStyle;
- (void)setTableViewIsCheckBoxStyle:(_Bool)arg1 sectionIndex:(unsigned long long)arg2;
- (void)setTableViewIsCheckBoxStyle:(_Bool)arg1;
- (void)refreshSelectedItems;
- (id)getAllItems;
- (_Bool)isSelectedItem:(id)arg1;
- (id)selectItems;
- (void)removeAllSelectItems;
- (_Bool)removeSelectItem:(id)arg1;
- (void)selectAllItems;
- (_Bool)addSelectItem:(id)arg1;
- (id)getTableView;
- (void)refreshControl:(id)arg1 didEngageRefreshDirection:(int)arg2;
- (void)menuClickWithMusicMenu:(id)arg1;
- (void)addMusicBtnActionWithMusicTableCell:(id)arg1 point:(struct CGPoint)arg2;
- (void)checkBoxActionWithMusicTableCell:(id)arg1;
- (void)menuActionWithMusicTableCell:(id)arg1;
- (_Bool)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 targetIndexPathForMoveFromRowAtIndexPath:(id)arg2 toProposedIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewWillBeginDecelerating:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidZoom:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)tableView:(id)arg1 moveRowAtIndexPath:(id)arg2 toIndexPath:(id)arg3;
- (_Bool)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)tableviewCellLongPressed:(id)arg1;
- (void)p_didFinishMusicControlCancelAction;
- (void)p_didFinishMusicControlEditAction;
- (void)p_refreshIndexPathsWithIndexPaths:(id)arg1 deleteRowsWithIndexPaths:(id)arg2;
- (id)p_songInfoUniqueTag:(id)arg1;
- (void)p_removeObjectWithDataSourceSelectedItemsMap:(id)arg1 songInfo:(id)arg2;
- (void)p_setObjectWithDataSourceSelectedItemsMap:(id)arg1 mvInfo:(id)arg2;
- (_Bool)p_selectItem:(id)arg1;
- (_Bool)p_isCheckBoxStyleInSeciton:(long long)arg1;
- (id)generateLocalBaseInfo:(id)arg1;
- (id)p_getSongInfoWithIndexPath:(id)arg1;
- (id)p_sortedSectionArray;
- (id)p_getAllSongInfoFormInfosDic;
- (void)p_dealWithMusicTableCell:(id)arg1 AndIndexPath:(id)arg2;
- (_Bool)p_removeToSelectWithItem:(id)arg1;
- (_Bool)p_insertToSelectWithItem:(id)arg1;
- (void)p_removeMusicMenuCellNotUpdatesWithCompletion:(CDUnknownBlockType)arg1;
- (void)p_removeMusicMenuCellNotUpdates;
- (void)p_removeMusicMenuCell;
- (void)p_insertMusicMenuCellWithIndexPath:(id)arg1 AndCell:(id)arg2;
- (void)p_insertMusicMenuCellWithMusicCell:(id)arg1;
- (_Bool)p_hasMore;
- (void)p_initTableviewWithFrame:(struct CGRect)arg1;
- (void)removeMusicMenuCell;
- (void)makeOnlyThisScrollViewScrollToTopOnStatusBarTap;
- (void)addTableViewToViewController:(id)arg1;
- (_Bool)isLoading;
- (void)loadingFinishAndRefresh;
- (void)combineAnimationForRowsAtInsertAtIndexPaths:(id)arg1 deleteRowsAtIndexPaths:(id)arg2 reloadRowsAtIndexPaths:(id)arg3 withRowAnimation:(long long)arg4;
- (void)deleteTableViewRowsAtIndexPaths:(id)arg1 withRowAnimation:(long long)arg2;
- (void)insertTableViewRowsAtIndexPaths:(id)arg1 withRowAnimation:(long long)arg2;
- (void)reloadTableViewRowsAtIndexPaths:(id)arg1 withRowAnimation:(long long)arg2;
- (void)reloadTableView;
- (void)setContentOffset:(struct CGPoint)arg1 animated:(_Bool)arg2;
- (void)setContentOffset:(struct CGPoint)arg1;
- (void)scrollToRowAtIndexPath:(id)arg1 atScrollPosition:(long long)arg2 animated:(_Bool)arg3;
- (struct CGRect)rectForSection:(long long)arg1;
- (void)addDataWithSctionIndex:(unsigned long long)arg1 rowData:(id)arg2 sectionCount:(unsigned long long)arg3;
- (void)updataWithSctionCount:(long long)arg1 rowInfosDic:(id)arg2;
- (void)addDataWithSctionIndex:(unsigned long long)arg1 rowData:(id)arg2;
- (void)updataRowInfosDic:(id)arg1;
@property(nonatomic) struct UIEdgeInsets tableViewContentInset;
@property(nonatomic) struct CGSize tableViewContentSize;
@property(nonatomic) struct CGPoint tableViewContentOffset;
@property(nonatomic, getter=isHidden) _Bool hidden;
- (void)setTableViewEdit:(_Bool)arg1;
- (id)getMenuIndexPath;
- (void)dealloc;
- (id)initWithTableViewFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

