//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "KGSongListDataSource.h"

@class NSArray, NSString;

@interface KGPlayListKugouMaDataSource : NSObject <KGSongListDataSource>
{
    NSArray *_songList;
    long long _userId;
    NSString *_userName;
    NSString *_pic;
    NSString *_title;
    id <KGSongListDelegate> _kugouMaDelegate;
}

@property(nonatomic) __weak id <KGSongListDelegate> kugouMaDelegate; // @synthesize kugouMaDelegate=_kugouMaDelegate;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *pic; // @synthesize pic=_pic;
@property(copy, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(nonatomic) long long userId; // @synthesize userId=_userId;
@property(retain, nonatomic) NSArray *songList; // @synthesize songList=_songList;
- (void).cxx_destruct;
- (void)delegate:(id)arg1;
- (void)startRequest;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

