//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MJRefreshAutoFooter.h"

@class KGThemeImageView, KGThemeLabel;

@interface KTVCommonTableFooterView : MJRefreshAutoFooter
{
    KGThemeLabel *_label;
    KGThemeImageView *_imageView;
}

@property(nonatomic) __weak KGThemeImageView *imageView; // @synthesize imageView=_imageView;
@property(nonatomic) __weak KGThemeLabel *label; // @synthesize label=_label;
- (void).cxx_destruct;
- (void)finishRefreshing;
- (void)startRefreshing;
- (void)setState:(int)arg1;
- (void)scrollViewPanStateDidChange:(id)arg1;
- (void)scrollViewContentSizeDidChange:(id)arg1;
- (void)scrollViewContentOffsetDidChange:(id)arg1;
- (void)placeSubviews;
- (void)prepare;

@end

