//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "KTVBaseViewController.h"

@class NSString, UIColor, UIImage, UIScrollView;

@interface KTVCompetitionResultShareViewController : KTVBaseViewController
{
    long long shareType;
    _Bool _isJudge;
    UIImage *_shareImage;
    UIImage *_wechatShareImage;
    NSString *_url;
    NSString *_songName;
    NSString *_madelStr;
    CDUnknownBlockType _dismissBlock;
    UIColor *_bgColor;
    UIColor *_textColor;
    UIScrollView *_scrollView;
}

@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) _Bool isJudge; // @synthesize isJudge=_isJudge;
@property(retain, nonatomic) UIColor *textColor; // @synthesize textColor=_textColor;
@property(retain, nonatomic) UIColor *bgColor; // @synthesize bgColor=_bgColor;
@property(copy, nonatomic) CDUnknownBlockType dismissBlock; // @synthesize dismissBlock=_dismissBlock;
@property(retain, nonatomic) NSString *madelStr; // @synthesize madelStr=_madelStr;
@property(retain, nonatomic) NSString *songName; // @synthesize songName=_songName;
@property(retain, nonatomic) NSString *url; // @synthesize url=_url;
@property(retain, nonatomic) UIImage *wechatShareImage; // @synthesize wechatShareImage=_wechatShareImage;
@property(retain, nonatomic) UIImage *shareImage; // @synthesize shareImage=_shareImage;
- (void).cxx_destruct;
- (void)callComplete:(id)arg1;
- (void)shareButtonClick:(id)arg1;
- (void)backEvent:(id)arg1;
- (long long)showPlayBarWay;
- (void)longPressAction;
- (void)viewDidLoad;
- (void)KGUsingControllerState:(int)arg1;
- (id)init;

@end

