//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSMutableArray, NSMutableDictionary;

@interface KTVGiftBarrageShow : UIView
{
    long long giftBarrageIndex;
    NSMutableArray *willShowGiftIndex;
    NSMutableDictionary *giftBarrageRoadIsFree;
    _Bool _playerIsPlaying;
    NSMutableArray *_giftArray;
}

@property(retain, nonatomic) NSMutableArray *giftArray; // @synthesize giftArray=_giftArray;
@property(nonatomic) _Bool playerIsPlaying; // @synthesize playerIsPlaying=_playerIsPlaying;
- (void).cxx_destruct;
- (void)addGiftBarrage:(id)arg1;
- (void)showGiftBarrage:(id)arg1 onRoad:(id)arg2;
- (void)seekToGiftBarrage:(float)arg1;
- (void)continueGiftBarrage;
- (void)beginGiftBarrage;
- (void)managerRoad:(id)arg1;

@end

