//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "KTVViewController.h"

#import "UIAlertViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class KGDefaultNetErrorView, KTVEmptyView, KTVInviKSongShakeHistoryViewModel, NSString, UITableView;

@interface KTVInviKSongShakeHistoryViewController : KTVViewController <UITableViewDataSource, UITableViewDelegate, UIAlertViewDelegate>
{
    _Bool _didFirstReq;
    KTVEmptyView *_historyEmptyView;
    KGDefaultNetErrorView *_netErrorView;
    UITableView *_shakeHistoryTableView;
    KTVInviKSongShakeHistoryViewModel *_shakeHistoryVM;
}

@property(retain, nonatomic) KTVInviKSongShakeHistoryViewModel *shakeHistoryVM; // @synthesize shakeHistoryVM=_shakeHistoryVM;
@property(retain, nonatomic) UITableView *shakeHistoryTableView; // @synthesize shakeHistoryTableView=_shakeHistoryTableView;
- (void).cxx_destruct;
- (void)KGUsingControllerState:(int)arg1;
- (long long)showPlayBarWay;
- (void)clickedNetErrorBtnAction:(id)arg1;
- (void)clearBtnDidClicked_TouchUpInside:(id)arg1;
- (void)netErrorViewPresentionForShow:(_Bool)arg1;
- (void)historyEmptyViewPresentionForShow:(_Bool)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)clearShakeHistoryList;
- (void)reqShakeHistoryList;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

