//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class KTVKSongInviGiftsCell;

@protocol KTVKSongInviGiftsCellDelegate <NSObject>

@optional
- (void)inviGiftsCell:(KTVKSongInviGiftsCell *)arg1 didSelectGift:(int)arg2 coupon:(int)arg3;
- (void)inviGiftsCell:(KTVKSongInviGiftsCell *)arg1 didChangeHeight:(double)arg2;
@end

