//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class KTVLocalOpusVLL, KTV_LocalWorksInfo, KTV_SongInfo, KTV_SoundInfo;

@protocol KTVLocalOpusVLLDelegate <NSObject>
- (void)goSingSong;
- (void)deletedHasRefresh;
- (void)localOpusVLL:(KTVLocalOpusVLL *)arg1 toTouneWithOpus:(KTV_LocalWorksInfo *)arg2;
- (void)localOpusVLL:(KTVLocalOpusVLL *)arg1 opusNotFind:(KTV_LocalWorksInfo *)arg2;
- (void)localOpusVLL:(KTVLocalOpusVLL *)arg1 upLoadToKugouWithOpus:(KTV_LocalWorksInfo *)arg2;
- (void)localOpusVLL:(KTVLocalOpusVLL *)arg1 toShareWithOpus:(KTV_LocalWorksInfo *)arg2;
- (void)localOpusVLL:(KTVLocalOpusVLL *)arg1 toRecordWithAccompany:(KTV_SongInfo *)arg2 isChorus:(_Bool)arg3 soundInfo:(KTV_SoundInfo *)arg4 inviteId:(long long)arg5 isFragmentWork:(_Bool)arg6 fragmentStartTime:(long long)arg7 fragmentEndTime:(long long)arg8;
@end

