//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "KFCommedTableViewCell.h"

@class KFUserAvatar, KGThemeImageView, KGThemeLabel, UIImageView, UIView;

@interface KTVSingleSongDetailCell : KFCommedTableViewCell
{
    int _playerId;
    KGThemeLabel *_rankLabel;
    UIImageView *_rankImg;
    UIImageView *_headBgImg;
    KFUserAvatar *_head;
    KGThemeLabel *_nameLabel;
    UIImageView *_sexImg;
    UIImageView *_userAuthCategoryImg;
    KGThemeImageView *_playicon;
    KGThemeLabel *_playlab;
    UIView *_gapLine;
    UIImageView *_inviteImg;
}

@property(retain, nonatomic) UIImageView *inviteImg; // @synthesize inviteImg=_inviteImg;
@property(retain, nonatomic) UIView *gapLine; // @synthesize gapLine=_gapLine;
@property(retain, nonatomic) KGThemeLabel *playlab; // @synthesize playlab=_playlab;
@property(retain, nonatomic) KGThemeImageView *playicon; // @synthesize playicon=_playicon;
@property(retain, nonatomic) UIImageView *userAuthCategoryImg; // @synthesize userAuthCategoryImg=_userAuthCategoryImg;
@property(retain, nonatomic) UIImageView *sexImg; // @synthesize sexImg=_sexImg;
@property(retain, nonatomic) KGThemeLabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) KFUserAvatar *head; // @synthesize head=_head;
@property(retain, nonatomic) UIImageView *headBgImg; // @synthesize headBgImg=_headBgImg;
@property(retain, nonatomic) UIImageView *rankImg; // @synthesize rankImg=_rankImg;
@property(retain, nonatomic) KGThemeLabel *rankLabel; // @synthesize rankLabel=_rankLabel;
@property(nonatomic) int playerId; // @synthesize playerId=_playerId;
- (void).cxx_destruct;
- (void)configOpusSingleAccView;
- (void)goToUserSpase;
- (void)updateCellWithData:(id)arg1 index:(long long)arg2;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

