//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "KFViewModelObject.h"

@class NSArray, NSDictionary;

@interface KTVShareToChatVM : KFViewModelObject
{
    _Bool _isFresh;
    int _pageNo;
    int _pageSize;
    NSDictionary *_data;
    NSArray *_titles;
}

@property(nonatomic) int pageSize; // @synthesize pageSize=_pageSize;
@property(nonatomic) int pageNo; // @synthesize pageNo=_pageNo;
@property(retain, nonatomic) NSArray *titles; // @synthesize titles=_titles;
@property(retain, nonatomic) NSDictionary *data; // @synthesize data=_data;
@property(nonatomic) _Bool isFresh; // @synthesize isFresh=_isFresh;
- (void).cxx_destruct;
- (void)handleUpdateSuccess:(id)arg1;
- (void)update;
- (id)init;

@end

