//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "KFCommedTableViewCell.h"

@class KTVIconLabel, KTVUserAchievement, UIButton, UILabel, UIView;

@interface KTVUserAchievementCell : KFCommedTableViewCell
{
    KTVIconLabel *_firstIconLabel;
    KTVIconLabel *_secondIconLabel;
    KTVIconLabel *_thirdIconLabel;
    KTVIconLabel *_fourIconLabel;
    UILabel *_headerLabel;
    UIButton *_detailButton;
    UIView *_mainView;
    UIButton *_button;
    KTVUserAchievement *_userAchievement;
    id <KTVUserAchievementCellDelegate> _delegate;
    long long _achievementType;
    double _adaptScale;
}

@property(nonatomic) double adaptScale; // @synthesize adaptScale=_adaptScale;
@property(nonatomic) long long achievementType; // @synthesize achievementType=_achievementType;
@property(nonatomic) __weak id <KTVUserAchievementCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) KTVUserAchievement *userAchievement; // @synthesize userAchievement=_userAchievement;
- (void).cxx_destruct;
- (void)clickToDetail:(id)arg1;
- (void)clickToTips:(id)arg1;
- (id)configIconViewWithView:(id)arg1 imageName:(id)arg2 iconY:(double)arg3 iconWidth:(double)arg4 iconHeight:(double)arg5 left:(double)arg6;
- (void)configIconWithAchievementType:(long long)arg1;
- (void)removeIconView;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)dealloc;

@end

