//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MessageCenterPlistDao.h"

@interface MessageCenterRedPointTypePlistDao : MessageCenterPlistDao
{
}

- (_Bool)messageCenterRedPointTypeHidden:(id)arg1;
- (_Bool)setMessageCenterRedPointType:(id)arg1 shouldHidden:(_Bool)arg2;
- (id)redPointTypeHiddenInfo;
- (id)messageCenterRedPointTypePlistPath;

@end

