//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MTNotificationProtocol.h"

@class NSString;

@interface MTNotificationProvider : NSObject <MTNotificationProtocol>
{
}

- (void)mobileLiveSendPlayMsg;
- (void)updateRegisterInfo;
- (void)getAllAliasAsync;
- (void)getAllTopicAsync;
- (void)unsubscribePush:(id)arg1;
- (void)subscribePush:(id)arg1;
- (id)notificationNameForKey:(id)arg1;
- (void)removeObserver:(id)arg1 name:(id)arg2 object:(id)arg3;
- (void)removeObserver:(id)arg1;
- (void)postNotificationName:(id)arg1 object:(id)arg2 userInfo:(id)arg3;
- (void)addObserver:(id)arg1 selector:(SEL)arg2 name:(id)arg3 object:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

