//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MVHttpDao : NSObject
{
    _Bool _askOnlyWifi;
}

+ (id)sharedInstance;
@property(nonatomic) _Bool askOnlyWifi; // @synthesize askOnlyWifi=_askOnlyWifi;
- (id)getMVMultiQualityInfoWithSongHash:(id)arg1 error:(id *)arg2;
- (id)getMVMultiQualityInfoWithMVID:(id)arg1 MVHash:(id)arg2 MVFileName:(id)arg3 andShowTag:(_Bool)arg4 error:(id *)arg5;
- (id)requestMVSingerDetailWithMVHash:(id)arg1 WithError:(id *)arg2;
- (void)requestRcmMVCheckAPI:(CDUnknownBlockType)arg1 fail:(CDUnknownBlockType)arg2;
- (long long)networkType;
- (_Bool)isNetPack;
- (id)buildGetMvAdInfoRequestString:(id)arg1 mvSinger:(id)arg2;
- (void)getMvAdInfoAPI:(id)arg1 mvSinger:(id)arg2 andMVHash:(id)arg3 success:(CDUnknownBlockType)arg4 fail:(CDUnknownBlockType)arg5;
- (id)clientTimeString;
- (id)getRelatedMVByVideoID:(int)arg1 videoHash:(id)arg2 error:(id *)arg3;
- (void)getMvDanDetailByVid:(id)arg1 success:(CDUnknownBlockType)arg2 fail:(CDUnknownBlockType)arg3;
- (void)getMvDanListByBean:(id)arg1 success:(CDUnknownBlockType)arg2 fail:(CDUnknownBlockType)arg3;
- (void)getMvNewListWithBean:(id)arg1 success:(CDUnknownBlockType)arg2 fail:(CDUnknownBlockType)arg3;
- (void)getMvRecommendSuccess:(CDUnknownBlockType)arg1 fail:(CDUnknownBlockType)arg2;
- (void)getmvMultBannerSuccess:(CDUnknownBlockType)arg1 fail:(CDUnknownBlockType)arg2;
- (void)getMvBannerSuccess:(CDUnknownBlockType)arg1 fail:(CDUnknownBlockType)arg2;
- (void)getMvListOfTag:(id)arg1 success:(CDUnknownBlockType)arg2 fail:(CDUnknownBlockType)arg3;
- (void)getMvTagsSuccess:(CDUnknownBlockType)arg1 fail:(CDUnknownBlockType)arg2;
- (void)getMvHotWordSuccess:(CDUnknownBlockType)arg1 fail:(CDUnknownBlockType)arg2;
- (id)init;

@end

