//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AlbumItem, MVSpecialBean, NSString, NetListTagInfo, RadioInfo, RankingItem, RecommendSong, SingerInfo, SpecialItem;

@interface OperateEntry : NSObject
{
    int _type;
    NSString *_imgurl;
    NSString *_title;
    NSString *_descriptionTitle;
    SpecialItem *_special;
    AlbumItem *_album;
    RankingItem *_rank;
    NSString *_innerurl;
    NSString *_innerurlTitle;
    RadioInfo *_radio;
    NSString *_mvHash;
    RecommendSong *_songInfo;
    MVSpecialBean *_mvSpecialBean;
    SingerInfo *_singerInfo;
    NetListTagInfo *_classifiedTagInfo;
}

@property(retain, nonatomic) NetListTagInfo *classifiedTagInfo; // @synthesize classifiedTagInfo=_classifiedTagInfo;
@property(retain, nonatomic) SingerInfo *singerInfo; // @synthesize singerInfo=_singerInfo;
@property(retain, nonatomic) MVSpecialBean *mvSpecialBean; // @synthesize mvSpecialBean=_mvSpecialBean;
@property(retain, nonatomic) RecommendSong *songInfo; // @synthesize songInfo=_songInfo;
@property(copy, nonatomic) NSString *mvHash; // @synthesize mvHash=_mvHash;
@property(retain, nonatomic) RadioInfo *radio; // @synthesize radio=_radio;
@property(copy, nonatomic) NSString *innerurlTitle; // @synthesize innerurlTitle=_innerurlTitle;
@property(copy, nonatomic) NSString *innerurl; // @synthesize innerurl=_innerurl;
@property(retain, nonatomic) RankingItem *rank; // @synthesize rank=_rank;
@property(retain, nonatomic) AlbumItem *album; // @synthesize album=_album;
@property(retain, nonatomic) SpecialItem *special; // @synthesize special=_special;
@property(nonatomic) int type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *descriptionTitle; // @synthesize descriptionTitle=_descriptionTitle;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *imgurl; // @synthesize imgurl=_imgurl;
- (void).cxx_destruct;

@end

