//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PlayViewComercialDBDAO : NSObject
{
}

+ (_Bool)deleteComercialInfoWithSingerId:(id)arg1 andAlbumId:(int)arg2 andHash:(id)arg3;
+ (_Bool)deleteComercialInfo:(long long)arg1;
+ (_Bool)selectOneComercialInfoDisplayTimes:(id)arg1;
+ (id)selectAllComercialInfo;
+ (id)selectComercialInfoBySingerId:(id)arg1 andAlbumId:(int)arg2 andHash:(id)arg3;
+ (_Bool)updateComercialInfoDisplayTimes:(int)arg1 withComercialInfo:(id)arg2;
+ (_Bool)updateComercialDisplayTimes:(id)arg1;
+ (_Bool)updateComercialInfo:(id)arg1;
+ (_Bool)addComercialDisplayTimes:(id)arg1;
+ (_Bool)addComercialInfo:(id)arg1;

@end

