//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionReusableView.h"

@class KGThemeLabel, NSString;

@interface SpecialZoneSectionHeaderView : UICollectionReusableView
{
    KGThemeLabel *_keyLabel;
    NSString *_tagName;
}

@property(copy, nonatomic) NSString *tagName; // @synthesize tagName=_tagName;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;

@end

