//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UGCBaseHistoryInfo.h"

@class NSArray, NSString;

@interface UGCCollectHistoryInfo : UGCBaseHistoryInfo
{
    long long _songlist_id;
    long long _kg_id;
    NSString *_songlist_name;
    NSString *_songlist_img;
    NSArray *_songlist_tag;
    long long _audio_count;
    long long _end;
}

@property(nonatomic) long long end; // @synthesize end=_end;
@property(nonatomic) long long audio_count; // @synthesize audio_count=_audio_count;
@property(retain, nonatomic) NSArray *songlist_tag; // @synthesize songlist_tag=_songlist_tag;
@property(retain, nonatomic) NSString *songlist_img; // @synthesize songlist_img=_songlist_img;
@property(retain, nonatomic) NSString *songlist_name; // @synthesize songlist_name=_songlist_name;
@property(nonatomic) long long kg_id; // @synthesize kg_id=_kg_id;
@property(nonatomic) long long songlist_id; // @synthesize songlist_id=_songlist_id;
- (void).cxx_destruct;

@end

