//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (i7Rotate360)
- (void)changeImage;
- (void)animationDidStart:(id)arg1;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)rotate360WithDuration:(double)arg1;
- (void)rotate360WithDuration:(double)arg1 timingMode:(int)arg2;
- (void)rotate360WithDuration:(double)arg1 repeatCount:(double)arg2 timingMode:(int)arg3;
@end

