//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class Address, RspMsg;

@interface ConnMasterGetRouteRsp : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) Address *connSvr; // @dynamic connSvr;
@property(nonatomic) _Bool hasConnSvr; // @dynamic hasConnSvr;
@property(nonatomic) _Bool hasRspMsg; // @dynamic hasRspMsg;
@property(retain, nonatomic) RspMsg *rspMsg; // @dynamic rspMsg;

@end

