//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface DCHomeMoreDriverModel : NSObject
{
    _Bool _isTemp;
    NSString *_order_id;
    NSString *_order_new_status;
    NSString *_route_id;
    NSDictionary *_routeParam;
}

@property(nonatomic) _Bool isTemp; // @synthesize isTemp=_isTemp;
@property(retain, nonatomic) NSDictionary *routeParam; // @synthesize routeParam=_routeParam;
@property(copy, nonatomic) NSString *route_id; // @synthesize route_id=_route_id;
@property(copy, nonatomic) NSString *order_new_status; // @synthesize order_new_status=_order_new_status;
@property(copy, nonatomic) NSString *order_id; // @synthesize order_id=_order_id;
- (void).cxx_destruct;

@end

