//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JSONModel.h"

@class DBAlertModel<Optional>, DCNoteInfoModel<Optional>, DCRouteOrderAutoMatchCloseInfoModel<Optional>, NSArray<Optional>, NSNumber<Optional>, NSString<Optional>;

@interface DCRouteOrderAutoMatchModel : JSONModel
{
    DCRouteOrderAutoMatchCloseInfoModel<Optional> *_close_alert_info;
    NSArray<Optional> *_open_desc_richtext;
    NSNumber<Optional> *_has_open;
    NSNumber<Optional> *_can_open;
    DBAlertModel<Optional> *_alert_info;
    NSString<Optional> *_title;
    NSString<Optional> *_desc;
    NSString<Optional> *_icon_url;
    NSString<Optional> *_h5_url;
    DCNoteInfoModel<Optional> *_rich_title;
}

@property(copy, nonatomic) DCNoteInfoModel<Optional> *rich_title; // @synthesize rich_title=_rich_title;
@property(copy, nonatomic) NSString<Optional> *h5_url; // @synthesize h5_url=_h5_url;
@property(copy, nonatomic) NSString<Optional> *icon_url; // @synthesize icon_url=_icon_url;
@property(copy, nonatomic) NSString<Optional> *desc; // @synthesize desc=_desc;
@property(copy, nonatomic) NSString<Optional> *title; // @synthesize title=_title;
@property(copy, nonatomic) DBAlertModel<Optional> *alert_info; // @synthesize alert_info=_alert_info;
@property(retain, nonatomic) NSNumber<Optional> *can_open; // @synthesize can_open=_can_open;
@property(retain, nonatomic) NSNumber<Optional> *has_open; // @synthesize has_open=_has_open;
@property(copy, nonatomic) NSArray<Optional> *open_desc_richtext; // @synthesize open_desc_richtext=_open_desc_richtext;
@property(copy, nonatomic) DCRouteOrderAutoMatchCloseInfoModel<Optional> *close_alert_info; // @synthesize close_alert_info=_close_alert_info;
- (void).cxx_destruct;
- (id)JSONObjectForOpen_desc_richtext;
- (void)setOpen_desc_richtextWithNSArray:(id)arg1;

@end

