//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class DDIMEmojiModel, UIActivityIndicatorView, UIImageView, UILabel;

@interface DDIMPhizInputViewCell : UICollectionViewCell
{
    UIImageView *_phizImage;
    UILabel *_phizName;
    DDIMEmojiModel *_phizInfo;
    UIActivityIndicatorView *_indicatorView;
}

@property(retain, nonatomic) UIActivityIndicatorView *indicatorView; // @synthesize indicatorView=_indicatorView;
@property(retain, nonatomic) DDIMEmojiModel *phizInfo; // @synthesize phizInfo=_phizInfo;
@property(retain, nonatomic) UILabel *phizName; // @synthesize phizName=_phizName;
@property(retain, nonatomic) UIImageView *phizImage; // @synthesize phizImage=_phizImage;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

