//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DDIMMessageInputView, NSArray, NSString;

@protocol DDIMMessageInputViewDelegate <NSObject>

@optional
- (NSArray *)locationList;
- (void)didPressMoreButton;
- (void)customActionClicked:(NSString *)arg1;
- (void)messageInputViewDidFailedRecording;
- (void)messageInputViewDidFinishWithRecordTime:(double)arg1 voicePath:(NSString *)arg2;
- (void)messageInputViewDidCancelRecording;
- (void)messageInputViewDidBeginRecording;
- (void)messageInputViewWillBeginRecording;
- (void)messageInputViewDidSwitchInput:(long long)arg1;
- (void)messageInputViewDidSendMessage:(NSString *)arg1;
- (void)messageInputViewHeightDidChange:(DDIMMessageInputView *)arg1;
- (void)messageInputViewTextViewDidChange:(DDIMMessageInputView *)arg1;
@end

