//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DGCBaseModel.h"

@class NSArray<DGCBannerModel>, NSString;

@interface DGCBannerQueryModel : DGCBaseModel
{
    NSArray<DGCBannerModel> *_banner;
    NSString *_flag;
}

@property(retain, nonatomic) NSString *flag; // @synthesize flag=_flag;
@property(retain, nonatomic) NSArray<DGCBannerModel> *banner; // @synthesize banner=_banner;
- (void).cxx_destruct;

@end

