//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DGCBaseWebViewController.h"

@class NSString;

@interface DGPBaseWebViewController : DGCBaseWebViewController
{
    NSString *_fromPagestr;
}

@property(retain, nonatomic) NSString *fromPagestr; // @synthesize fromPagestr=_fromPagestr;
- (void).cxx_destruct;
- (void)viewDidLoad;
- (void)trWebViewWillGoBack:(id)arg1;

@end

