//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData;

@interface DIDIVRPostData : NSObject
{
    int idx;
    NSData *_audioData;
}

@property(retain, nonatomic) NSData *audioData; // @synthesize audioData=_audioData;
@property(nonatomic) int idx; // @synthesize idx;
- (void).cxx_destruct;
- (id)init;

@end

