//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DiMConnectionItemDelegate.h"

@class DMMapView, DiOrderExtraInfo, DiRouteGuidanceResult, NSArray, NSMutableArray, NSString, NSTimer;

@interface DiRouteNavigationDataManager : NSObject <DiMConnectionItemDelegate>
{
    _Bool _patternHasReTry;
    _Bool _arrowHasReTry;
    _Bool _isNavigating;
    _Bool _canUpdateLocation;
    _Bool _isReCalculating;
    _Bool _shouldShowGoOnAlertView;
    _Bool _needsPlayTTs;
    _Bool _forceStopVoice;
    _Bool _needsEnterBackgroundVoice;
    _Bool _isLightNavigating;
    _Bool _isSameDispNaving;
    _Bool _isConsistencyRecing;
    int _timerCounter;
    int _gpsPointsCount;
    int _locationCounter;
    int _backgroundMode;
    int _routeColor;
    int _nextEventSegmentIndex;
    int _gpsNo;
    void *_rgHandle;
    struct __sFILE *_fpTrack;
    id <RouteNavigationDelegate> _delegate;
    DiRouteGuidanceResult *_result;
    NSArray *_lineArray;
    NSArray *_trafficTimesArray;
    long long _remainTime;
    long long _currSegmentIndex;
    NSString *_trafficRadioRouteID;
    NSMutableArray *_gpsDataArray;
    NSArray *_drawLineEventsArray;
    struct __sFILE *_recordFile;
    DMMapView *_mapView;
    DiOrderExtraInfo *_orderExtraInfo;
    NSString *_curRouteID;
    long long _lineWidth;
    _RouteGuidanceGPSPoint_e0d7dc1f _lastMatchedPoint;
    _RouteGuidanceGPSPoint_e0d7dc1f _m_gpsPoint;
}

@property(nonatomic) _RouteGuidanceGPSPoint_5bddcbd0 m_gpsPoint; // @synthesize m_gpsPoint=_m_gpsPoint;
@property(nonatomic) _RouteGuidanceGPSPoint_5bddcbd0 lastMatchedPoint; // @synthesize lastMatchedPoint=_lastMatchedPoint;
@property(nonatomic) _Bool isConsistencyRecing; // @synthesize isConsistencyRecing=_isConsistencyRecing;
@property(nonatomic) _Bool isSameDispNaving; // @synthesize isSameDispNaving=_isSameDispNaving;
@property(nonatomic) _Bool isLightNavigating; // @synthesize isLightNavigating=_isLightNavigating;
@property(nonatomic) long long lineWidth; // @synthesize lineWidth=_lineWidth;
@property(retain, nonatomic) NSString *curRouteID; // @synthesize curRouteID=_curRouteID;
@property(retain, nonatomic) DiOrderExtraInfo *orderExtraInfo; // @synthesize orderExtraInfo=_orderExtraInfo;
@property(nonatomic) __weak DMMapView *mapView; // @synthesize mapView=_mapView;
@property(nonatomic) struct __sFILE *recordFile; // @synthesize recordFile=_recordFile;
@property(retain, nonatomic) NSArray *drawLineEventsArray; // @synthesize drawLineEventsArray=_drawLineEventsArray;
@property(nonatomic) int gpsNo; // @synthesize gpsNo=_gpsNo;
@property(retain, nonatomic) NSMutableArray *gpsDataArray; // @synthesize gpsDataArray=_gpsDataArray;
@property(retain, nonatomic) NSString *trafficRadioRouteID; // @synthesize trafficRadioRouteID=_trafficRadioRouteID;
@property(nonatomic) long long currSegmentIndex; // @synthesize currSegmentIndex=_currSegmentIndex;
@property(nonatomic) long long remainTime; // @synthesize remainTime=_remainTime;
@property(retain, nonatomic) NSArray *trafficTimesArray; // @synthesize trafficTimesArray=_trafficTimesArray;
@property(nonatomic) int nextEventSegmentIndex; // @synthesize nextEventSegmentIndex=_nextEventSegmentIndex;
@property(nonatomic) int routeColor; // @synthesize routeColor=_routeColor;
@property(retain, nonatomic) NSArray *lineArray; // @synthesize lineArray=_lineArray;
@property(retain, nonatomic) DiRouteGuidanceResult *result; // @synthesize result=_result;
@property(nonatomic) int backgroundMode; // @synthesize backgroundMode=_backgroundMode;
@property(nonatomic) _Bool needsEnterBackgroundVoice; // @synthesize needsEnterBackgroundVoice=_needsEnterBackgroundVoice;
@property(nonatomic) _Bool forceStopVoice; // @synthesize forceStopVoice=_forceStopVoice;
@property(nonatomic) _Bool needsPlayTTs; // @synthesize needsPlayTTs=_needsPlayTTs;
@property(nonatomic) _Bool shouldShowGoOnAlertView; // @synthesize shouldShowGoOnAlertView=_shouldShowGoOnAlertView;
@property(nonatomic) _Bool isReCalculating; // @synthesize isReCalculating=_isReCalculating;
@property(nonatomic) _Bool canUpdateLocation; // @synthesize canUpdateLocation=_canUpdateLocation;
@property(nonatomic) int locationCounter; // @synthesize locationCounter=_locationCounter;
@property(nonatomic) __weak id <RouteNavigationDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool isNavigating; // @synthesize isNavigating=_isNavigating;
@property(nonatomic) struct __sFILE *fpTrack; // @synthesize fpTrack=_fpTrack;
@property(nonatomic) int gpsPointsCount; // @synthesize gpsPointsCount=_gpsPointsCount;
@property(nonatomic) int timerCounter; // @synthesize timerCounter=_timerCounter;
@property(nonatomic) void *rgHandle; // @synthesize rgHandle=_rgHandle;
- (void).cxx_destruct;
- (void)handleConsistencyNavigationFail:(id)arg1;
- (void)handleConsistencyNavigationRouteUpdate:(id)arg1;
- (void)handleNavigationRouteUpdate:(id)arg1;
- (void)handleSameDispChangeNavigationState:(id)arg1;
- (long long)getOnlineTime:(struct _RouteGuidanceGPSPoint *)arg1 nextSegmentDistance:(int)arg2;
- (long long)getRealSegmentIndex:(long long)arg1;
- (void)checkUpdateRoute;
- (_Bool)needsShowDisclaimer;
- (void)sendArrowImageRequest;
- (void)sendPatternImageRequest;
- (void)downloadEnlargementImage;
- (void)clearRoute;
- (void)showRoute:(id)arg1 lineArray:(id)arg2;
- (void)showRoute:(id)arg1 routeColor:(int)arg2;
- (_Bool)writeLocation:(id)arg1 lon:(double *)arg2 lat:(double *)arg3 course:(double *)arg4;
- (void)updateNavigationUIWithOutLocation;
- (void)updateNavigationUIWithLocation:(id)arg1;
- (void)setTrafficStatus:(struct _RouteGuidanceTrafficStatus *)arg1 count:(int)arg2;
- (void)connectionItem:(id)arg1 didFailWithError:(id)arg2;
- (void)connectionItemDidFinish:(id)arg1;
- (void)recalculateRouteDidFailWithErrorFinally:(id)arg1;
- (void)recalculateRouteDidFailWithError:(id)arg1;
- (void)recalculateRouteDidFinishWithResult:(id)arg1;
- (void)stopLightNavigation;
- (void)startLightNavigationWithDelegate:(id)arg1;
- (id)getRouteLineInfo;
- (void)startNavigationWithJson_WithoutLocation:(id)arg1;
- (_Bool)createNavigationWithJson_WithoutLocation:(id)arg1;
- (void)startNavigationWithJson_WithoutLocation:(id)arg1 routeColor:(int)arg2;
- (void)startNavigationWithJson:(id)arg1;
- (void)updatePianhangRoute:(id)arg1;
- (void)setMapPointToEngine:(id)arg1;
- (void)createfpTrack;
- (id)condParameter;
- (void)stopTTS;
- (void)cancel;
- (void)ConsistencyRecalculate;
- (void)reCalculate;
- (id)reCalculate:(_Bool)arg1;
- (void)calculate;
- (id)calculate:(_Bool)arg1;
- (void)stop;
- (void)startWithoutLocation:(int)arg1;
- (void)start;
- (_Bool)isValidStartEnd;
- (void)loadFromDictionary:(id)arg1;
- (void)saveToDictionary:(id)arg1;
- (void)dealloc;
- (id)initWithMapView:(id)arg1;
- (id)init;
- (void)recordRainbowUpdateError:(int)arg1;
- (id)dictForJSON:(id)arg1;
- (void)handlePassengerRainbowRoute:(id)arg1 points:(id)arg2 type:(int)arg3;
- (void)handleOriginalRoute:(id)arg1;
- (void)handleRainbowRoute:(id)arg1;
- (id)routeSearchDataManagerSelectedRouteId;
- (int)updateThroughedIndex:(int)arg1;
- (void)recordResultReport;
- (void)stopLogging;
- (void)startLogging;
- (void)refreshRouteOverlay:(id)arg1;
- (void)refreshRouteOverlayWithEvents:(id)arg1 andRoutePoints:(id)arg2 andRouteType:(int)arg3;
- (_Bool)isValidTraffic:(id)arg1;
- (void)setTrafficStatus:(id)arg1;
- (void)handleTimerFired:(id)arg1;
- (void)stopDynamicRoute;
- (void)startDynamicRoute;
@property(retain, nonatomic) NSTimer *timer;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

