//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ONEIMViewManager : NSObject
{
}

+ (id)promotionHttpToHttps:(id)arg1;
+ (void)openPageWithURL:(id)arg1;
+ (void)popAndPushViewControllerWithPopVC:(id)arg1 pushVC:(id)arg2 animated:(_Bool)arg3;
+ (void)popViewController:(id)arg1 animated:(_Bool)arg2;
+ (void)popViewControllerAnimated:(_Bool)arg1;
+ (id)sharedInstance;
- (id)topViewController;
- (id)rootViewControllers;
- (id)rootNavigationController;
- (void)popAllIMViewController;
- (void)switchToIMMessageViewController:(id)arg1 animated:(_Bool)arg2;
- (void)switchToIMViewController:(id)arg1 animated:(_Bool)arg2;

@end

