//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UITextViewDelegate.h"

@class NSString, UILabel, UITextView;

@interface ONEReportTextView : UIView <UITextViewDelegate>
{
    UITextView *_textView;
    UILabel *_countLabel;
    UILabel *_placeHolderLabel;
    CDUnknownBlockType _textLengthBlock;
    long long _textStyle;
}

@property(nonatomic) long long textStyle; // @synthesize textStyle=_textStyle;
@property(copy, nonatomic) CDUnknownBlockType textLengthBlock; // @synthesize textLengthBlock=_textLengthBlock;
@property(retain, nonatomic) UILabel *placeHolderLabel; // @synthesize placeHolderLabel=_placeHolderLabel;
@property(retain, nonatomic) UILabel *countLabel; // @synthesize countLabel=_countLabel;
@property(retain, nonatomic) UITextView *textView; // @synthesize textView=_textView;
- (void).cxx_destruct;
- (void)keyboardWillHideNotification:(id)arg1;
- (void)textViewEditChanged:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)resignResponder;
- (void)becomResponder;
- (id)inputedTextString;
- (void)setUpSubViews:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 placeHolderStr:(id)arg2 textLengthBlock:(CDUnknownBlockType)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

