//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SDDJEvaluationModuleLogic : NSObject
{
}

- (void)evaluateDriveByStar:(id)arg1 andOrderId:(id)arg2 andLatitude:(id)arg3 andLongitude:(id)arg4 andTags:(id)arg5 andDescTxt:(id)arg6 succeed:(CDUnknownBlockType)arg7 failure:(CDUnknownBlockType)arg8;
- (void)queryTagsByCityId:(id)arg1 driverID:(long long)arg2 schemeType:(long long)arg3 succeed:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (void)queryCommentByPID:(long long)arg1 orderID:(long long)arg2 succeed:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;

@end

