//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SSCarBizDataSource.h"

#import "SBulletinBoardsDataSource.h"
#import "SCancelComDataSource.h"
#import "SCarPoolDataSourceProtocol.h"
#import "SCreateOrderDataSourceProtocol.h"
#import "SDynamicPriceDataSourceProtocol.h"
#import "SEstimateComDataSource.h"
#import "SPickLikeWaitComDataSource.h"
#import "SPopupDataSourceProtocol.h"
#import "SSCarBizDataSourceProtocal.h"

@class NSMutableDictionary, NSNumber, NSString, TRStationInfoModel;

@interface SFastBizDataSource : SSCarBizDataSource <SCancelComDataSource, SCarPoolDataSourceProtocol, SCreateOrderDataSourceProtocol, SDynamicPriceDataSourceProtocol, SBulletinBoardsDataSource, SEstimateComDataSource, SPopupDataSourceProtocol, SSCarBizDataSourceProtocal, SPickLikeWaitComDataSource>
{
    _Bool _bizVal_isLikeWait;
    _Bool _bizVal_isGuideToCarPool;
    _Bool _bizVal_isGuidToStation;
    _Bool _bizVal_isFirstStationEst;
    _Bool _bizVal_isStationConfrim;
    _Bool _bizVal_selectedStation;
    _Bool _bizval_AutoCreateOrder;
    _Bool _bizVal_isCrosscityConfrim;
    NSNumber *_bizVal_isCarpool;
    NSNumber *_bizVal_crosscityCarpoolErrorNo;
    NSNumber *_bizVal_carpoolSeat;
    NSNumber *_bizVal_carpoolNormalSeat;
    NSNumber *_bizVal_carpoolCrosscitySeat;
    NSString *_bizVal_isRegionOrder;
    NSNumber *_carpool_show;
    TRStationInfoModel *_bizVal_currentStation;
    NSMutableDictionary *_likeWaitMap;
}

@property(retain, nonatomic) NSMutableDictionary *likeWaitMap; // @synthesize likeWaitMap=_likeWaitMap;
@property(nonatomic) _Bool bizVal_isCrosscityConfrim; // @synthesize bizVal_isCrosscityConfrim=_bizVal_isCrosscityConfrim;
@property(nonatomic) _Bool bizval_AutoCreateOrder; // @synthesize bizval_AutoCreateOrder=_bizval_AutoCreateOrder;
@property(nonatomic) _Bool bizVal_selectedStation; // @synthesize bizVal_selectedStation=_bizVal_selectedStation;
@property(retain, nonatomic) TRStationInfoModel *bizVal_currentStation; // @synthesize bizVal_currentStation=_bizVal_currentStation;
@property(nonatomic) _Bool bizVal_isStationConfrim; // @synthesize bizVal_isStationConfrim=_bizVal_isStationConfrim;
@property(nonatomic) _Bool bizVal_isFirstStationEst; // @synthesize bizVal_isFirstStationEst=_bizVal_isFirstStationEst;
@property(nonatomic) _Bool bizVal_isGuidToStation; // @synthesize bizVal_isGuidToStation=_bizVal_isGuidToStation;
@property(nonatomic) _Bool bizVal_isGuideToCarPool; // @synthesize bizVal_isGuideToCarPool=_bizVal_isGuideToCarPool;
@property(retain, nonatomic) NSNumber *carpool_show; // @synthesize carpool_show=_carpool_show;
@property(copy, nonatomic) NSString *bizVal_isRegionOrder; // @synthesize bizVal_isRegionOrder=_bizVal_isRegionOrder;
@property(nonatomic) _Bool bizVal_isLikeWait; // @synthesize bizVal_isLikeWait=_bizVal_isLikeWait;
@property(retain, nonatomic) NSNumber *bizVal_carpoolCrosscitySeat; // @synthesize bizVal_carpoolCrosscitySeat=_bizVal_carpoolCrosscitySeat;
@property(retain, nonatomic) NSNumber *bizVal_carpoolNormalSeat; // @synthesize bizVal_carpoolNormalSeat=_bizVal_carpoolNormalSeat;
@property(retain, nonatomic) NSNumber *bizVal_carpoolSeat; // @synthesize bizVal_carpoolSeat=_bizVal_carpoolSeat;
@property(retain, nonatomic) NSNumber *bizVal_crosscityCarpoolErrorNo; // @synthesize bizVal_crosscityCarpoolErrorNo=_bizVal_crosscityCarpoolErrorNo;
@property(retain, nonatomic) NSNumber *bizVal_isCarpool; // @synthesize bizVal_isCarpool=_bizVal_isCarpool;
- (void).cxx_destruct;
- (void)clearCache;
- (long long)winXinPayAbilityChannel;
- (void)setickLikeWaitOn:(_Bool)arg1;
- (_Bool)isPickLikeWaitOn;
- (id)biz_carPoolSeatConfig;
- (id)biz_tipFee;
- (_Bool)supportPoolSeatMode;
- (int)cancelTripFlier;
- (_Bool)needLoadTripReasonVC;
- (id)carPoolViewModelForCarpoolCom:(id)arg1;
- (id)agenerateOrderInfo;
- (void)getCreateOrderModel:(CDUnknownBlockType)arg1;
- (id)estimateFeeDataModel;
- (id)dynamicPriceConfirmURLString;
- (id)dynamicPriceURLString;
- (_Bool)needDynamicPriceConfirmView;
- (_Bool)needDynamicPriceView;
- (void)bulletinBoardsClickedCard:(id)arg1 actBtnAtIndex:(long long)arg2 actionHandler:(CDUnknownBlockType)arg3;
- (void)bulletinBoardsDidTimerFinishedWorkForCard:(id)arg1 actionHandler:(CDUnknownBlockType)arg2;
- (_Bool)isLikeWaitTimerFinish;
- (void)setLikeWaitTimerFinish:(_Bool)arg1;
- (void)omgRefreshCoupon:(id)arg1;
- (id)dictionaryWithJsonString:(id)arg1;
- (id)getCompanyMsg:(id)arg1;
- (void)requestEstimateWithSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (id)generateOrderInfoEstimate;
- (long long)estimateComPollInteval;
- (id)postOrderRecomendModel;
- (id)inServicePagePopupDataModel;
- (id)homeCrosscityCarpoolPopupDataModel;
- (id)homeStationPagePopupDataModel;
- (id)popupDataForPopupCom;
- (_Bool)posMarkerShouldDisplayTotalCities:(long long)arg1;
- (id)posMarkerComStartAddrPrefix;
- (id)posMarkerComForVoiceCarProductId;
- (id)postOrderStartPoiModel;
- (id)posMarkerComStartAddrModelForScene:(long long)arg1;
- (void)requestCrosscityCarpoolWithSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (void)requestStationInfoWithSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

