//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SSheetItemView.h"

@class NSString, UILabel;

@interface SPayMessageView : SSheetItemView
{
    NSString *_message;
    UILabel *_textLabel;
}

+ (double)height;
@property(retain, nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;
@property(copy, nonatomic) NSString *message; // @synthesize message=_message;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)init;

@end

