//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TaxiBaseModel.h"

@class NSString<Optional>;

@interface TaxiCommentResultModel : TaxiBaseModel
{
    NSString<Optional> *_score1_title;
}

@property(copy, nonatomic) NSString<Optional> *score1_title; // @synthesize score1_title=_score1_title;
- (void).cxx_destruct;

@end

