//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray, NSString;

@interface TaxiDriverShareTripLetPayReq : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *commonTripItemsArray; // @dynamic commonTripItemsArray;
@property(readonly, nonatomic) unsigned long long commonTripItemsArray_Count; // @dynamic commonTripItemsArray_Count;
@property(nonatomic) int commonTripTotal; // @dynamic commonTripTotal;
@property(nonatomic) _Bool hasCommonTripTotal; // @dynamic hasCommonTripTotal;
@property(nonatomic) _Bool hasOrderId; // @dynamic hasOrderId;
@property(nonatomic) _Bool hasOtherFee; // @dynamic hasOtherFee;
@property(nonatomic) _Bool hasSelfTripTotal; // @dynamic hasSelfTripTotal;
@property(nonatomic) _Bool hasTip; // @dynamic hasTip;
@property(nonatomic) _Bool hasTripTotal; // @dynamic hasTripTotal;
@property(copy, nonatomic) NSString *orderId; // @dynamic orderId;
@property(nonatomic) int otherFee; // @dynamic otherFee;
@property(retain, nonatomic) NSMutableArray *selfTripItemsArray; // @dynamic selfTripItemsArray;
@property(readonly, nonatomic) unsigned long long selfTripItemsArray_Count; // @dynamic selfTripItemsArray_Count;
@property(nonatomic) int selfTripTotal; // @dynamic selfTripTotal;
@property(nonatomic) int tip; // @dynamic tip;
@property(nonatomic) int tripTotal; // @dynamic tripTotal;

@end

