//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TRBaseModel.h"

@class NSNumber<Optional>, NSString<Optional>;

@interface TRWanliuCarTypeModel : TRBaseModel
{
    NSNumber<Optional> *_c_default;
    NSNumber<Optional> *_c_level;
    NSString<Optional> *_c_logo;
    NSString<Optional> *_c_level_name;
    NSString<Optional> *_c_price;
    NSString<Optional> *_c_estimate_tips;
    NSString<Optional> *_c_coupon_tips;
    NSString<Optional> *_c_min_estimate;
    NSString<Optional> *_c_android_icon;
}

@property(retain, nonatomic) NSString<Optional> *c_android_icon; // @synthesize c_android_icon=_c_android_icon;
@property(retain, nonatomic) NSString<Optional> *c_min_estimate; // @synthesize c_min_estimate=_c_min_estimate;
@property(retain, nonatomic) NSString<Optional> *c_coupon_tips; // @synthesize c_coupon_tips=_c_coupon_tips;
@property(retain, nonatomic) NSString<Optional> *c_estimate_tips; // @synthesize c_estimate_tips=_c_estimate_tips;
@property(retain, nonatomic) NSString<Optional> *c_price; // @synthesize c_price=_c_price;
@property(retain, nonatomic) NSString<Optional> *c_level_name; // @synthesize c_level_name=_c_level_name;
@property(retain, nonatomic) NSString<Optional> *c_logo; // @synthesize c_logo=_c_logo;
@property(retain, nonatomic) NSNumber<Optional> *c_level; // @synthesize c_level=_c_level;
@property(retain, nonatomic) NSNumber<Optional> *c_default; // @synthesize c_default=_c_default;
- (void).cxx_destruct;

@end

