//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TRWanliuBaseRequest.h"

@interface TRWanLiuGetOrderDetailRequest : TRWanliuBaseRequest
{
}

+ (id)modelWithData:(id)arg1;
+ (id)oknet_adapterWithOid:(id)arg1 timeout:(double)arg2;
- (id)responseModelWithData:(id)arg1;
- (_Bool)isUniPayEnable;
- (id)initWithOid:(id)arg1 timeout:(double)arg2;
- (id)initWithOid:(id)arg1;
- (id)pathName;
- (id)methodName;

@end

