//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray<FMFishpondInfoUserDO>, NSString;

@interface FMFishpondInfoDO : NSObject
{
    NSString *_desc;
    NSString *_poolName;
    NSString *_serverTime;
    NSArray<FMFishpondInfoUserDO> *_adminList;
    NSArray<FMFishpondInfoUserDO> *_userList;
}

@property(retain, nonatomic) NSArray<FMFishpondInfoUserDO> *userList; // @synthesize userList=_userList;
@property(retain, nonatomic) NSArray<FMFishpondInfoUserDO> *adminList; // @synthesize adminList=_adminList;
@property(copy, nonatomic) NSString *serverTime; // @synthesize serverTime=_serverTime;
@property(copy, nonatomic) NSString *poolName; // @synthesize poolName=_poolName;
@property(copy, nonatomic) NSString *desc; // @synthesize desc=_desc;
- (void).cxx_destruct;

@end

