//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIGestureRecognizerDelegate.h"
#import "UIScrollViewDelegate.h"

@class FMFullScreenVideoView, FMImageView, FMItemDO, NSArray, NSString, UIScrollView;

@interface FMMaxImageView : UIView <UIGestureRecognizerDelegate, UIScrollViewDelegate>
{
    _Bool _pageChanged;
    _Bool _isNeedLoad;
    NSString *_titleText;
    FMFullScreenVideoView *_videoView;
    NSArray *_imageDOs;
    FMItemDO *_itemDO;
    FMImageView *_videoOriginalImageView;
    NSString *_itemId;
    NSString *_videoID;
    UIView *_markView;
    UIScrollView *_imageScrollView;
    UIView *_toolBarView;
    UIView *_picTitleView;
    long long _count;
    long long _page;
    long long _lastPage;
    double _lastPosition;
}

@property(nonatomic) double lastPosition; // @synthesize lastPosition=_lastPosition;
@property(nonatomic) _Bool isNeedLoad; // @synthesize isNeedLoad=_isNeedLoad;
@property(nonatomic) _Bool pageChanged; // @synthesize pageChanged=_pageChanged;
@property(nonatomic) long long lastPage; // @synthesize lastPage=_lastPage;
@property(nonatomic) long long page; // @synthesize page=_page;
@property(nonatomic) long long count; // @synthesize count=_count;
@property(retain, nonatomic) UIView *picTitleView; // @synthesize picTitleView=_picTitleView;
@property(retain, nonatomic) UIView *toolBarView; // @synthesize toolBarView=_toolBarView;
@property(retain, nonatomic) UIScrollView *imageScrollView; // @synthesize imageScrollView=_imageScrollView;
@property(retain, nonatomic) UIView *markView; // @synthesize markView=_markView;
@property(copy, nonatomic) NSString *videoID; // @synthesize videoID=_videoID;
@property(copy, nonatomic) NSString *itemId; // @synthesize itemId=_itemId;
@property(retain, nonatomic) FMImageView *videoOriginalImageView; // @synthesize videoOriginalImageView=_videoOriginalImageView;
@property(retain, nonatomic) FMItemDO *itemDO; // @synthesize itemDO=_itemDO;
@property(retain, nonatomic) NSArray *imageDOs; // @synthesize imageDOs=_imageDOs;
@property(retain, nonatomic) FMFullScreenVideoView *videoView; // @synthesize videoView=_videoView;
@property(copy, nonatomic) NSString *titleText; // @synthesize titleText=_titleText;
- (void).cxx_destruct;
- (void)reachabilityReachableChanged:(id)arg1;
- (void)showWithImageDO:(id)arg1 page:(unsigned long long)arg2 itemDO:(id)arg3 videoOriginalImageView:(id)arg4;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (id)getRealNum:(long long)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)showNext:(_Bool)arg1 prev:(_Bool)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)initImagesScrollView;
- (struct CGRect)getOriRect:(id)arg1;
- (void)reChangeInitRect;
- (void)image:(id)arg1 didFinishSavingWithError:(id)arg2 contextInfo:(void *)arg3;
- (void)longPress:(id)arg1;
- (void)tapGesture:(id)arg1;
- (void)removeMaxImageView;
- (void)hideScrollPanel;
- (void)detail;
- (void)setGestureRecognizer;
- (void)initTitleView;
- (void)initToolBar;
- (void)initBigPicView;
- (void)removeScrollPanel;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

