//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class FMMyCityRefreshView;

@protocol FMMyCityRefreshViewDelegate
- (_Bool)refreshDataSourceIsLoading:(FMMyCityRefreshView *)arg1;
- (void)refreshDidTriggerRefresh:(FMMyCityRefreshView *)arg1;
@end

