//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSError, NSString, NSURL, UIView, UIView<WVWebViewBasicProtocol>, UIViewController, WXSDKInstance;

@protocol WVBridgeContext <NSObject>
@property(readonly, nonatomic) __weak WXSDKInstance *weexEnv;
@property(readonly, nonatomic) __weak UIView<WVWebViewBasicProtocol> *webViewEnv;
@property(readonly, nonatomic) __weak id env;
@property(readonly, nonatomic) __weak UIViewController *viewController;
@property(readonly, nonatomic) __weak UIView *view;
@property(readonly, nonatomic) NSURL *referrer;
- (void)releaseHandler:(id)arg1;
- (NSError *)addTailInvocation:(NSString *)arg1 withParams:(NSDictionary *)arg2;
- (_Bool)dispatchEvent:(NSString *)arg1 withParam:(NSDictionary *)arg2 withCallback:(void (^)(NSString *, _Bool))arg3;
- (_Bool)dispatchEvent:(NSString *)arg1 withParam:(NSDictionary *)arg2;
@end

