//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSIndexPath, UICollectionView, UICollectionViewLayout;

@protocol WXMultiColumnLayoutDelegate <NSObject>
- (double)collectionView:(UICollectionView *)arg1 layout:(UICollectionViewLayout *)arg2 isNeedStickyForHeaderInSection:(long long)arg3;
- (_Bool)collectionView:(UICollectionView *)arg1 layout:(UICollectionViewLayout *)arg2 hasHeaderInSection:(long long)arg3;
- (double)collectionView:(UICollectionView *)arg1 layout:(UICollectionViewLayout *)arg2 heightForHeaderInSection:(long long)arg3;
- (double)collectionView:(UICollectionView *)arg1 layout:(UICollectionViewLayout *)arg2 heightForItemAtIndexPath:(NSIndexPath *)arg3;
- (double)collectionView:(UICollectionView *)arg1 contentWidthForLayout:(UICollectionViewLayout *)arg2;
- (struct UIEdgeInsets)collectionView:(UICollectionView *)arg1 insetForLayout:(UICollectionViewLayout *)arg2;
@end

