//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FMCRPCStruct.h"

@class FMCECallConfirmationStatus, FMCVehicleDataNotificationStatus;

@interface FMCECallInfo : FMCRPCStruct
{
}

@property(retain) FMCECallConfirmationStatus *eCallConfirmationStatus;
@property(retain) FMCVehicleDataNotificationStatus *auxECallNotificationStatus;
@property(retain) FMCVehicleDataNotificationStatus *eCallNotificationStatus;
- (id)initWithDictionary:(id)arg1;
- (id)init;

@end

