//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MCEmailSuggestList, NSString;

@protocol MCEmailSuggestListDelegate <NSObject>
- (void)suggestList:(MCEmailSuggestList *)arg1 didSelectSuggest:(NSString *)arg2;
@end

