//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIColor;

@interface MCRulerDialView : UIView
{
    unsigned long long _style;
    unsigned long long _stepCount;
    unsigned long long _stepCountPerSection;
    UIColor *_shorterDialColor;
    UIColor *_longerDialColor;
    double _longerDialHeightRatio;
    double _shorterDialHeightRatio;
}

@property(nonatomic) double shorterDialHeightRatio; // @synthesize shorterDialHeightRatio=_shorterDialHeightRatio;
@property(nonatomic) double longerDialHeightRatio; // @synthesize longerDialHeightRatio=_longerDialHeightRatio;
@property(retain, nonatomic) UIColor *longerDialColor; // @synthesize longerDialColor=_longerDialColor;
@property(retain, nonatomic) UIColor *shorterDialColor; // @synthesize shorterDialColor=_shorterDialColor;
@property(nonatomic) unsigned long long stepCountPerSection; // @synthesize stepCountPerSection=_stepCountPerSection;
@property(nonatomic) unsigned long long stepCount; // @synthesize stepCount=_stepCount;
@property(nonatomic) unsigned long long style; // @synthesize style=_style;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (void)drawLineAtX:(double)arg1 withIndex:(int)arg2 rect:(struct CGRect)arg3 context:(struct CGContext *)arg4;
- (struct CGContext *)prepareDrawLines;
- (id)initWithFrame:(struct CGRect)arg1;

@end

