//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NMCatalogue, NMSettingHeaderFooterView, NSArray, NSMutableArray, UIImage, UIImageView, UILabel, UIView;

@interface NMCategoryCell : UITableViewCell
{
    UIView *_formBgView;
    NMSettingHeaderFooterView *_topView;
    NMSettingHeaderFooterView *_bottomView;
    UIImageView *_leftBlockBg;
    UIImageView *_iconImage;
    UILabel *_iconTitle;
    NSMutableArray *_buttonArray;
    UIImage *_buttonBg;
    UIImage *_buttonHighlightBg;
    UIImage *_buttonBottomBg;
    UIImage *_buttonBottomHighlightBg;
    UIImage *_buttonRightBg;
    UIImage *_buttonRightHighlightBg;
    long long _btnWidth;
    NMCatalogue *_catalogue;
    NSArray *_categoryArray;
    id <NMCategoryCellDelegate> _delegate;
}

+ (double)height:(id)arg1;
+ (double)blankHeight;
+ (double)buttonHeight;
@property(nonatomic) id <NMCategoryCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) NSArray *categoryArray; // @synthesize categoryArray=_categoryArray;
@property(retain, nonatomic) NMCatalogue *catalogue; // @synthesize catalogue=_catalogue;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)onButtonClicked:(id)arg1;
- (void)setButtonBackgroundImage;
- (long long)column:(long long)arg1;
- (long long)row:(long long)arg1;
- (void)setCategoryArray:(id)arg1 selectedCategoryName:(id)arg2;
- (void)setCategoryArray:(id)arg1;
- (long long)rowCountForCount:(long long)arg1;
- (void)layoutSubviews;
- (void)handleSkinChange:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

