//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSMutableArray, UIColor;

@interface NMCountNumberLabel : UIView
{
    unsigned long long _expectedCount;
    unsigned long long _currentCount;
    double _numberFontSize;
    struct CGSize _numberViewSize;
    double _numberViewInnerPadding;
    double _selfHeight;
    UIColor *_numberColor;
    double _labelHeight;
    NSMutableArray *_numberViews;
    id <NMCountNumberLabelDelegate> _delegate;
}

+ (double)widthForExpectedNumber:(unsigned long long)arg1 numberViewWidth:(double)arg2 numberViewPadding:(double)arg3;
@property(nonatomic) __weak id <NMCountNumberLabelDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) unsigned long long expectedCount; // @synthesize expectedCount=_expectedCount;
- (void).cxx_destruct;
- (void)updateCount:(unsigned long long)arg1;
- (void)updateExpectedCount:(unsigned long long)arg1 currentVote:(unsigned long long)arg2;
- (void)layoutSubviews;
- (void)refreshSize;
- (id)initWithExpectedCount:(unsigned long long)arg1 initialCount:(unsigned long long)arg2 numberFontSize:(double)arg3 numberColor:(id)arg4 numberViewSize:(struct CGSize)arg5 numberViewPadding:(double)arg6 labelHeight:(double)arg7;

@end

