//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSMutableArray, NSObject<OS_dispatch_group>, NSObject<OS_dispatch_semaphore>;

@interface NMMultiRequestWrapper : NSObject
{
    _Bool _needOrder;
    NSMutableArray *_requestArray;
    id <NMHttpRequestDelegate> _delegate;
    NSDictionary *_exParams;
    NSObject<OS_dispatch_semaphore> *_semaphore;
    NSObject<OS_dispatch_group> *_group;
}

@property(nonatomic) _Bool needOrder; // @synthesize needOrder=_needOrder;
@property(retain, nonatomic) NSObject<OS_dispatch_group> *group; // @synthesize group=_group;
@property(retain, nonatomic) NSObject<OS_dispatch_semaphore> *semaphore; // @synthesize semaphore=_semaphore;
@property(copy, nonatomic) NSDictionary *exParams; // @synthesize exParams=_exParams;
@property(nonatomic) __weak id <NMHttpRequestDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) NSMutableArray *requestArray; // @synthesize requestArray=_requestArray;
- (void).cxx_destruct;
- (void)_finishRequests;
- (void)_startOutOrder;
- (void)_startInOrder;
- (void)cancel;
- (void)start;
- (id)initWithMultiRequests:(id)arg1 needOrder:(_Bool)arg2;
- (id)initWithMultiRequests:(id)arg1;
- (void)dealloc;

@end

