//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NMMyCollectionSubViewController.h"

#import "NMRecommendMVCellDelegate.h"

@class NSString;

@interface NMMyCollectedMvViewController : NMMyCollectionSubViewController <NMRecommendMVCellDelegate>
{
}

- (void)willRemoveItem:(id)arg1;
- (id)itemTypeName;
- (void)setItemUncollected:(id)arg1;
- (id)itemWithUnCollectRequest:(id)arg1;
- (unsigned long long)maxRecommendCount;
- (id)recommendResultKey;
- (void)prepareItems:(id)arg1 finished:(CDUnknownBlockType)arg2;
- (id)itemWithDictionary:(id)arg1;
- (id)idForItem:(id)arg1;
- (id)moreRecommendViewController;
- (void)logMoreButtonClick;
- (void)logImpressWithItem:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)logClickActionWithItem:(id)arg1 recommend:(_Bool)arg2;
- (id)itemViewControllerWithItem:(id)arg1;
- (id)recommendCellWithTableView:(id)arg1 cellIdentifier:(id)arg2 items:(id)arg3;
- (double)recommendCellHeightWithItems:(id)arg1;
- (id)itemCellWithTableView:(id)arg1 cellIdentifier:(id)arg2 item:(id)arg3;
- (_Bool)recommentItemSingleCell;
- (double)itemCellHeight;
- (id)recommendRequest;
- (id)refreshRequestWithCount:(unsigned long long)arg1;
- (id)loadMoreRequestWithCount:(unsigned long long)arg1 offset:(unsigned long long)arg2;
- (id)sendRemoveCollectRequestWithItem:(id)arg1;
- (void)logSearchBegin;
- (_Bool)searchMatchedItem:(id)arg1 keyword:(id)arg2;
- (id)collectStateChangeNotificationStateKey;
- (id)collectStateChangeNotificationIdKey;
- (id)batchCollectStateChangeNotificationName;
- (id)collectStateChangeNotificationName;
- (double)tableViewLeftEdgeInset;
- (void)recommendMVCell:(id)arg1 mvClicked:(id)arg2;
- (void)_downloadMVChanged:(id)arg1;
- (void)downloadMVStart;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (unsigned long long)type;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

