//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "Mobike_ViewController.h"

#import "MBKApplePayDelegate.h"
#import "UIAlertViewDelegate.h"
#import "UITextFieldDelegate.h"
#import "netNoneFreshDelegate.h"

@class MBKCardConfigModel, NSMutableArray, NSString, NoNetWrokViewController, PayMethodButton, UIButton, UILabel, UIView;

@interface DingViewController : Mobike_ViewController <UITextFieldDelegate, netNoneFreshDelegate, MBKApplePayDelegate, UIAlertViewDelegate>
{
    long long payCount;
    long long payIndex;
    PayMethodButton *weichatPay;
    PayMethodButton *redPacketPay;
    id orderInfo;
    long long applePayType;
    _Bool _rechargeListReady;
    _Bool _payMethodListReady;
    long long _type;
    unsigned long long _payPlatform;
    NoNetWrokViewController *_netWorkView;
    UIButton *_rechargeBtn;
    UIView *_subBtnView;
    UIView *_payMethodContainerView;
    NSMutableArray *_rechargeListArray;
    NSMutableArray *_payMethodListArray;
    UILabel *_depositLine;
    MBKCardConfigModel *_cardConfigModel;
}

@property(retain, nonatomic) MBKCardConfigModel *cardConfigModel; // @synthesize cardConfigModel=_cardConfigModel;
@property(retain, nonatomic) UILabel *depositLine; // @synthesize depositLine=_depositLine;
@property(nonatomic) _Bool payMethodListReady; // @synthesize payMethodListReady=_payMethodListReady;
@property(nonatomic) _Bool rechargeListReady; // @synthesize rechargeListReady=_rechargeListReady;
@property(retain) NSMutableArray *payMethodListArray; // @synthesize payMethodListArray=_payMethodListArray;
@property(retain) NSMutableArray *rechargeListArray; // @synthesize rechargeListArray=_rechargeListArray;
@property(retain, nonatomic) UIView *payMethodContainerView; // @synthesize payMethodContainerView=_payMethodContainerView;
@property(retain, nonatomic) UIView *subBtnView; // @synthesize subBtnView=_subBtnView;
@property(retain, nonatomic) UIButton *rechargeBtn; // @synthesize rechargeBtn=_rechargeBtn;
@property(retain, nonatomic) NoNetWrokViewController *netWorkView; // @synthesize netWorkView=_netWorkView;
@property(nonatomic) unsigned long long payPlatform; // @synthesize payPlatform=_payPlatform;
@property long long type; // @synthesize type=_type;
- (void).cxx_destruct;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)applePayResultCallBack:(id)arg1 withError:(id)arg2;
- (void)onRequestPayWayListFailed:(id)arg1;
- (void)onRequestPayWayListSucc:(id)arg1;
- (void)requestRechargeListFailed:(id)arg1;
- (void)requestRechargeListSucc:(id)arg1;
- (void)requestDepositionFailed:(id)arg1;
- (void)requestDepositionSucc:(id)arg1;
- (void)loaddeposit;
- (void)appToForeGround:(id)arg1;
- (void)selectedMoneyAction:(long long)arg1;
- (void)dealloc;
- (void)requestPayParamsFailed:(id)arg1;
- (void)requestPayParamsSucc:(id)arg1;
- (void)rechargeBtnAction:(id)arg1;
- (void)paymentStatusCallback;
- (void)paymentStatusCallbackFailed;
- (void)handleNotification:(id)arg1;
- (void)setupController;
- (void)redpacketEnough:(_Bool)arg1;
- (void)onTapPayMethond:(long long)arg1;
- (void)rechargeInstructionAction:(id)arg1;
- (id)attributedString:(id)arg1 length:(long long)arg2;
- (void)layoutPayMethods;
- (void)setupView;
- (void)getAcountInfo;
- (void)onBackAction:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)netNoneFresh:(long long)arg1;
- (void)loadNomal;
- (void)layoutPayWayList;
- (void)requestPayList;
- (void)viewDidLoad;
- (void)updateAllLayout;
- (void)layoutRecharedButtons;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

