//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GMSx_PBGeneratedMessage.h"

@class NSString;

@interface GMSx_GMPCIconStyle : GMSx_PBGeneratedMessage
{
}

+ (id)descriptor;
@property(nonatomic) int iconURLPrefixIndex;
@property(nonatomic) _Bool hasIconURLPrefixIndex;
@property(retain, nonatomic) NSString *iconURL;
@property(nonatomic) _Bool hasIconURL;

// Remaining properties
@property(nonatomic) unsigned int colorFilterArgb; // @dynamic colorFilterArgb;
@property(nonatomic) _Bool hasColorFilterArgb; // @dynamic hasColorFilterArgb;
@property(nonatomic) _Bool hasHighlightColorRgb; // @dynamic hasHighlightColorRgb;
@property(nonatomic) _Bool hasIconHeight; // @dynamic hasIconHeight;
@property(nonatomic) _Bool hasIconScale; // @dynamic hasIconScale;
@property(nonatomic) _Bool hasIconUrl; // @dynamic hasIconUrl;
@property(nonatomic) _Bool hasIconUrlPrefixIndex; // @dynamic hasIconUrlPrefixIndex;
@property(nonatomic) _Bool hasIconWidth; // @dynamic hasIconWidth;
@property(nonatomic) unsigned int highlightColorRgb; // @dynamic highlightColorRgb;
@property(nonatomic) int iconHeight; // @dynamic iconHeight;
@property(nonatomic) int iconScale; // @dynamic iconScale;
@property(retain, nonatomic) NSString *iconUrl; // @dynamic iconUrl;
@property(nonatomic) int iconUrlPrefixIndex; // @dynamic iconUrlPrefixIndex;
@property(nonatomic) int iconWidth; // @dynamic iconWidth;

@end

