//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GTPNetworkCalculator : NSObject
{
}

+ (id)subnetToWildCard:(id)arg1;
+ (_Bool)isEqualBinary:(id)arg1 andLastIPArray:(id)arg2;
+ (id)binaryToIP:(id)arg1;
+ (id)ipToBinary:(id)arg1;
+ (id)print01:(int)arg1;
+ (_Bool)isValidIPAddress:(id)arg1;
+ (id)increaseBitArray:(id)arg1;
+ (id)lastIPToPingForIPAddress:(id)arg1 subnetMask:(id)arg2;
+ (id)firstIPToPingForIPAddress:(id)arg1 subnetMask:(id)arg2;
+ (id)getAllHostsForIP:(id)arg1 andSubnet:(id)arg2 onMaxCount:(long long)arg3;

@end

