//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface Mobike_WebPlaceholderView : UIView
{
    CDUnknownBlockType _dismissHandler;
}

@property(copy, nonatomic) CDUnknownBlockType dismissHandler; // @synthesize dismissHandler=_dismissHandler;
- (void).cxx_destruct;
- (void)onTapDismiss;
- (id)initWithFrame:(struct CGRect)arg1;

@end

