//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "Mobike_ViewController.h"

#import "BluetoothGuideDelegate.h"
#import "MBKCentralDelegate.h"
#import "closeHelpDelegate.h"
#import "manualInputView.h"

@class AVCaptureDevice, AVCaptureDeviceInput, AVCaptureMetadataOutput, AVCaptureSession, AVCaptureVideoPreviewLayer, BlueToothGuideView, CardBackGroundView, MBKAudioPlayer, MBKCentral, NSString, NSTimer, QRcodeView, UIButton, UIImageView;

@interface ScanQRCodeViewController : Mobike_ViewController <manualInputView, closeHelpDelegate, MBKCentralDelegate, BluetoothGuideDelegate>
{
    QRcodeView *rcodeView;
    MBKAudioPlayer *player;
    BlueToothGuideView *bluetoothGuideView;
    NSTimer *bluetoothTimer;
    UIButton *bluetoothNoticeButton;
    _Bool isPermitBack;
    _Bool islimit;
    AVCaptureDevice *_device;
    AVCaptureDeviceInput *_input;
    AVCaptureMetadataOutput *_output;
    AVCaptureSession *_session;
    AVCaptureVideoPreviewLayer *_preview;
    UIImageView *_line;
    UIImageView *_backgroundView;
    NSString *_bikeCode;
    CardBackGroundView *_cards;
    MBKCentral *_mbCentral;
    struct CLLocationCoordinate2D _currentCoordinate;
}

@property(retain, nonatomic) MBKCentral *mbCentral; // @synthesize mbCentral=_mbCentral;
@property(retain) CardBackGroundView *cards; // @synthesize cards=_cards;
@property(retain, nonatomic) NSString *bikeCode; // @synthesize bikeCode=_bikeCode;
@property(retain, nonatomic) UIImageView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) UIImageView *line; // @synthesize line=_line;
@property(retain, nonatomic) AVCaptureVideoPreviewLayer *preview; // @synthesize preview=_preview;
@property(retain, nonatomic) AVCaptureSession *session; // @synthesize session=_session;
@property(retain, nonatomic) AVCaptureMetadataOutput *output; // @synthesize output=_output;
@property(retain, nonatomic) AVCaptureDeviceInput *input; // @synthesize input=_input;
@property(retain, nonatomic) AVCaptureDevice *device; // @synthesize device=_device;
@property(nonatomic) struct CLLocationCoordinate2D currentCoordinate; // @synthesize currentCoordinate=_currentCoordinate;
- (void).cxx_destruct;
- (void)destoryBlueTooth;
- (void)destoryQRcode;
- (void)ringSound;
- (void)dealloc;
- (void)startScanPeripheral;
- (void)gotoUnlockAnimat;
- (void)onCancel;
- (void)mobikeScanPeripheralsTimeOut:(long long)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)popToMainView;
- (void)updateViewController;
- (void)onBackAction:(id)arg1;
- (void)manualInputViewClicked;
- (void)mobikeCentralUpdateState:(long long)arg1;
- (void)peripheralBackhaulString:(id)arg1;
- (void)mobikeCentralMgr:(id)arg1 didFailToConnectPeripheral:(id)arg2 error:(id)arg3;
- (void)closeHelpEvent:(id)arg1;
- (void)displayOperationCards;
- (void)displayCards;
- (void)onUserHelpBarButotnAction:(id)arg1;
- (void)handleNotification:(id)arg1;
- (void)setupController;
- (void)initQRCode;
- (void)bluetoothBtnAction:(id)arg1;
- (void)setupView;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

