//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSString;

@interface TencentLBSAppList : NSObject
{
    NSString *_docPath;
    NSString *_path;
    NSDate *_last;
}

+ (id)sharedInstance;
@property(copy, nonatomic) NSDate *last; // @synthesize last=_last;
@property(copy, nonatomic) NSString *path; // @synthesize path=_path;
@property(copy, nonatomic) NSString *docPath; // @synthesize docPath=_docPath;
- (void).cxx_destruct;
- (void)postAppList;
- (id)init;

@end

