//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CTBusinessBean.h"

@class BasicListResInformationModel, BindBankCardInformationModel, BindWalletInformationModel, NSMutableArray, NSString, TouchPayInformationModel;

@interface BindPayListSearchResponse : CTBusinessBean
{
    int resultCode;
    NSString *subCode;
    NSString *resultMessage;
    NSString *debugMessage;
    BasicListResInformationModel *basicListResInfoModel;
    BindWalletInformationModel *walletInfoModel;
    BindBankCardInformationModel *bankCardInfoModel;
    NSMutableArray *thirdPayList;
    NSMutableArray *payDisplaySettingsList;
    TouchPayInformationModel *touchPayInfoModel;
    int paymentRoute;
    NSString *icoResourceUrl;
    NSString *paySign;
    NSString *dataVersion;
}

@property(copy, nonatomic) NSString *dataVersion; // @synthesize dataVersion;
@property(copy, nonatomic) NSString *paySign; // @synthesize paySign;
@property(copy, nonatomic) NSString *icoResourceUrl; // @synthesize icoResourceUrl;
@property(nonatomic) int paymentRoute; // @synthesize paymentRoute;
@property(retain, nonatomic) TouchPayInformationModel *touchPayInfoModel; // @synthesize touchPayInfoModel;
@property(retain, nonatomic) NSMutableArray *payDisplaySettingsList; // @synthesize payDisplaySettingsList;
@property(retain, nonatomic) NSMutableArray *thirdPayList; // @synthesize thirdPayList;
@property(retain, nonatomic) BindBankCardInformationModel *bankCardInfoModel; // @synthesize bankCardInfoModel;
@property(retain, nonatomic) BindWalletInformationModel *walletInfoModel; // @synthesize walletInfoModel;
@property(retain, nonatomic) BasicListResInformationModel *basicListResInfoModel; // @synthesize basicListResInfoModel;
@property(copy, nonatomic) NSString *debugMessage; // @synthesize debugMessage;
@property(copy, nonatomic) NSString *resultMessage; // @synthesize resultMessage;
@property(copy, nonatomic) NSString *subCode; // @synthesize subCode;
@property(nonatomic) int resultCode; // @synthesize resultCode;
- (void).cxx_destruct;
- (id)getPBAnnotationArray;
- (id)getAnnotationArray;
- (id)init;

@end

