//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CTViewModel.h"

@class NSString;

@interface CTAdDateInformation : CTViewModel
{
    NSString *_beginDate;
    NSString *_endDate;
}

@property(retain, nonatomic) NSString *endDate; // @synthesize endDate=_endDate;
@property(retain, nonatomic) NSString *beginDate; // @synthesize beginDate=_beginDate;
- (void).cxx_destruct;
- (_Bool)isHit:(id)arg1;

@end

