//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIWebView.h"

@interface CTAddJSInterfaceWebView : UIWebView
{
}

+ (void)load;
- (id)webViewProxyDelegate;
- (void)addJavascriptInterfaces:(id)arg1 withName:(id)arg2;
- (void)YQHybridSetDelegate:(id)arg1;

@end

