//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CTChatConfigManager.h"

@class NSDate, NSMutableDictionary;

@interface CTChatUpdateManager : CTChatConfigManager
{
    int queueNum;
    NSDate *messageUpDate;
    _Bool _isFirstSynced;
    int syncConversationQueueTag;
    _Bool _isSyncingConversationsAndMessages;
    NSMutableDictionary *_activeConversationsDict;
    NSMutableDictionary *_activeConversationsNeedRetryDict;
    NSDate *_lastSyncDate;
}

+ (id)updateManager;
@property(retain, nonatomic) NSDate *lastSyncDate; // @synthesize lastSyncDate=_lastSyncDate;
@property(retain) NSMutableDictionary *activeConversationsNeedRetryDict; // @synthesize activeConversationsNeedRetryDict=_activeConversationsNeedRetryDict;
@property(retain) NSMutableDictionary *activeConversationsDict; // @synthesize activeConversationsDict=_activeConversationsDict;
@property(readonly, nonatomic) _Bool isSyncingConversationsAndMessages; // @synthesize isSyncingConversationsAndMessages=_isSyncingConversationsAndMessages;
- (void).cxx_destruct;
- (void)requestThreadInfo:(id)arg1 resultBlock:(CDUnknownBlockType)arg2;
- (void)updateGroupMember:(id)arg1 member:(id)arg2;
- (void)updateGroupMembers:(id)arg1 pagingParameter:(id)arg2 resultBlock:(CDUnknownBlockType)arg3;
- (void)updatePartnerInfo:(id)arg1 andType:(long long)arg2 resultBlock:(CDUnknownBlockType)arg3;
- (void)updateGroupSettingInfoGid:(id)arg1 resultBlock:(CDUnknownBlockType)arg2;
- (void)updateConversationInfo:(id)arg1;
- (void)updateConversationInfo:(id)arg1 andTimestampToNow:(id)arg2;
- (void)startMessageUpdateWithConversation:(id)arg1 andTimeStamp:(id)arg2 withType:(long long)arg3;
- (void)startMessageUpdateWithConversation:(id)arg1 andTimestampToNow:(id)arg2 withType:(long long)arg3;
- (void)syncLatestMessagesForOneConversation:(id)arg1 startMsgId:(long long)arg2 endMsgId:(long long)arg3 withType:(long long)arg4 result:(CDUnknownBlockType)arg5;
- (void)syncLatestMessagesForConversationList:(id)arg1 andTag:(int)arg2 withType:(long long)arg3 needRetryed:(_Bool)arg4;
- (void)syncConversationsAndMessagesFinish;
- (void)updateConversationsMessageWithList:(id)arg1 andIndex:(int)arg2 andTimeStamp:(id)arg3 andTag:(int)arg4 withType:(long long)arg5;
- (void)updateMessageWithList:(id)arg1 andIndex:(int)arg2 andTimestampToNow:(id)arg3 andTag:(int)arg4 withType:(long long)arg5;
- (void)messageUpdateType:(long long)arg1;
- (id)conversationListSortDescByLastActivityTime:(id)arg1;
- (void)updateActiveConversationListWithTimeStamp:(id)arg1 andOwnerjid:(id)arg2 andTag:(int)arg3 withType:(long long)arg4 isRetry:(_Bool)arg5;
- (void)startConversationListUpdateWithTimeStamp:(id)arg1 andOwnerjid:(id)arg2 withType:(long long)arg3;
- (void)startConversationListUpdateWithTimeStampToNow:(id)arg1 withType:(long long)arg2;
- (_Bool)isSyncMessageNewVersion;
- (_Bool)isVersionB;
- (id)init;

@end

