//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CAGradientLayer, UILabel;

@interface CTDiscoverGradientView : UIView
{
    UILabel *_titleLabel;
    UIView *_contentView;
    CAGradientLayer *_bgLayer;
}

@property(retain, nonatomic) CAGradientLayer *bgLayer; // @synthesize bgLayer=_bgLayer;
@property(nonatomic) __weak UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (void)configGradientLayer;
- (void)layoutSubviews;
- (void)awakeFromNib;

@end

