//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CTLoginTableViewWidget.h"

#import "UIAlertViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class CTCustomeGroupTableViewCell, NSDate, NSString, UIButton, UILabel, UITableViewCell, UITextField, UIView;

@interface CTFindPasswordStepOne : CTLoginTableViewWidget <UIGestureRecognizerDelegate, UIAlertViewDelegate>
{
    NSDate *_sendCodeTime;
    CTCustomeGroupTableViewCell *_phoneNumCell;
    UIButton *_nextStepButton;
    UIView *_nextStepView;
    UITextField *_phoneNumTextField;
    UITableViewCell *_countryPhoneCodeCell;
    UILabel *_countryPhoneCode;
}

@property(retain, nonatomic) UILabel *countryPhoneCode; // @synthesize countryPhoneCode=_countryPhoneCode;
@property(retain, nonatomic) UITableViewCell *countryPhoneCodeCell; // @synthesize countryPhoneCodeCell=_countryPhoneCodeCell;
@property(retain, nonatomic) UITextField *phoneNumTextField; // @synthesize phoneNumTextField=_phoneNumTextField;
@property(retain, nonatomic) UIView *nextStepView; // @synthesize nextStepView=_nextStepView;
@property(retain, nonatomic) UIButton *nextStepButton; // @synthesize nextStepButton=_nextStepButton;
@property(retain, nonatomic) CTCustomeGroupTableViewCell *phoneNumCell; // @synthesize phoneNumCell=_phoneNumCell;
- (void).cxx_destruct;
- (void)didSelectedCountryPhoneCode:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)setTextFieldHightlighted:(id)arg1;
- (void)setTextFieldNormal:(id)arg1;
- (void)sendGetVerifyCode;
- (void)doNextStep;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)widgetWillAppear;
- (void)widgetDidInit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

