//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSLock, NSString;

@interface CTFileLog : NSObject
{
    NSLock *_lock;
    NSString *_logFilePath;
}

@property(retain, nonatomic) NSString *logFilePath; // @synthesize logFilePath=_logFilePath;
@property(retain, nonatomic) NSLock *lock; // @synthesize lock=_lock;
- (void).cxx_destruct;
- (void)appendLog:(id)arg1;
- (void)writeLog:(id)arg1 toFile:(id)arg2;
- (long long)fiseSizeAtPath:(id)arg1;
- (id)initWithLogFile:(id)arg1;

@end

