//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CTFlightCommon : NSObject
{
}

+ (void)flyView:(id)arg1 fromView:(id)arg2 animView:(id)arg3 duration:(double)arg4 didFinish:(CDUnknownBlockType)arg5;
+ (void)flyView:(id)arg1 fromView:(id)arg2 image:(id)arg3 alpha:(double)arg4 duration:(double)arg5 didFinish:(CDUnknownBlockType)arg6;
+ (void)flyView:(id)arg1 fromView:(id)arg2 image:(id)arg3 didFinish:(CDUnknownBlockType)arg4;
+ (id)imageWithView:(id)arg1;
+ (id)getInvalidatePassengerPinYingTipInfo:(id)arg1 isInland:(_Bool)arg2;
+ (id)duplicateArrayWithSelectedArray:(id)arg1 newSelectNode:(id)arg2 withDepartDate:(id)arg3 isOnlyCheckSelected:(_Bool)arg4;
+ (id)duplicateIDCardNoMessageWithPassengerArray:(id)arg1 withDepartDate:(id)arg2 isInland:(_Bool)arg3;
+ (id)allDuplicateIDCardNoGroupWithPassengerArray:(id)arg1 withDepartDate:(id)arg2;
+ (_Bool)validatePassengerSameCertNum:(id)arg1 withDepartDate:(id)arg2;
+ (void)saveTaxGuideViewShowStatus;
+ (_Bool)needsShowTaxGuideView;
+ (void)saveTravelerEligibilityGuideViewShowStatus;
+ (_Bool)needsShowTravelerEligibilityGuideView;
+ (void)setLastOrderPersonNodes:(id)arg1 lastPersonType:(int)arg2;
+ (id)getLastOrderPersonNodes:(id)arg1 eFlightServiceAreaType:(int)arg2;
+ (_Bool)isHongKongOrMacauCity:(id)arg1;
+ (_Bool)isTaiWanCity:(id)arg1;
+ (void)gotoRootViewWithIndex:(int)arg1 formViewController:(id)arg2 needDisappearAction:(_Bool)arg3;
+ (void)gotoRootViewWithIndex:(int)arg1 formViewController:(id)arg2 needDisappearAction:(_Bool)arg3 action:(_Bool)arg4;
+ (id)getViewControllerWithClass:(Class)arg1 formViewController:(id)arg2;
+ (id)insertLineBreakToString:(id)arg1 chineseCharacterNumber:(long long)arg2;
+ (id)createImageWithColor:(id)arg1;
+ (struct CGSize)ceilfSize:(struct CGSize)arg1;

@end

