//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CTViewModel.h"

@class CTBasicDescriptionViewModel;

@interface CTFlightPurchaseExplainViewModel : CTViewModel
{
    CTBasicDescriptionViewModel *_buyLimitDescModel;
    CTBasicDescriptionViewModel *_choicenessClassDescModel;
    CTBasicDescriptionViewModel *_insuranceDescription;
    CTBasicDescriptionViewModel *_kClassDescription;
    CTBasicDescriptionViewModel *_packageDescription;
    CTBasicDescriptionViewModel *_hxPayDesc;
    CTBasicDescriptionViewModel *_hxIsWhatDesc;
    CTBasicDescriptionViewModel *_hxFeatureDesc;
    CTBasicDescriptionViewModel *_hxAttentionDesc;
    CTBasicDescriptionViewModel *_invoiceDesc;
    CTBasicDescriptionViewModel *_waitingOrderDesc;
    CTBasicDescriptionViewModel *_bundleSaleDesc;
}

@property(retain, nonatomic) CTBasicDescriptionViewModel *bundleSaleDesc; // @synthesize bundleSaleDesc=_bundleSaleDesc;
@property(retain, nonatomic) CTBasicDescriptionViewModel *waitingOrderDesc; // @synthesize waitingOrderDesc=_waitingOrderDesc;
@property(retain, nonatomic) CTBasicDescriptionViewModel *invoiceDesc; // @synthesize invoiceDesc=_invoiceDesc;
@property(retain, nonatomic) CTBasicDescriptionViewModel *hxAttentionDesc; // @synthesize hxAttentionDesc=_hxAttentionDesc;
@property(retain, nonatomic) CTBasicDescriptionViewModel *hxFeatureDesc; // @synthesize hxFeatureDesc=_hxFeatureDesc;
@property(retain, nonatomic) CTBasicDescriptionViewModel *hxIsWhatDesc; // @synthesize hxIsWhatDesc=_hxIsWhatDesc;
@property(retain, nonatomic) CTBasicDescriptionViewModel *hxPayDesc; // @synthesize hxPayDesc=_hxPayDesc;
@property(retain, nonatomic) CTBasicDescriptionViewModel *packageDescription; // @synthesize packageDescription=_packageDescription;
@property(retain, nonatomic) CTBasicDescriptionViewModel *kClassDescription; // @synthesize kClassDescription=_kClassDescription;
@property(retain, nonatomic) CTBasicDescriptionViewModel *insuranceDescription; // @synthesize insuranceDescription=_insuranceDescription;
@property(retain, nonatomic) CTBasicDescriptionViewModel *choicenessClassDescModel; // @synthesize choicenessClassDescModel=_choicenessClassDescModel;
@property(retain, nonatomic) CTBasicDescriptionViewModel *buyLimitDescModel; // @synthesize buyLimitDescModel=_buyLimitDescModel;
- (void).cxx_destruct;
- (void)initData;
- (id)init;

@end

