//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CTHotelBaseCell.h"

@class CTHotelFilterCommonView;

@interface CTHotelCommentFilterBtnCell : CTHotelBaseCell
{
    CTHotelFilterCommonView *_commomView;
}

@property(retain, nonatomic) CTHotelFilterCommonView *commomView; // @synthesize commomView=_commomView;
- (void).cxx_destruct;
- (void)initView;

@end

