//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CTCacheBean.h"

@class HotelCommentSearchRequest, HotelModuleConfigGetter, NSMutableArray, NSString;

@interface CTHotelCommentBaseCacheBean : CTCacheBean
{
    _Bool _hasMoreComment;
    int _hotelID;
    int _hotelDataType;
    int _commentTotal;
    int _nextPageExpiredType;
    HotelCommentSearchRequest *_lastRequest;
    HotelCommentSearchRequest *_lastSuccessRequest;
    NSMutableArray *_commentList;
    NSString *_hotelName;
    HotelModuleConfigGetter *_hotelModuleConfigGetter;
    NSString *_orderId;
}

@property(retain, nonatomic) NSString *orderId; // @synthesize orderId=_orderId;
@property(retain, nonatomic) HotelModuleConfigGetter *hotelModuleConfigGetter; // @synthesize hotelModuleConfigGetter=_hotelModuleConfigGetter;
@property(copy, nonatomic) NSString *hotelName; // @synthesize hotelName=_hotelName;
@property(retain, nonatomic) NSMutableArray *commentList; // @synthesize commentList=_commentList;
@property(nonatomic) int nextPageExpiredType; // @synthesize nextPageExpiredType=_nextPageExpiredType;
@property(nonatomic) int commentTotal; // @synthesize commentTotal=_commentTotal;
@property(nonatomic) _Bool hasMoreComment; // @synthesize hasMoreComment=_hasMoreComment;
@property(nonatomic) int hotelDataType; // @synthesize hotelDataType=_hotelDataType;
@property(nonatomic) int hotelID; // @synthesize hotelID=_hotelID;
@property(retain, nonatomic) HotelCommentSearchRequest *lastSuccessRequest; // @synthesize lastSuccessRequest=_lastSuccessRequest;
@property(retain, nonatomic) HotelCommentSearchRequest *lastRequest; // @synthesize lastRequest=_lastRequest;
- (void).cxx_destruct;
- (void)initCache;

@end

