//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CTLogUtil : NSObject
{
}

+ (void)logCode:(id)arg1 userInfo:(id)arg2;
+ (void)logMonitor:(id)arg1 value:(id)arg2 userInfo:(id)arg3;
+ (void)logMetrics:(id)arg1 value:(id)arg2 userInfo:(id)arg3;
+ (void)wsLog:(id)arg1;
+ (void)wsLogWarning:(id)arg1;
+ (void)wsUBT:(id)arg1 message:(id)arg2;
+ (void)wsLogError:(id)arg1;
+ (void)logRealtimeTrace:(id)arg1 userInfo:(id)arg2;
+ (void)logTrace:(id)arg1 userInfo:(id)arg2;

@end

