//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface CTPayAdPayController : NSObject
{
    _Bool _isAdPayViewClicked;
    _Bool _isRecommendPayWay;
    _Bool _isAliMaintain;
    _Bool _isWechatMaintain;
    _Bool _isBDMaintain;
    _Bool _isApplePayMaintain;
    _Bool _isIouPayMaintain;
    _Bool _isQQWalletMaintain;
    long long _defaultPayWay;
    NSMutableArray *_cellArr;
    NSString *_recommendText;
    unsigned long long _recommendCategory;
    NSString *_recommendBrandID;
    long long _recommendCardInfoID;
    long long _recommendStatus;
    unsigned long long _paymentMode;
    NSMutableArray *_bankListOfDebit;
    NSMutableArray *_bankListOfCredit;
    NSMutableArray *_bankListOfUsed;
    NSMutableArray *_bankOfOverseaAll;
}

@property(retain, nonatomic) NSMutableArray *bankOfOverseaAll; // @synthesize bankOfOverseaAll=_bankOfOverseaAll;
@property(retain, nonatomic) NSMutableArray *bankListOfUsed; // @synthesize bankListOfUsed=_bankListOfUsed;
@property(retain, nonatomic) NSMutableArray *bankListOfCredit; // @synthesize bankListOfCredit=_bankListOfCredit;
@property(retain, nonatomic) NSMutableArray *bankListOfDebit; // @synthesize bankListOfDebit=_bankListOfDebit;
@property(nonatomic) unsigned long long paymentMode; // @synthesize paymentMode=_paymentMode;
@property(nonatomic) _Bool isQQWalletMaintain; // @synthesize isQQWalletMaintain=_isQQWalletMaintain;
@property(nonatomic) _Bool isIouPayMaintain; // @synthesize isIouPayMaintain=_isIouPayMaintain;
@property(nonatomic) _Bool isApplePayMaintain; // @synthesize isApplePayMaintain=_isApplePayMaintain;
@property(nonatomic) _Bool isBDMaintain; // @synthesize isBDMaintain=_isBDMaintain;
@property(nonatomic) _Bool isWechatMaintain; // @synthesize isWechatMaintain=_isWechatMaintain;
@property(nonatomic) _Bool isAliMaintain; // @synthesize isAliMaintain=_isAliMaintain;
@property(nonatomic) _Bool isRecommendPayWay; // @synthesize isRecommendPayWay=_isRecommendPayWay;
@property(nonatomic) _Bool isAdPayViewClicked; // @synthesize isAdPayViewClicked=_isAdPayViewClicked;
@property(nonatomic) long long recommendStatus; // @synthesize recommendStatus=_recommendStatus;
@property(nonatomic) long long recommendCardInfoID; // @synthesize recommendCardInfoID=_recommendCardInfoID;
@property(copy, nonatomic) NSString *recommendBrandID; // @synthesize recommendBrandID=_recommendBrandID;
@property(nonatomic) unsigned long long recommendCategory; // @synthesize recommendCategory=_recommendCategory;
@property(copy, nonatomic) NSString *recommendText; // @synthesize recommendText=_recommendText;
@property(retain, nonatomic) NSMutableArray *cellArr; // @synthesize cellArr=_cellArr;
@property(nonatomic) long long defaultPayWay; // @synthesize defaultPayWay=_defaultPayWay;
- (void).cxx_destruct;
- (void)changeRecommendPayTypeWithCompleted:(CDUnknownBlockType)arg1;
- (id)getRecommendNewCard;
- (id)getRecommendUsedCard;
- (_Bool)isAdPayViewShow;
- (CDUnknownBlockType)setAdPayDefaultPayWay;
- (CDUnknownBlockType)setAdPayPaymentMode;
- (CDUnknownBlockType)setAdPayCacheBeanParams;

@end

