//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CTSerialize : NSObject
{
}

+ (id)serialize:(id)arg1 EncodingCode:(unsigned long long)arg2;
+ (id)deserialize:(id)arg1 ClassType:(Class)arg2 EncodingCode:(unsigned long long)arg3;

@end

