//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CTSCustomActionCell.h"

@class CTImageView, CTVectorImageView, NSLayoutConstraint, UIButton, UILabel, UIView;

@interface CTSTeamCell : CTSCustomActionCell
{
    UIView *_realContentView;
    UILabel *_titleLabel;
    CTImageView *_firstImageView;
    CTImageView *_secondImageView;
    CTImageView *_thirdImageView;
    CTImageView *_fourthImageView;
    UILabel *_statusLabel;
    CTVectorImageView *_statusImageView;
    NSLayoutConstraint *_statusviewHeightConstraint;
    UIButton *_orderServiceButton;
    UIView *_statusView;
    UIView *_imageContentView;
    NSLayoutConstraint *_imageContentViewHeightConstraint;
    NSLayoutConstraint *_topConstraint;
}

@property(nonatomic) __weak NSLayoutConstraint *topConstraint; // @synthesize topConstraint=_topConstraint;
@property(nonatomic) __weak NSLayoutConstraint *imageContentViewHeightConstraint; // @synthesize imageContentViewHeightConstraint=_imageContentViewHeightConstraint;
@property(nonatomic) __weak UIView *imageContentView; // @synthesize imageContentView=_imageContentView;
@property(nonatomic) __weak UIView *statusView; // @synthesize statusView=_statusView;
@property(nonatomic) __weak UIButton *orderServiceButton; // @synthesize orderServiceButton=_orderServiceButton;
@property(nonatomic) __weak NSLayoutConstraint *statusviewHeightConstraint; // @synthesize statusviewHeightConstraint=_statusviewHeightConstraint;
@property(nonatomic) __weak CTVectorImageView *statusImageView; // @synthesize statusImageView=_statusImageView;
@property(nonatomic) __weak UILabel *statusLabel; // @synthesize statusLabel=_statusLabel;
@property(nonatomic) __weak CTImageView *fourthImageView; // @synthesize fourthImageView=_fourthImageView;
@property(nonatomic) __weak CTImageView *thirdImageView; // @synthesize thirdImageView=_thirdImageView;
@property(nonatomic) __weak CTImageView *secondImageView; // @synthesize secondImageView=_secondImageView;
@property(nonatomic) __weak CTImageView *firstImageView; // @synthesize firstImageView=_firstImageView;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak UIView *realContentView; // @synthesize realContentView=_realContentView;
- (void).cxx_destruct;
- (_Bool)needShowStatusView;
- (_Bool)needShowOrderServiceButton;
- (id)getOperationView;
- (id)getCardStatusLabel;
- (id)getCardStatusImageView;
- (id)ctsOrderServiceButton;
- (id)getTopConstraint;
- (id)customizedContentView;
- (double)cellHeight;
- (void)setCellWithModel:(id)arg1 index:(id)arg2 delegate:(id)arg3;
- (void)showOrderServiceAction:(id)arg1;
- (void)awakeFromNib;

@end

