//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CTBusinessBean.h"

@interface FlightTagInformationModel : CTBusinessBean
{
    int tagType;
}

@property(nonatomic) int tagType; // @synthesize tagType;
- (id)getPBAnnotationArray;
- (id)init;

@end

