//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CTBusinessBean.h"

@class NSString;

@interface FlightInlandGradeDetailInformationModel : CTBusinessBean
{
    int segmentNo;
    NSString *flightNo;
    int classGrade;
    NSString *subClass;
    int classGradeIndex;
    NSString *displayClass;
    NSString *saleType;
    NSString *remark;
}

@property(copy, nonatomic) NSString *remark; // @synthesize remark;
@property(copy, nonatomic) NSString *saleType; // @synthesize saleType;
@property(copy, nonatomic) NSString *displayClass; // @synthesize displayClass;
@property(nonatomic) int classGradeIndex; // @synthesize classGradeIndex;
@property(copy, nonatomic) NSString *subClass; // @synthesize subClass;
@property(nonatomic) int classGrade; // @synthesize classGrade;
@property(copy, nonatomic) NSString *flightNo; // @synthesize flightNo;
@property(nonatomic) int segmentNo; // @synthesize segmentNo;
- (void).cxx_destruct;
- (id)getPBAnnotationArray;
- (id)init;

@end

