//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CTBusinessBean.h"

@class FlightTagContentInformationModel;

@interface FlightTagDetailInformationModel : CTBusinessBean
{
    int subTagType;
    int displayArea;
    FlightTagContentInformationModel *contentInforModel;
}

@property(retain, nonatomic) FlightTagContentInformationModel *contentInforModel; // @synthesize contentInforModel;
@property(nonatomic) int displayArea; // @synthesize displayArea;
@property(nonatomic) int subTagType; // @synthesize subTagType;
- (void).cxx_destruct;
- (id)getPBAnnotationArray;
- (id)init;

@end

