//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CTBusinessBean.h"

@class FlightInlandMiddleSalePolicyInformationModel, NSMutableArray, NSString;

@interface FlightInlandMiddleBasicPolicyInformationModel : CTBusinessBean
{
    long long flag;
    _Bool defaultShow;
    int defaultShowWeight;
    int moreShowWeight;
    NSMutableArray *gradesList;
    NSString *gradesDisplayName;
    NSString *gradeDescription;
    int isHighLight;
    NSString *gradesFillDisplayName;
    int quantity;
    NSMutableArray *priceList;
    int buttonRemarkIndex;
    FlightInlandMiddleSalePolicyInformationModel *salePolicyInfoModel;
}

@property(retain, nonatomic) FlightInlandMiddleSalePolicyInformationModel *salePolicyInfoModel; // @synthesize salePolicyInfoModel;
@property(nonatomic) int buttonRemarkIndex; // @synthesize buttonRemarkIndex;
@property(retain, nonatomic) NSMutableArray *priceList; // @synthesize priceList;
@property(nonatomic) int quantity; // @synthesize quantity;
@property(copy, nonatomic) NSString *gradesFillDisplayName; // @synthesize gradesFillDisplayName;
@property(nonatomic) int isHighLight; // @synthesize isHighLight;
@property(copy, nonatomic) NSString *gradeDescription; // @synthesize gradeDescription;
@property(copy, nonatomic) NSString *gradesDisplayName; // @synthesize gradesDisplayName;
@property(retain, nonatomic) NSMutableArray *gradesList; // @synthesize gradesList;
@property(nonatomic) int moreShowWeight; // @synthesize moreShowWeight;
@property(nonatomic) int defaultShowWeight; // @synthesize defaultShowWeight;
@property(nonatomic) _Bool defaultShow; // @synthesize defaultShow;
@property(nonatomic) long long flag; // @synthesize flag;
- (void).cxx_destruct;
- (id)getPBAnnotationArray;
- (id)init;

@end

