//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CTBusinessBean.h"

@class NSString;

@interface HotelCustomeRemarkModel : CTBusinessBean
{
    _Bool _isSelected;
    int _optionType;
    NSString *_key;
    NSString *_remarkId;
    NSString *_title;
    NSString *_hotelDescription;
    NSString *_displayTitle;
}

@property(nonatomic) _Bool isSelected; // @synthesize isSelected=_isSelected;
@property(nonatomic) int optionType; // @synthesize optionType=_optionType;
@property(copy, nonatomic) NSString *displayTitle; // @synthesize displayTitle=_displayTitle;
@property(copy, nonatomic) NSString *hotelDescription; // @synthesize hotelDescription=_hotelDescription;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *remarkId; // @synthesize remarkId=_remarkId;
@property(copy, nonatomic) NSString *key; // @synthesize key=_key;
- (void).cxx_destruct;
- (id)getPBAnnotationArray;
- (id)init;

@end

