//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CTBusinessBean.h"

@class NSMutableArray, NSString;

@interface HotelFilterListRequest : CTBusinessBean
{
    int _serviceVersion;
    int _cityID;
    int _distinctID;
    int _countryType;
    int _dataFor;
    NSString *_checkInDate;
    NSString *_checkOutDate;
    NSMutableArray *_coordinateList;
}

@property(retain, nonatomic) NSMutableArray *coordinateList; // @synthesize coordinateList=_coordinateList;
@property(nonatomic) int dataFor; // @synthesize dataFor=_dataFor;
@property(copy, nonatomic) NSString *checkOutDate; // @synthesize checkOutDate=_checkOutDate;
@property(copy, nonatomic) NSString *checkInDate; // @synthesize checkInDate=_checkInDate;
@property(nonatomic) int countryType; // @synthesize countryType=_countryType;
@property(nonatomic) int distinctID; // @synthesize distinctID=_distinctID;
@property(nonatomic) int cityID; // @synthesize cityID=_cityID;
@property(nonatomic) int serviceVersion; // @synthesize serviceVersion=_serviceVersion;
- (void).cxx_destruct;
- (id)getPBAnnotationArray;
- (id)init;

@end

