//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XMPPElement.h"

@interface XMPPMessage : XMPPElement
{
}

+ (id)messageWithType:(id)arg1 child:(id)arg2;
+ (id)messageWithType:(id)arg1 elementID:(id)arg2 child:(id)arg3;
+ (id)messageWithType:(id)arg1 elementID:(id)arg2;
+ (id)messageWithType:(id)arg1 to:(id)arg2 elementID:(id)arg3 child:(id)arg4;
+ (id)messageWithType:(id)arg1 to:(id)arg2 elementID:(id)arg3;
+ (id)messageWithType:(id)arg1 to:(id)arg2;
+ (id)messageWithType:(id)arg1;
+ (id)message;
+ (id)messageFromElement:(id)arg1;
- (_Bool)isSendResult;
- (_Bool)isDelayMessage;
- (_Bool)isMessageWithBody;
- (id)errorMessage;
- (_Bool)isErrorMessage;
- (_Bool)isChatMessageWithBody;
- (_Bool)isChatMessage;
- (void)addThread:(id)arg1;
- (void)addBody:(id)arg1 withLanguage:(id)arg2;
- (void)addBody:(id)arg1;
- (void)addSubject:(id)arg1;
- (id)thread;
- (id)bodyForLanguage:(id)arg1;
- (id)body;
- (id)subject;
- (id)type;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithXMLString:(id)arg1 error:(id *)arg2;
- (id)initWithType:(id)arg1 child:(id)arg2;
- (id)initWithType:(id)arg1 elementID:(id)arg2 child:(id)arg3;
- (id)initWithType:(id)arg1 elementID:(id)arg2;
- (id)initWithType:(id)arg1 to:(id)arg2 elementID:(id)arg3 child:(id)arg4;
- (id)initWithType:(id)arg1 to:(id)arg2 elementID:(id)arg3;
- (id)initWithType:(id)arg1 to:(id)arg2;
- (id)initWithType:(id)arg1;
- (id)init;
- (void)setChatMessageLogTime:(id)arg1;
- (id)chatMessageLogTime;
- (_Bool)isGroupChatMessageWithSubject;
- (_Bool)isGroupChatMessageWithBody;
- (_Bool)isGroupChatMessage;
- (void)addReceiptRequest;
- (id)generateReceiptResponse;
- (id)receiptResponseID;
- (_Bool)hasReceiptResponse;
- (_Bool)hasReceiptRequest;
- (id)nick;
- (void)addGoneChatState;
- (void)addInactiveChatState;
- (void)addPausedChatState;
- (void)addComposingChatState;
- (void)addActiveChatState;
- (_Bool)hasGoneChatState;
- (_Bool)hasInactiveChatState;
- (_Bool)hasPausedChatState;
- (_Bool)hasComposingChatState;
- (_Bool)hasActiveChatState;
- (_Bool)hasChatState;
- (id)chatState;
- (id)outOfBandDesc;
- (id)outOfBandURI;
- (id)outOfBandURL;
- (_Bool)hasOutOfBandData;
- (void)addOutOfBandURI:(id)arg1 desc:(id)arg2;
- (void)addOutOfBandURL:(id)arg1 desc:(id)arg2;
- (_Bool)isGroupChatSysMsg;
- (_Bool)isChatSysMsg;
- (id)systemTip;
- (id)threadId;
- (id)msgType;
- (long long)bizType;
- (_Bool)isGroupResponseToMe;
- (_Bool)isMUCConfigUpdate;
- (_Bool)isDismissMessage;
- (_Bool)isInviteMessage;
- (_Bool)isKickMessage;

@end

