//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AUToast, DTRpcAsyncCaller;

@interface AFStockMangerUtils : NSObject
{
    DTRpcAsyncCaller *_caller;
    AUToast *_toast;
}

+ (void)pushAccountVerifyPage;
+ (void)pushAddAccountPage;
+ (void)pushAccountCenter;
+ (void)pushInstTrade:(id)arg1 sceneType:(id)arg2;
+ (id)sharedInstance;
@property(retain, nonatomic) AUToast *toast; // @synthesize toast=_toast;
@property(retain, nonatomic) DTRpcAsyncCaller *caller; // @synthesize caller=_caller;
- (void).cxx_destruct;
- (void)successJump:(id)arg1 stockParam:(id)arg2 sceneType:(id)arg3;
- (id)lastControllerView;
- (void)loadModel:(id)arg1 sceneType:(id)arg2;

@end

