//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface APDataCenterInterface : NSObject
{
}

+ (id)sharedInstance;
- (id)launchingFinishNotificationName;
- (void)writePerformanceLog:(id)arg1;
- (void)writeRemoteLog:(id)arg1;
- (void)writeLocalFileLog:(id)arg1;
- (_Bool)setDefaultCryptKey:(CDUnknownFunctionPointerType)arg1;
- (void)writeLocalFileLog:(id)arg1;
- (id)launchingFinishNotificationName;
- (_Bool)setDefaultCryptKey:(CDUnknownFunctionPointerType)arg1;

@end

