//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface APScanAREUtil : NSObject
{
}

+ (id)colorWithRGBString:(id)arg1;
+ (void)gotoCocacolaLicenseLink;
+ (id)presentErrorAlertInView:(id)arg1 text:(id)arg2 complete:(CDUnknownBlockType)arg3;
+ (id)presentInitAlertInView:(id)arg1 logo:(id)arg2 text:(id)arg3 complete:(CDUnknownBlockType)arg4;
+ (void)showTestToast:(id)arg1;

@end

