//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APShareServiceCardView.h"

@class APShareServiceImageView, UILabel;

@interface APShareServiceCardGoodsView : APShareServiceCardView
{
    APShareServiceImageView *_imageView;
    UILabel *_title;
    UILabel *_desc;
    UILabel *_tips;
}

@property(retain, nonatomic) UILabel *tips; // @synthesize tips=_tips;
@property(retain, nonatomic) UILabel *desc; // @synthesize desc=_desc;
@property(retain, nonatomic) UILabel *title; // @synthesize title=_title;
@property(retain, nonatomic) APShareServiceImageView *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
- (void)reloadImageView;
- (double)refreshCard:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

