//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString, UIColor;

@interface APWealthBankCardColorCell : NSObject
{
    NSString *_bankCardID;
    NSArray *_gradientColor;
    UIColor *_singleColor;
}

@property(retain, nonatomic) UIColor *singleColor; // @synthesize singleColor=_singleColor;
@property(retain, nonatomic) NSArray *gradientColor; // @synthesize gradientColor=_gradientColor;
@property(retain, nonatomic) NSString *bankCardID; // @synthesize bankCardID=_bankCardID;
- (void).cxx_destruct;

@end

