//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AUImageDialog.h"

@interface ARAlertView : AUImageDialog
{
    CDUnknownBlockType _cancelCallback;
    CDUnknownBlockType _confirmCallback;
}

+ (id)showAlertViewWithTitle:(id)arg1 message:(id)arg2 cancelButtonTitle:(id)arg3 confirmButtonTitle:(id)arg4 cancelCallback:(CDUnknownBlockType)arg5 confirmCallback:(CDUnknownBlockType)arg6;
@property(copy, nonatomic) CDUnknownBlockType confirmCallback; // @synthesize confirmCallback=_confirmCallback;
@property(copy, nonatomic) CDUnknownBlockType cancelCallback; // @synthesize cancelCallback=_cancelCallback;
- (void).cxx_destruct;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)dealloc;

@end

