//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CCRBaseRespVO.h"

@class NSArray, NSString;

@interface CCRCreditCardInitRespVO : CCRBaseRespVO
{
    _Bool _hasNext;
    NSArray *_savedCardList;
    NSArray *_bankAndCardBinList;
    NSString *_bankAndCardBinVersion;
}

+ (Class)bankAndCardBinListElementClass;
+ (Class)savedCardListElementClass;
@property(nonatomic) _Bool hasNext; // @synthesize hasNext=_hasNext;
@property(retain, nonatomic) NSString *bankAndCardBinVersion; // @synthesize bankAndCardBinVersion=_bankAndCardBinVersion;
@property(retain, nonatomic) NSArray *bankAndCardBinList; // @synthesize bankAndCardBinList=_bankAndCardBinList;
@property(retain, nonatomic) NSArray *savedCardList; // @synthesize savedCardList=_savedCardList;
- (void).cxx_destruct;

@end

