//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APDPBGeneratedMessage.h"

@class COMFeed, NSString;

@interface COMPublishFeedResp : APDPBGeneratedMessage
{
}

+ (CDStruct_af61540b *)_fieldInfos;

// Remaining properties
@property(readonly) _Bool hasMemo; // @dynamic hasMemo;
@property(readonly) _Bool hasMockFeed; // @dynamic hasMockFeed;
@property(readonly) _Bool hasResultStatus; // @dynamic hasResultStatus;
@property(readonly) _Bool hasRetry; // @dynamic hasRetry;
@property(retain, nonatomic) NSString *memo; // @dynamic memo;
@property(retain, nonatomic) COMFeed *mockFeed; // @dynamic mockFeed;
@property(retain, nonatomic) NSString *resultStatus; // @dynamic resultStatus;
@property(nonatomic) _Bool retry; // @dynamic retry;

@end

