//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "EWBaseSectionDelegate.h"

#import "EWHorizontalScrollMenuDelegate.h"

@class EWCategoryMenuView, EWMainPageViewController, EWMainPageViewModel, NSMutableDictionary, NSString;

@interface EWCategoryMenuDelegate : EWBaseSectionDelegate <EWHorizontalScrollMenuDelegate>
{
    EWMainPageViewController *_vc;
    EWCategoryMenuView *_categoryMenuView;
    NSMutableDictionary *_subCategoryGroupDic;
}

@property(retain, nonatomic) NSMutableDictionary *subCategoryGroupDic; // @synthesize subCategoryGroupDic=_subCategoryGroupDic;
@property(retain, nonatomic) EWCategoryMenuView *categoryMenuView; // @synthesize categoryMenuView=_categoryMenuView;
@property(nonatomic) __weak EWMainPageViewController *vc; // @synthesize vc=_vc;
- (void).cxx_destruct;
- (void)clickedMoreButton:(id)arg1;
- (void)clickedMenu:(id)arg1;
- (_Bool)hasData;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)dealloc;
- (id)initWithViewModel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(retain, nonatomic) EWMainPageViewModel *viewModel;

@end

