//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "KABAOPRODToString.h"

@class NSString;

@interface KABAOPRODPresentPassReq : KABAOPRODToString
{
    int _presentChannel;
    NSString *_relationId;
    NSString *_passId;
    NSString *_receiveUserId;
    NSString *_password;
    NSString *_passwordType;
    NSString *_token;
    NSString *_uuid;
    NSString *_message;
}

@property(retain, nonatomic) NSString *message; // @synthesize message=_message;
@property(retain, nonatomic) NSString *uuid; // @synthesize uuid=_uuid;
@property(retain, nonatomic) NSString *token; // @synthesize token=_token;
@property(retain, nonatomic) NSString *passwordType; // @synthesize passwordType=_passwordType;
@property(retain, nonatomic) NSString *password; // @synthesize password=_password;
@property(retain, nonatomic) NSString *receiveUserId; // @synthesize receiveUserId=_receiveUserId;
@property(nonatomic) int presentChannel; // @synthesize presentChannel=_presentChannel;
@property(retain, nonatomic) NSString *passId; // @synthesize passId=_passId;
@property(retain, nonatomic) NSString *relationId; // @synthesize relationId=_relationId;
- (void).cxx_destruct;

@end

