//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "KBCONTENTToString.h"

@class KBCONTENTItemInfo, NSArray, NSString;

@interface KBCONTENTShopBriefInfo : KBCONTENTToString
{
    _Bool _collected;
    NSString *_id;
    NSString *_name;
    NSString *_logoUrl;
    NSString *_starLevel;
    NSString *_avgScore;
    NSString *_distance;
    NSString *_perPay;
    double _longitude;
    double _latitude;
    NSString *_cityId;
    NSString *_cityName;
    NSString *_districtId;
    NSString *_districtName;
    NSString *_cuisine;
    NSString *_bizCircle;
    NSString *_discount;
    NSString *_discountUint;
    NSString *_firstPromotionIcon;
    NSString *_promotionInfo;
    NSArray *_promotionIconList;
    NSString *_shopMarkTag;
    KBCONTENTItemInfo *_couponInfo;
}

+ (Class)promotionIconListElementClass;
@property(retain, nonatomic) KBCONTENTItemInfo *couponInfo; // @synthesize couponInfo=_couponInfo;
@property(retain, nonatomic) NSString *shopMarkTag; // @synthesize shopMarkTag=_shopMarkTag;
@property(retain, nonatomic) NSArray *promotionIconList; // @synthesize promotionIconList=_promotionIconList;
@property(retain, nonatomic) NSString *promotionInfo; // @synthesize promotionInfo=_promotionInfo;
@property(retain, nonatomic) NSString *firstPromotionIcon; // @synthesize firstPromotionIcon=_firstPromotionIcon;
@property(retain, nonatomic) NSString *discountUint; // @synthesize discountUint=_discountUint;
@property(retain, nonatomic) NSString *discount; // @synthesize discount=_discount;
@property(nonatomic) _Bool collected; // @synthesize collected=_collected;
@property(retain, nonatomic) NSString *bizCircle; // @synthesize bizCircle=_bizCircle;
@property(retain, nonatomic) NSString *cuisine; // @synthesize cuisine=_cuisine;
@property(retain, nonatomic) NSString *districtName; // @synthesize districtName=_districtName;
@property(retain, nonatomic) NSString *districtId; // @synthesize districtId=_districtId;
@property(retain, nonatomic) NSString *cityName; // @synthesize cityName=_cityName;
@property(retain, nonatomic) NSString *cityId; // @synthesize cityId=_cityId;
@property(nonatomic) double latitude; // @synthesize latitude=_latitude;
@property(nonatomic) double longitude; // @synthesize longitude=_longitude;
@property(retain, nonatomic) NSString *perPay; // @synthesize perPay=_perPay;
@property(retain, nonatomic) NSString *distance; // @synthesize distance=_distance;
@property(retain, nonatomic) NSString *avgScore; // @synthesize avgScore=_avgScore;
@property(retain, nonatomic) NSString *starLevel; // @synthesize starLevel=_starLevel;
@property(retain, nonatomic) NSString *logoUrl; // @synthesize logoUrl=_logoUrl;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *id; // @synthesize id=_id;
- (void).cxx_destruct;

@end

