//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class AUFloatMenu, ButtonObject, MenuItemView, NSArray, NSString, UIActivityIndicatorView;

@interface LFMenuView : UIView
{
    _Bool _msgSwitchOn;
    _Bool _isFollow;
    NSString *_publicId;
    NSArray *_menuInfos;
    ButtonObject *_showMenuItemInfo;
    MenuItemView *_showMenuItemView;
    UIActivityIndicatorView *_indicatorView;
    AUFloatMenu *_floatMenu;
    double _oriHeight;
}

@property(nonatomic) double oriHeight; // @synthesize oriHeight=_oriHeight;
@property(nonatomic) _Bool isFollow; // @synthesize isFollow=_isFollow;
@property(nonatomic) _Bool msgSwitchOn; // @synthesize msgSwitchOn=_msgSwitchOn;
@property(retain, nonatomic) AUFloatMenu *floatMenu; // @synthesize floatMenu=_floatMenu;
@property(retain, nonatomic) UIActivityIndicatorView *indicatorView; // @synthesize indicatorView=_indicatorView;
@property(retain, nonatomic) MenuItemView *showMenuItemView; // @synthesize showMenuItemView=_showMenuItemView;
@property(retain, nonatomic) ButtonObject *showMenuItemInfo; // @synthesize showMenuItemInfo=_showMenuItemInfo;
@property(retain, nonatomic) NSArray *menuInfos; // @synthesize menuInfos=_menuInfos;
@property(retain, nonatomic) NSString *publicId; // @synthesize publicId=_publicId;
- (void).cxx_destruct;
- (void)followStateChanged:(id)arg1;
- (void)handlePushSwitchChangedNotification:(id)arg1;
- (void)menuViewSelectedForRow:(long long)arg1;
- (void)menuButtonClicked:(id)arg1 buttonView:(id)arg2;
- (id)createImageWithColor:(id)arg1;
- (void)menuItemUpInside:(id)arg1;
- (void)updateBadgeView:(id)arg1;
- (id)unreadCount;
- (id)refreshMenuView:(id)arg1;
- (void)chatMessage:(id)arg1;
- (void)dealloc;
- (void)addObserveNotifications;
- (id)seperateLine:(double)arg1;
- (void)addBottomLine;
- (id)initWithFrame:(struct CGRect)arg1 lifeInfo:(id)arg2;

@end

