//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface MACoreDataGridList : NSObject
{
    NSMutableDictionary *_gridDic;
}

+ (id)sharedGridlist;
- (void).cxx_destruct;
- (void)removeTileWithTileName:(id)arg1 dataSource:(int)arg2 index:(long long)arg3;
- (_Bool)isGridProcessingWithTileName:(id)arg1 dataSource:(int)arg2 index:(long long)arg3;
- (id)init;

@end

