//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MOBILEBILLQueryContactBaseReq.h"

@class NSArray, NSDictionary, NSString;

@interface MOBILEBILLQueryContactDataReq : MOBILEBILLQueryContactBaseReq
{
    int _pageNum;
    int _pageSize;
    int _apiVersion;
    NSString *_filter;
    long long _startTime;
    NSDictionary *_extendField;
    NSArray *_bizSubtypes;
}

+ (Class)bizSubtypesElementClass;
+ (Class)extendFieldElementClass;
@property(retain, nonatomic) NSArray *bizSubtypes; // @synthesize bizSubtypes=_bizSubtypes;
@property(retain, nonatomic) NSDictionary *extendField; // @synthesize extendField=_extendField;
@property(nonatomic) int apiVersion; // @synthesize apiVersion=_apiVersion;
@property(nonatomic) int pageSize; // @synthesize pageSize=_pageSize;
@property(nonatomic) int pageNum; // @synthesize pageNum=_pageNum;
@property(nonatomic) long long startTime; // @synthesize startTime=_startTime;
@property(retain, nonatomic) NSString *filter; // @synthesize filter=_filter;
- (void).cxx_destruct;

@end

