//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewFlowLayout.h"

@interface MVFilmListCollectionLayout : UICollectionViewFlowLayout
{
    double _leftContentPadding;
}

@property(nonatomic) double leftContentPadding; // @synthesize leftContentPadding=_leftContentPadding;
- (struct CGPoint)targetContentOffsetForProposedContentOffset:(struct CGPoint)arg1 withScrollingVelocity:(struct CGPoint)arg2;
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;
- (struct CGSize)collectionViewContentSize;
- (double)contentOffsetForItemAtIndex:(unsigned long long)arg1;
- (void)setItemSize:(struct CGSize)arg1;
- (id)init;

@end

