//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APPBGeneratedMessage.h"

#import "GeneratedMessageProtocol.h"

@class NSMutableArray, NSString;

@interface O2OSearchMenuInfoPB : APPBGeneratedMessage <GeneratedMessageProtocol>
{
    _Bool _hasCode;
    _Bool _hasName;
    _Bool _hasDname;
    _Bool _hasCount;
    _Bool _hasStyle;
    _Bool _hasOrder;
    _Bool _hasConfig;
    _Bool _hasIsSelected;
    _Bool _isSelected;
    int _count;
    int _order;
    NSString *_code;
    NSString *_name;
    NSString *_dname;
    NSString *_style;
    NSMutableArray *_icons;
    NSMutableArray *_subMenuInfos;
    NSString *_config;
}

+ (id)parseFromData:(id)arg1;
@property(nonatomic) _Bool isSelected; // @synthesize isSelected=_isSelected;
@property(retain, nonatomic) NSString *config; // @synthesize config=_config;
@property(retain, nonatomic) NSMutableArray *subMenuInfos; // @synthesize subMenuInfos=_subMenuInfos;
@property(retain, nonatomic) NSMutableArray *icons; // @synthesize icons=_icons;
@property(nonatomic) int order; // @synthesize order=_order;
@property(retain, nonatomic) NSString *style; // @synthesize style=_style;
@property(nonatomic) int count; // @synthesize count=_count;
@property(retain, nonatomic) NSString *dname; // @synthesize dname=_dname;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *code; // @synthesize code=_code;
@property(readonly) _Bool hasIsSelected; // @synthesize hasIsSelected=_hasIsSelected;
@property(readonly) _Bool hasConfig; // @synthesize hasConfig=_hasConfig;
@property(readonly) _Bool hasOrder; // @synthesize hasOrder=_hasOrder;
@property(readonly) _Bool hasStyle; // @synthesize hasStyle=_hasStyle;
@property(readonly) _Bool hasCount; // @synthesize hasCount=_hasCount;
@property(readonly) _Bool hasDname; // @synthesize hasDname=_hasDname;
@property(readonly) _Bool hasName; // @synthesize hasName=_hasName;
@property(readonly) _Bool hasCode; // @synthesize hasCode=_hasCode;
- (void).cxx_destruct;
- (void)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
- (void)addSubMenuInfos:(id)arg1;
- (void)setSubMenuInfosArray:(id)arg1;
- (void)addIcons:(id)arg1;
- (void)setIconsArray:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

