//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class CAGradientLayer, NSArray, UIColor, UIImage, UIImageView;

@interface OSPTabBar : UIControl
{
    long long _itemCount;
    struct CGSize _itemSize;
    long long _selectIndex;
    id <OSPTabBarDelegate> _delegate;
    UIColor *_titleColor;
    UIColor *_selectTitleColor;
    UIImageView *_bgImageView;
    UIImage *_backgroundImage;
    NSArray *_itemDataArray;
    CAGradientLayer *_gradientLayer;
}

@property(retain, nonatomic) CAGradientLayer *gradientLayer; // @synthesize gradientLayer=_gradientLayer;
@property(copy, nonatomic) NSArray *itemDataArray; // @synthesize itemDataArray=_itemDataArray;
@property(retain, nonatomic) UIImage *backgroundImage; // @synthesize backgroundImage=_backgroundImage;
@property(retain, nonatomic) UIImageView *bgImageView; // @synthesize bgImageView=_bgImageView;
@property(copy, nonatomic) UIColor *selectTitleColor; // @synthesize selectTitleColor=_selectTitleColor;
@property(copy, nonatomic) UIColor *titleColor; // @synthesize titleColor=_titleColor;
@property(nonatomic) __weak id <OSPTabBarDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)getTabArraw;
- (long long)getItemsCount;
- (void)selectItemAtIndex:(long long)arg1;
- (void)tabItemClick:(id)arg1;
- (void)createSubViews;
- (id)initWithItemTitle:(id)arg1 itemFrame:(struct CGRect)arg2 delegate:(id)arg3;

@end

