//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, UIImageView, UILabel;

@interface PPDetailUserInfoSubview : UIView
{
    _Bool _isPrevSetting;
    id <PPSubviewsDelegate> _delegate;
    UIImageView *_imgView;
    UILabel *_name;
    UILabel *_identify;
    UIImageView *_followCountImgView;
    NSString *_loginId;
    NSString *_strName;
    NSString *_followType;
}

@property(retain, nonatomic) NSString *followType; // @synthesize followType=_followType;
@property(nonatomic) _Bool isPrevSetting; // @synthesize isPrevSetting=_isPrevSetting;
@property(retain, nonatomic) NSString *strName; // @synthesize strName=_strName;
@property(retain, nonatomic) NSString *loginId; // @synthesize loginId=_loginId;
@property(retain, nonatomic) UIImageView *followCountImgView; // @synthesize followCountImgView=_followCountImgView;
@property(retain, nonatomic) UILabel *identify; // @synthesize identify=_identify;
@property(retain, nonatomic) UILabel *name; // @synthesize name=_name;
@property(retain, nonatomic) UIImageView *imgView; // @synthesize imgView=_imgView;
@property(nonatomic) __weak id <PPSubviewsDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)addLabelToView:(id)arg1 label:(id)arg2 labelProperties:(id)arg3;
- (id)labelWithFrame:(struct CGRect)arg1;
- (_Bool)isEmptyText:(id)arg1;
- (_Bool)isPrevSet:(id)arg1;
- (double)maxValue:(double)arg1 another:(double)arg2;
- (void)calculateSubviewFrameWithNameShow:(_Bool)arg1 isNotShowIdentify:(_Bool)arg2;
- (void)updateInfo:(id)arg1 name:(id)arg2 identify:(id)arg3;
- (id)defaultImageFromFollowType:(id)arg1;
- (void)setImageViewImageWithUrl:(id)arg1 width:(int)arg2 height:(int)arg3;
- (void)addRoundedCornerImageViewFromUrl:(id)arg1 frame:(struct CGRect)arg2 widthHeight:(float)arg3 raidus:(float)arg4;
- (void)roundedCornerImageView:(id)arg1 cornerRaidus:(double)arg2;
- (id)initWithParent:(id)arg1 frame:(struct CGRect)arg2;

@end

