//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DTViewController.h"

@class NSMutableArray;

@interface SCCommonBaseViewController : DTViewController
{
    NSMutableArray *_rpcCallers;
}

+ (id)makeDeleteButtonWithTitle:(id)arg1;
- (void).cxx_destruct;
- (_Bool)isTwoStringsEqual:(id)arg1 str2:(id)arg2;
- (void)showHudInView:(id)arg1 text:(id)arg2;
- (void)setRightBtnTitle:(id)arg1;
- (void)setBackBtnTitle:(id)arg1;
- (void)washRpcCallers;
- (void)cancelAllRpcCallers;
- (void)addRpcCaller:(id)arg1;
- (void)onRightBarBtnClick:(id)arg1;
- (void)privateCommonInit;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)init;

@end

