//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SpecificGroupUIFactory : NSObject
{
}

+ (id)createActivityIndicatorView;
+ (id)createButton:(struct CGRect)arg1;
+ (id)createImageView:(id)arg1;
+ (id)createLabel:(struct CGRect)arg1;
+ (id)createView:(struct CGRect)arg1;

@end

