//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SPProfileInfoRPCService : NSObject
{
}

+ (id)convert2BoolNum:(id)arg1;
+ (void)updateOldConfigModelDataWith:(id)arg1;
+ (void)mergeProfileInfo:(id)arg1 withProfile:(id)arg2 withProperties:(id)arg3;
+ (id)makeContactInfoFrom:(id)arg1;
+ (id)makeProfileInfoFrom:(id)arg1;
+ (id)makeSOUserCardFrom:(id)arg1 userId:(id)arg2 rpcDate:(long long)arg3;
+ (id)sendNoHeadImageTipMessage:(id)arg1 loginId:(id)arg2 callback:(CDUnknownBlockType)arg3;
+ (id)delelteFeed:(id)arg1 clientFeedId:(id)arg2 swallowException:(_Bool)arg3 rpcResultCallback:(CDUnknownBlockType)arg4;
+ (id)getFeedsData:(id)arg1 pageSize:(long long)arg2 lastFeedId:(id)arg3 swallowException:(_Bool)arg4 rpcResultCallback:(CDUnknownBlockType)arg5;
+ (id)profileGetDetailInfo:(id)arg1 account:(id)arg2 swallowException:(_Bool)arg3 rpcResultCallback:(CDUnknownBlockType)arg4;
+ (void)updateConfigModelWithProfileRetForPrivacyScene:(id)arg1;
+ (void)updateConfigModelAndContactInfo:(out id *)arg1 withProfileResult:(id)arg2;
+ (void)handleProfileRespWithBizType:(id)arg1 profileRet:(id)arg2 contactInfo:(out id *)arg3 profileInfo:(out id *)arg4;
+ (id)getSelfProfileInfoAsync:(_Bool)arg1 bizType:(id)arg2 resultCallback:(CDUnknownBlockType)arg3;

@end

