//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VIViewController.h"

@class NSArray, NSString, NSTimer, UIButton, VIQRCodeDescView, VIQRCodeView;

@interface VIQRCodeLoginViewController : VIViewController
{
    _Bool _hasOtherVIProduct;
    NSString *_navigationTitle;
    NSString *_mainCodeTitle;
    NSString *_qrCodeToken;
    NSArray *_descriptions;
    NSString *_otherLinkTitle;
    long long _qrcodeTimeInterval;
    VIQRCodeView *_qrCodeView;
    VIQRCodeDescView *_descriptionView;
    UIButton *_otherLink;
    NSTimer *_refreshTimer;
    double _resignActiveTime;
}

@property(nonatomic) double resignActiveTime; // @synthesize resignActiveTime=_resignActiveTime;
@property(retain, nonatomic) NSTimer *refreshTimer; // @synthesize refreshTimer=_refreshTimer;
@property(retain, nonatomic) UIButton *otherLink; // @synthesize otherLink=_otherLink;
@property(retain, nonatomic) VIQRCodeDescView *descriptionView; // @synthesize descriptionView=_descriptionView;
@property(retain, nonatomic) VIQRCodeView *qrCodeView; // @synthesize qrCodeView=_qrCodeView;
@property(nonatomic) long long qrcodeTimeInterval; // @synthesize qrcodeTimeInterval=_qrcodeTimeInterval;
@property(nonatomic) _Bool hasOtherVIProduct; // @synthesize hasOtherVIProduct=_hasOtherVIProduct;
@property(retain, nonatomic) NSString *otherLinkTitle; // @synthesize otherLinkTitle=_otherLinkTitle;
@property(retain, nonatomic) NSArray *descriptions; // @synthesize descriptions=_descriptions;
@property(retain, nonatomic) NSString *qrCodeToken; // @synthesize qrCodeToken=_qrCodeToken;
@property(retain, nonatomic) NSString *mainCodeTitle; // @synthesize mainCodeTitle=_mainCodeTitle;
@property(retain, nonatomic) NSString *navigationTitle; // @synthesize navigationTitle=_navigationTitle;
- (void).cxx_destruct;
- (void)applicationDidBecomeActive;
- (void)applicationWillResignActive;
- (void)handleRefreshResultWith:(id)arg1;
- (void)qrCodeNeedRefresh;
- (void)stopRefreshTimer;
- (void)startRefreshTimer;
- (void)didReceiveMemoryWarning;
- (void)otherLinkClicked;
- (void)drawOtherLinkView;
- (id)qrCodeImageWith:(id)arg1;
- (void)drawSubView;
- (void)registNotifications;
- (void)viewDidLoad;
- (void)viewDidDisappear:(_Bool)arg1;

@end

