//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSCache, NSMutableArray, NSMutableDictionary, NSMutableSet, NSString;

@interface WKTemplateManager : NSObject
{
    NSString *_tplVersion;
    id <WKTemplateDownloadProtocol> _downloadManager;
    id <WKTemplateStorageProtocol> _dbManager;
    NSMutableSet *_updatedTemplates;
    NSMutableSet *_cachedQuickPayTpls;
    NSCache *_cacheTemplate;
    NSMutableDictionary *_downloadSet;
    NSMutableDictionary *_failedTemplateIdInfo;
    NSMutableArray *_blockArray;
    long long _lastPreloadTime;
}

+ (id)defaultManager;
@property(nonatomic) long long lastPreloadTime; // @synthesize lastPreloadTime=_lastPreloadTime;
@property(retain) NSMutableArray *blockArray; // @synthesize blockArray=_blockArray;
@property(retain) NSMutableDictionary *failedTemplateIdInfo; // @synthesize failedTemplateIdInfo=_failedTemplateIdInfo;
@property(retain) NSMutableDictionary *downloadSet; // @synthesize downloadSet=_downloadSet;
@property(retain, nonatomic) NSCache *cacheTemplate; // @synthesize cacheTemplate=_cacheTemplate;
@property(retain, nonatomic) NSMutableSet *cachedQuickPayTpls; // @synthesize cachedQuickPayTpls=_cachedQuickPayTpls;
@property(retain, nonatomic) NSMutableSet *updatedTemplates; // @synthesize updatedTemplates=_updatedTemplates;
@property(retain, nonatomic) id <WKTemplateStorageProtocol> dbManager; // @synthesize dbManager=_dbManager;
@property(retain, nonatomic) id <WKTemplateDownloadProtocol> downloadManager; // @synthesize downloadManager=_downloadManager;
@property(retain, nonatomic) NSString *tplVersion; // @synthesize tplVersion=_tplVersion;
- (void).cxx_destruct;
- (void)logTplDownloadFailed:(id)arg1 isSyncUpdate:(_Bool)arg2;
- (void)requestTemplates:(id)arg1 isSyncUpdate:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)requestTemplates:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)notifyTemplatesDownloadDone:(id)arg1 error:(id)arg2;
- (void)cachedDownload:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)forceDownloadInNextRpc:(id)arg1;
- (_Bool)removeTemplateById:(id)arg1;
- (_Bool)saveTemplates:(id)arg1;
- (_Bool)save:(id)arg1;
- (void)downloadTemplates:(id)arg1 isSyncUpdate:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)downloadTemplates:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)templateById:(id)arg1 retriveBlock:(CDUnknownBlockType)arg2;
- (id)cachedTemplatesByIds:(id)arg1;
- (id)cachedTemplateById:(id)arg1;
- (void)addTemplateCaches:(id)arg1;
- (void)addTemplateCache:(id)arg1;
- (void)receiveMemoryWarning;
- (void)setupTemplateManager;
- (void)dealloc;
- (id)init;

@end

