//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "TuSDKPFStickerItemViewInterface.h"
#import "UIGestureRecognizerDelegate.h"

@class NSMutableArray, NSString, TuSDKPFSticker, UIButton, UIColor, UIImageView, UIPanGestureRecognizer, UIPinchGestureRecognizer, UIRotationGestureRecognizer;

@interface TuSDKPFStickerItemView : UIView <UIGestureRecognizerDelegate, TuSDKPFStickerItemViewInterface>
{
    UIImageView *_imageView;
    UIButton *_cancelButton;
    UIImageView *_turnButton;
    struct UIEdgeInsets _mImageEdge;
    struct CGSize _mCSize;
    struct CGSize _mCMargin;
    double _mMaxScale;
    struct CGSize _mDefaultViewSize;
    double _mCHypotenuse;
    double _mScale;
    double _mDegree;
    NSMutableArray *_mTextViews;
    _Bool _isRotatScaleAction;
    UIPanGestureRecognizer *_panGesture;
    UIRotationGestureRecognizer *_rotationGesture;
    UIPinchGestureRecognizer *_pinchGesture;
    struct CGPoint _lastPotion;
    _Bool _hasTouched;
    _Bool _isInGesture;
    _Bool _selected;
    id <TuSDKPFStickerItemViewDelegate> _delegate;
    double _minScale;
    double _strokeWidth;
    UIColor *_strokeColor;
    TuSDKPFSticker *_sticker;
}

@property(retain, nonatomic) TuSDKPFSticker *sticker; // @synthesize sticker=_sticker;
@property(nonatomic) _Bool selected; // @synthesize selected=_selected;
@property(retain, nonatomic) UIColor *strokeColor; // @synthesize strokeColor=_strokeColor;
@property(nonatomic) double strokeWidth; // @synthesize strokeWidth=_strokeWidth;
@property(nonatomic) double minScale; // @synthesize minScale=_minScale;
@property(nonatomic) id <TuSDKPFStickerItemViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) UIImageView *turnButton; // @synthesize turnButton=_turnButton;
@property(readonly, nonatomic) UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(readonly, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
- (struct CGRect)centerOfParentRegin:(struct CGRect)arg1;
- (id)resultWithRegionRect:(struct CGRect)arg1;
- (struct CGPoint)fixedCenterPoint:(struct CGPoint)arg1;
- (void)computerScaleWithScale:(double)arg1 center:(struct CGPoint)arg2;
- (void)computerScaleWithPoint:(struct CGPoint)arg1 lastPoint:(struct CGPoint)arg2 center:(struct CGPoint)arg3;
- (void)computerAngleWithPoint:(struct CGPoint)arg1 lastPoint:(struct CGPoint)arg2 center:(struct CGPoint)arg3;
- (void)loginfo:(id)arg1;
- (void)handlePanGestureRotatScaleAction:(struct CGPoint)arg1;
- (void)handlePanGestureTransAction:(struct CGPoint)arg1;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)handlePinchGesture:(id)arg1;
- (void)handleRotationGesture:(id)arg1;
- (void)handlePanGesture:(id)arg1;
- (void)buildStickerTextView:(id)arg1;
- (void)createStickerTexts:(id)arg1;
- (void)initStickerPostion;
- (void)resetViewsBounds;
- (void)resetImageEdge;
- (void)handleCancelButton;
- (void)dealloc;
- (void)viewWillDestory;
- (void)removeGestureRecognizer;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)appendGestureRecognizer;
- (void)initView;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

