//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UILabel;

@interface XYPHPostEditImageGenerateBranchTagChooseDistrictAddTagTableViewCell : UITableViewCell
{
    UILabel *_addLabel;
}

+ (double)estimatedHeight;
@property(retain, nonatomic) UILabel *addLabel; // @synthesize addLabel=_addLabel;
- (void).cxx_destruct;
- (void)config:(id)arg1;
- (void)setup;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

