//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XYPHBaseViewController.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UICollectionViewDelegateFlowLayout.h"

@class JSCustomBadge, NSMutableArray, NSString, UIBarButtonItem, UIButton, UICollectionView, UIToolbar;

@interface XYPHPostAssetsBrowserViewController : XYPHBaseViewController <UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout>
{
    _Bool _isGenerating;
    NSMutableArray *_assets;
    NSMutableArray *_selectedAssets;
    long long _startIndex;
    UICollectionView *_collectionView;
    UIToolbar *_toolbar;
    UIBarButtonItem *_doneBarButtonItem;
    JSCustomBadge *_badgeView;
    UIButton *_checkmarkButton;
}

@property(nonatomic) _Bool isGenerating; // @synthesize isGenerating=_isGenerating;
@property(retain, nonatomic) UIButton *checkmarkButton; // @synthesize checkmarkButton=_checkmarkButton;
@property(retain, nonatomic) JSCustomBadge *badgeView; // @synthesize badgeView=_badgeView;
@property(retain, nonatomic) UIBarButtonItem *doneBarButtonItem; // @synthesize doneBarButtonItem=_doneBarButtonItem;
@property(retain, nonatomic) UIToolbar *toolbar; // @synthesize toolbar=_toolbar;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(nonatomic) long long startIndex; // @synthesize startIndex=_startIndex;
@property(retain, nonatomic) NSMutableArray *selectedAssets; // @synthesize selectedAssets=_selectedAssets;
@property(retain, nonatomic) NSMutableArray *assets; // @synthesize assets=_assets;
- (void).cxx_destruct;
- (void)postImageChangeNotification:(id)arg1;
- (id)centerIndexPath;
- (void)checkmarkButtonTouchUpInside:(id)arg1;
- (void)doneBarButtonTouchUpInside:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)updateCheckmarkButton;
- (void)setupCollectionView;
- (void)setupDoneBarButton;
- (void)setupDoneBarButtonItem;
- (void)setupBootomToolBar;
- (void)setup;
- (void)dealloc;
- (_Bool)prefersStatusBarHidden;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

