//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "XYPHBranchTagViewDelegate.h"

@class NSMutableSet, NSString;

@interface XYPHPostEditImageBranchTagView : UIView <XYPHBranchTagViewDelegate>
{
    id <XYPHPostEditImageBranchTagViewDelegate> _delegate;
    UIView *_placeholderBranchTagView;
    NSMutableSet *_addBranchTag;
}

@property(retain, nonatomic) NSMutableSet *addBranchTag; // @synthesize addBranchTag=_addBranchTag;
@property(retain, nonatomic) UIView *placeholderBranchTagView; // @synthesize placeholderBranchTagView=_placeholderBranchTagView;
@property(nonatomic) __weak id <XYPHPostEditImageBranchTagViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)branchTagViewDidTapLocation:(id)arg1 branchTag:(id)arg2;
- (void)branchTagViewDidTapPrice:(id)arg1 branchTag:(id)arg2;
- (void)branchTagViewDidTapBrandAndGood:(id)arg1 branchTag:(id)arg2;
- (void)branchTagViewDidTapCenterCircle:(id)arg1 branchTag:(id)arg2;
- (void)removeLongGesture:(id)arg1;
- (void)addBranchTagTapGesture:(id)arg1;
- (void)removePlaceholderBranchTag;
- (void)setupTags:(id)arg1;
- (void)removeBranchTag:(id)arg1;
- (void)addBranchTag:(id)arg1 animated:(_Bool)arg2;
- (void)createPlaceholderBranchTagAtPoint:(struct CGPoint)arg1;
- (void)setup;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

