//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ALBBURLBusContext, ALBBURLFilterAction, NSURL;

@protocol ALBBURLFilterAction <NSObject>
- (NSURL *)action:(ALBBURLFilterAction *)arg1 filterURL:(NSURL *)arg2 context:(ALBBURLBusContext *)arg3;
@end

