//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TTRequestModel.h"

@class NSNumber, NSNumber<Optional>, NSString;

@interface FRVerticalMovie1ShortReviewsRequestModel : TTRequestModel
{
    NSString *_concern_id;
    NSNumber *_count;
    NSNumber *_cursor;
    NSNumber<Optional> *_sort_type;
}

@property(retain, nonatomic) NSNumber<Optional> *sort_type; // @synthesize sort_type=_sort_type;
@property(retain, nonatomic) NSNumber *cursor; // @synthesize cursor=_cursor;
@property(retain, nonatomic) NSNumber *count; // @synthesize count=_count;
@property(retain, nonatomic) NSString *concern_id; // @synthesize concern_id=_concern_id;
- (void).cxx_destruct;
- (id)_requestParams;
- (id)init;

@end

