//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessageBuilder.h"

@class Message;

@interface MessageBuilder : PBGeneratedMessageBuilder
{
    Message *resultMessage;
}

@property(retain) Message *resultMessage; // @synthesize resultMessage;
- (void).cxx_destruct;
- (id)clearCreateTime;
- (id)setCreateTime:(long long)arg1;
- (long long)createTime;
- (_Bool)hasCreateTime;
- (id)clearContent;
- (id)setContent:(id)arg1;
- (id)content;
- (_Bool)hasContent;
- (id)clearType;
- (id)setType:(int)arg1;
- (int)type;
- (_Bool)hasType;
- (id)clearToId;
- (id)setToId:(id)arg1;
- (id)toId;
- (_Bool)hasToId;
- (id)clearFromId;
- (id)setFromId:(long long)arg1;
- (long long)fromId;
- (_Bool)hasFromId;
- (id)clearMessageId;
- (id)setMessageId:(long long)arg1;
- (long long)messageId;
- (_Bool)hasMessageId;
- (id)clearDeviceId;
- (id)setDeviceId:(long long)arg1;
- (long long)deviceId;
- (_Bool)hasDeviceId;
- (id)clearClientId;
- (id)setClientId:(long long)arg1;
- (long long)clientId;
- (_Bool)hasClientId;
- (id)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
- (id)mergeFromCodedInputStream:(id)arg1;
- (id)mergeFrom:(id)arg1;
- (id)buildPartial;
- (id)build;
- (id)defaultInstance;
- (id)clone;
- (id)clear;
- (id)internalGetResult;
- (id)init;

@end

