//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessageBuilder.h"

@class PBFileDescriptorSet;

@interface PBFileDescriptorSetBuilder : PBGeneratedMessageBuilder
{
    PBFileDescriptorSet *resultFileDescriptorSet;
}

@property(retain) PBFileDescriptorSet *resultFileDescriptorSet; // @synthesize resultFileDescriptorSet;
- (void).cxx_destruct;
- (id)clearFile;
- (id)setFileArray:(id)arg1;
- (id)addFile:(id)arg1;
- (id)fileAtIndex:(unsigned long long)arg1;
- (id)file;
- (id)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
- (id)mergeFromCodedInputStream:(id)arg1;
- (id)mergeFrom:(id)arg1;
- (id)buildPartial;
- (id)build;
- (id)defaultInstance;
- (id)clone;
- (id)clear;
- (id)internalGetResult;
- (id)init;

@end

