//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SSThemedView.h"

#import "UIScrollViewDelegate.h"
#import "_TTTabBarDelegate.h"

@class NSMutableArray, NSString, _TTContainerScrollView, _TTTabBar;

@interface TTTabContainerView : SSThemedView <_TTTabBarDelegate, UIScrollViewDelegate>
{
    _Bool _isClickTabToScroll;
    _Bool _firstShowIndexFinish;
    id <TTTabContainerViewDelegate> _delegate;
    unsigned long long _pageIndex;
    NSMutableArray *_pages;
    _TTTabBar *_tabBar;
    double _tabbarHeight;
    unsigned long long _tabBarType;
    _TTContainerScrollView *_scrollContainerView;
}

@property(nonatomic) _Bool firstShowIndexFinish; // @synthesize firstShowIndexFinish=_firstShowIndexFinish;
@property(retain, nonatomic) _TTContainerScrollView *scrollContainerView; // @synthesize scrollContainerView=_scrollContainerView;
@property(nonatomic) unsigned long long tabBarType; // @synthesize tabBarType=_tabBarType;
@property(nonatomic) double tabbarHeight; // @synthesize tabbarHeight=_tabbarHeight;
@property(retain, nonatomic) _TTTabBar *tabBar; // @synthesize tabBar=_tabBar;
@property(retain, nonatomic) NSMutableArray *pages; // @synthesize pages=_pages;
@property(nonatomic) unsigned long long pageIndex; // @synthesize pageIndex=_pageIndex;
@property(nonatomic) __weak id <TTTabContainerViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)tabBar:(id)arg1 didSelectedAtIndex:(unsigned long long)arg2;
- (unsigned long long)currentPageIndexTabBar:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (struct CGRect)frameForScrollContainerViewWithContainerType:(unsigned long long)arg1 TabBarHeight:(double)arg2;
- (struct CGRect)frameForTabbarWithContainerType:(unsigned long long)arg1 tabBarHeight:(double)arg2;
- (id)pageAtIndex:(unsigned long long)arg1;
- (void)showIndex:(unsigned long long)arg1 animation:(_Bool)arg2;
- (void)performBatchUpdatesAndShowIndex:(unsigned long long)arg1 animation:(_Bool)arg2;
- (void)layoutSubviews;
- (void)addPageView:(id)arg1 title:(id)arg2;
- (void)createComponentWithTabBarType:(unsigned long long)arg1 tabBarHeight:(double)arg2;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 tabBarType:(unsigned long long)arg2 tabBarHeight:(double)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

