//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TTThreadCellItemBase.h"

#import "BlockUserManagerDelegate.h"
#import "ExploreDislikeViewDelegate.h"
#import "TTDislikePopViewDelegate.h"
#import "TTShareManagerDelegate.h"

@class BlockUserManager, CAShapeLayer, DetailActionRequestManager, FRIconView, FriendDataManager, NSArray, NSSet, NSString, SSThemedButton, SSThemedImageView, SSThemedLabel, SSThemedView, TTActionSheetController, TTAlphaThemedButton, TTArticleTagView, TTThreadRateView, TTVerifyIconImageView, Thread, UIFont;

@interface TTThreadAvatarView : TTThreadCellItemBase <BlockUserManagerDelegate, TTDislikePopViewDelegate, ExploreDislikeViewDelegate, TTShareManagerDelegate>
{
    Thread *_originalThreadData;
    NSArray *_actionItems;
    BlockUserManager *_blockUserManager;
    FriendDataManager *_friendManager;
    TTArticleTagView *_tagView;
    SSThemedImageView *_avatarView;
    CAShapeLayer *_avatarMaskLayer;
    CAShapeLayer *_cellLayout1AvatarMaskLayer;
    CAShapeLayer *_avatarBorderLayer;
    CAShapeLayer *_cellLayout1AvatarBorderLayer;
    SSThemedButton *_nameButton;
    SSThemedView *_verifiedContentSeprateLine;
    SSThemedLabel *_verifiedContentLabel;
    TTVerifyIconImageView *_verifiedImageView;
    FRIconView *_iconsView;
    SSThemedLabel *_commentLabel;
    SSThemedImageView *_arrowImageView;
    SSThemedButton *_forumButton;
    TTThreadRateView *_rateView;
    SSThemedButton *_moreView;
    TTAlphaThemedButton *_unInterestedButton;
    SSThemedButton *_resendButton;
    UIFont *_infoFont;
    UIFont *_cellLayout1InfoFont;
    TTActionSheetController *_actionSheetController;
    DetailActionRequestManager *_actionManager;
    NSSet *_shareActivityContentItemTypes;
}

+ (_Bool)shouldShowForData:(id)arg1 listType:(unsigned long long)arg2;
+ (double)heightForData:(id)arg1 width:(double)arg2 listType:(unsigned long long)arg3;
@property(copy, nonatomic) NSSet *shareActivityContentItemTypes; // @synthesize shareActivityContentItemTypes=_shareActivityContentItemTypes;
@property(retain, nonatomic) DetailActionRequestManager *actionManager; // @synthesize actionManager=_actionManager;
@property(retain, nonatomic) TTActionSheetController *actionSheetController; // @synthesize actionSheetController=_actionSheetController;
@property(retain, nonatomic) UIFont *cellLayout1InfoFont; // @synthesize cellLayout1InfoFont=_cellLayout1InfoFont;
@property(retain, nonatomic) UIFont *infoFont; // @synthesize infoFont=_infoFont;
@property(retain, nonatomic) SSThemedButton *resendButton; // @synthesize resendButton=_resendButton;
@property(retain, nonatomic) TTAlphaThemedButton *unInterestedButton; // @synthesize unInterestedButton=_unInterestedButton;
@property(retain, nonatomic) SSThemedButton *moreView; // @synthesize moreView=_moreView;
@property(retain, nonatomic) TTThreadRateView *rateView; // @synthesize rateView=_rateView;
@property(retain, nonatomic) SSThemedButton *forumButton; // @synthesize forumButton=_forumButton;
@property(retain, nonatomic) SSThemedImageView *arrowImageView; // @synthesize arrowImageView=_arrowImageView;
@property(retain, nonatomic) SSThemedLabel *commentLabel; // @synthesize commentLabel=_commentLabel;
@property(retain, nonatomic) FRIconView *iconsView; // @synthesize iconsView=_iconsView;
@property(retain, nonatomic) TTVerifyIconImageView *verifiedImageView; // @synthesize verifiedImageView=_verifiedImageView;
@property(retain, nonatomic) SSThemedLabel *verifiedContentLabel; // @synthesize verifiedContentLabel=_verifiedContentLabel;
@property(retain, nonatomic) SSThemedView *verifiedContentSeprateLine; // @synthesize verifiedContentSeprateLine=_verifiedContentSeprateLine;
@property(retain, nonatomic) SSThemedButton *nameButton; // @synthesize nameButton=_nameButton;
@property(retain, nonatomic) CAShapeLayer *cellLayout1AvatarBorderLayer; // @synthesize cellLayout1AvatarBorderLayer=_cellLayout1AvatarBorderLayer;
@property(retain, nonatomic) CAShapeLayer *avatarBorderLayer; // @synthesize avatarBorderLayer=_avatarBorderLayer;
@property(retain, nonatomic) CAShapeLayer *cellLayout1AvatarMaskLayer; // @synthesize cellLayout1AvatarMaskLayer=_cellLayout1AvatarMaskLayer;
@property(retain, nonatomic) CAShapeLayer *avatarMaskLayer; // @synthesize avatarMaskLayer=_avatarMaskLayer;
@property(retain, nonatomic) SSThemedImageView *avatarView; // @synthesize avatarView=_avatarView;
@property(retain, nonatomic) TTArticleTagView *tagView; // @synthesize tagView=_tagView;
@property(retain, nonatomic) FriendDataManager *friendManager; // @synthesize friendManager=_friendManager;
@property(retain, nonatomic) BlockUserManager *blockUserManager; // @synthesize blockUserManager=_blockUserManager;
@property(retain, nonatomic) NSArray *actionItems; // @synthesize actionItems=_actionItems;
@property(retain, nonatomic) Thread *originalThreadData; // @synthesize originalThreadData=_originalThreadData;
- (void).cxx_destruct;
- (_Bool)needShowTagView:(id)arg1 listType:(unsigned long long)arg2;
- (void)themeChanged:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)removeKVO;
- (void)addKVO;
- (void)blockUserManager:(id)arg1 unblockResult:(_Bool)arg2 unblockedUserID:(id)arg3 error:(id)arg4 errorTip:(id)arg5;
- (void)blockUserManager:(id)arg1 blocResult:(_Bool)arg2 blockedUserID:(id)arg3 error:(id)arg4 errorTip:(id)arg5;
- (void)shareManager:(id)arg1 completedWith:(id)arg2 error:(id)arg3 desc:(id)arg4;
- (void)shareManager:(id)arg1 clickedWith:(id)arg2;
- (void)exploreDislikeViewOKBtnClicked:(id)arg1;
- (void)dislikeButtonClicked:(id)arg1 onlyOne:(_Bool)arg2;
- (void)showLoginViewController:(id)arg1;
- (void)blockUser:(id)arg1;
- (_Bool)isAuthor:(id)arg1;
- (id)createDeleteItem;
- (id)createReportItem:(id)arg1;
- (id)createBlockItem:(id)arg1;
- (id)createShareItem:(id)arg1;
- (id)createFollowItem:(id)arg1;
- (id)createDislikeItem:(id)arg1;
- (id)createActionItems;
- (void)moreViewClicked;
- (void)resendClick:(id)arg1;
- (void)unInterestTap:(id)arg1;
- (void)forumTap:(id)arg1;
- (void)nameTap:(id)arg1;
- (void)avatarTap:(id)arg1;
- (id)generateImageInfos;
- (void)layoutInfoComponentsOfAvatarAtBottom;
- (void)layoutInfoComponentsOfAvatarAtTop;
- (void)layoutResendButtonAndMoreView;
- (void)refreshReadStyle;
- (void)refreshWithData:(id)arg1 listType:(unsigned long long)arg2;
- (void)refreshUI;
- (void)createComponent;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

