//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ExploreActionButton.h"

@class ExploreMovieView;

@interface TTVideoEmbededAdButton : ExploreActionButton
{
    ExploreMovieView *_attachedMovie;
}

@property(nonatomic) __weak ExploreMovieView *attachedMovie; // @synthesize attachedMovie=_attachedMovie;
- (void).cxx_destruct;
- (double)fontSize;
- (void)listenCall:(id)arg1;
- (void)adButtonClicked:(id)arg1;
- (void)setAdModel:(id)arg1;
- (id)init;

@end

