//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class TTHttpTask, WalletMode;

@interface WalletViewMode : NSObject
{
    WalletMode *_walletMode;
    TTHttpTask *_task;
    CDUnknownBlockType _walletInfoSuccessBlock;
    CDUnknownBlockType _walletInfoFailBlock;
}

+ (id)shareInstance;
@property(copy, nonatomic) CDUnknownBlockType walletInfoFailBlock; // @synthesize walletInfoFailBlock=_walletInfoFailBlock;
@property(copy, nonatomic) CDUnknownBlockType walletInfoSuccessBlock; // @synthesize walletInfoSuccessBlock=_walletInfoSuccessBlock;
@property(retain, nonatomic) TTHttpTask *task; // @synthesize task=_task;
@property(retain, nonatomic) WalletMode *walletMode; // @synthesize walletMode=_walletMode;
- (void).cxx_destruct;
- (id)alipayAvatarUrl;
- (id)alipayNickName;
- (_Bool)isAlipayAuthorised;
- (void)setWithDrawMoney:(id)arg1;
- (id)getWithDrawMoney;
- (unsigned long long)getCurrentUserID;
- (id)getDescribe;
- (id)getAvailableMoney;
- (id)getTotalMoney;
- (id)getCurrentMoney;
- (id)getCurrentFanTicket;
- (unsigned long long)getDiamondNum;
- (void)handleResult:(id)arg1 error:(id)arg2 userInfo:(id)arg3;
- (id)getModeInfo:(id)arg1 params:(id)arg2 userInfo:(id)arg3 retryCount:(int)arg4;
- (void)getWalletModeInfo;

@end

