//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WDBaseModel.h"

@class NSNumber, NSString, NSString<Optional>;

@interface WDPrevPageStructModel : WDBaseModel
{
    NSString<Optional> *_prev_ansid;
    NSString<Optional> *_prev_answer_schema;
    NSString *_all_answer_text;
    NSString *_prev_answer_text;
    NSNumber *_show_toast;
    NSNumber *_has_prev;
}

@property(retain, nonatomic) NSNumber *has_prev; // @synthesize has_prev=_has_prev;
@property(retain, nonatomic) NSNumber *show_toast; // @synthesize show_toast=_show_toast;
@property(retain, nonatomic) NSString *prev_answer_text; // @synthesize prev_answer_text=_prev_answer_text;
@property(retain, nonatomic) NSString *all_answer_text; // @synthesize all_answer_text=_all_answer_text;
@property(retain, nonatomic) NSString<Optional> *prev_answer_schema; // @synthesize prev_answer_schema=_prev_answer_schema;
@property(retain, nonatomic) NSString<Optional> *prev_ansid; // @synthesize prev_ansid=_prev_ansid;
- (void).cxx_destruct;
- (void)reset;
- (id)init;

@end

