//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NVMModel.h"

@class NSArray, NSNumber, NSString;

@interface NVMOrderItem : NVMModel
{
    _Bool _isValid;
    NSNumber *_cartFoodID;
    NSString *_name;
    double _price;
    unsigned long long _quantity;
    NSArray *_specsItems;
    NSArray *_attributeItems;
    NSString *_content;
}

+ (id)attributeItemsJSONTransformer;
+ (id)specsItemsJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@property(nonatomic) _Bool isValid; // @synthesize isValid=_isValid;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
@property(copy, nonatomic) NSArray *attributeItems; // @synthesize attributeItems=_attributeItems;
@property(copy, nonatomic) NSArray *specsItems; // @synthesize specsItems=_specsItems;
@property(nonatomic) unsigned long long quantity; // @synthesize quantity=_quantity;
@property(nonatomic) double price; // @synthesize price=_price;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSNumber *cartFoodID; // @synthesize cartFoodID=_cartFoodID;
- (void).cxx_destruct;
- (_Bool)hasContent;
- (double)total;
- (id)quantityString;
- (id)totalString;

@end

