//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface NVMWebURLPatternSegment : NSObject
{
    NSString *_segmenntName;
    NSString *_segmentValue;
    unsigned long long _type;
    struct _NSRange _originRange;
}

@property(nonatomic) struct _NSRange originRange; // @synthesize originRange=_originRange;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *segmentValue; // @synthesize segmentValue=_segmentValue;
@property(copy, nonatomic) NSString *segmenntName; // @synthesize segmenntName=_segmenntName;
- (void).cxx_destruct;
- (id)description;
- (id)subURLStringFromMeta:(id)arg1;
- (id)initWithName:(id)arg1 value:(id)arg2 originRange:(struct _NSRange)arg3;

@end

