//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WXComponent.h"

@class NSIndexPath, NSString, WXListComponent;

@interface WXCellComponent : WXComponent
{
    NSIndexPath *_indexPathBeforeMove;
    NSString *_scope;
    long long _insertAnimation;
    long long _deleteAnimation;
    WXListComponent *_list;
}

@property(nonatomic) __weak WXListComponent *list; // @synthesize list=_list;
@property(nonatomic) long long deleteAnimation; // @synthesize deleteAnimation=_deleteAnimation;
@property(nonatomic) long long insertAnimation; // @synthesize insertAnimation=_insertAnimation;
@property(retain, nonatomic) NSString *scope; // @synthesize scope=_scope;
- (void).cxx_destruct;
- (void)_calculateFrameWithSuperAbsolutePosition:(struct CGPoint)arg1 gatherDirtyComponents:(id)arg2;
- (void)removeFromSuperview;
- (void)_removeFromSupercomponent;
- (void)_moveToSupercomponent:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)updateAttributes:(id)arg1;
- (CDUnknownBlockType)displayCompletionBlock;
- (void)_frameDidCalculated:(_Bool)arg1;
- (void)dealloc;
- (id)initWithRef:(id)arg1 type:(id)arg2 styles:(id)arg3 attributes:(id)arg4 events:(id)arg5 weexInstance:(id)arg6;

@end

