//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIAlertViewDelegate.h"

@class AlibcSafeMutableArray, NSString;

@interface AlibcFlowCheck : NSObject <UIAlertViewDelegate>
{
    NSString *alertTips;
    NSString *openUrl;
    NSString *appkey;
    AlibcSafeMutableArray *_visaCheckedURLs;
}

+ (id)shareInstance;
@property(retain, nonatomic) AlibcSafeMutableArray *visaCheckedURLs; // @synthesize visaCheckedURLs=_visaCheckedURLs;
- (void).cxx_destruct;
- (void)userTrackMgrFlowLostFlyWithUrl:(id)arg1 ext:(id)arg2;
- (void)userTrackMgrFlowLostAppNotInstallWithUrl:(id)arg1 ext:(id)arg2;
- (void)userTrackMgrFlowLostHandleWithUrl:(id)arg1 ext:(id)arg2;
- (void)userTrackMgrFlowGetHandleWithSourceAppPackageName:(id)arg1 url:(id)arg2;
- (void)userTrackMgrFlowGetPassWithSourceAppPackageName:(id)arg1 url:(id)arg2;
- (_Bool)isUrl:(id)arg1 MatchRegularExpress:(id)arg2;
- (void)showToast:(id)arg1;
- (_Bool)visaCheckForFirstGo;
- (_Bool)checkByRemoteVisa:(id)arg1 outScheme:(id)arg2 complete:(CDUnknownBlockType)arg3;
- (_Bool)flowOutGoingCheckByVisa:(id)arg1 outScheme:(id)arg2 complete:(CDUnknownBlockType)arg3;
- (_Bool)checkVisaExistWithUrl:(id)arg1 visa:(id)arg2 outScheme:(id)arg3 complete:(CDUnknownBlockType)arg4;
- (_Bool)isUrlMatchBlackList:(id)arg1;
- (_Bool)flowOutGoingCheckByWhiteListWithUrl:(id)arg1 visa:(id)arg2 outScheme:(id)arg3 complete:(CDUnknownBlockType)arg4;
- (_Bool)flowOutGoingCheckWithUrl:(id)arg1 visa:(id)arg2 complete:(CDUnknownBlockType)arg3;
- (_Bool)flowEntryCheckPtivateWithPackageName:(id)arg1 url:(id)arg2 ext:(id)arg3;
- (_Bool)flowEntryCheckWithPackageName:(id)arg1 url:(id)arg2 ext:(id)arg3;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

