//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TBJSONModel.h"

@class NSArray<AliDetailConsumerProtectionItemModel>, NSString;

@interface AliDetailConsumerProtectionSubServiceModel : TBJSONModel
{
    NSString *_icon;
    NSString *_title;
    NSArray<AliDetailConsumerProtectionItemModel> *_items;
}

@property(retain, nonatomic) NSArray<AliDetailConsumerProtectionItemModel> *items; // @synthesize items=_items;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *icon; // @synthesize icon=_icon;
- (void).cxx_destruct;

@end

