//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ALPJumpParam.h"

@class NSString;

@interface ALPTBURIParam : ALPJumpParam
{
    NSString *_degradeToH5Url;
    NSString *_uri;
}

@property(retain, nonatomic) NSString *uri; // @synthesize uri=_uri;
- (void)setDegradeToH5Url:(id)arg1;
- (void).cxx_destruct;
- (id)degradeToH5Url;
- (id)isLegalParam;
- (void)removeRepeatParams;
- (id)ALP_visaString;
- (id)ALP_parseToJSONString;
- (id)init;
- (id)initWithURI:(id)arg1;

@end

