//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface AVFSFileDetail : NSObject
{
    NSString *_fileName;
    NSString *_moduleName;
    long long _fileSize;
    long long _createDate;
    long long _modifyDate;
    long long _accessDate;
}

@property(nonatomic) long long accessDate; // @synthesize accessDate=_accessDate;
@property(nonatomic) long long modifyDate; // @synthesize modifyDate=_modifyDate;
@property(nonatomic) long long createDate; // @synthesize createDate=_createDate;
@property(nonatomic) long long fileSize; // @synthesize fileSize=_fileSize;
@property(retain, nonatomic) NSString *moduleName; // @synthesize moduleName=_moduleName;
@property(retain, nonatomic) NSString *fileName; // @synthesize fileName=_fileName;
- (void).cxx_destruct;
- (long long)dismissionDate:(long long)arg1;
- (id)base64Decode:(id)arg1;
- (id)keysWithFileName:(id)arg1;
- (void)deleteFile:(id)arg1 withName:(id)arg2 withBlock:(CDUnknownBlockType)arg3;
- (_Bool)deleteFile;
- (id)jsonDictionary;
- (void)calculateFileDetail:(id)arg1;
- (id)initWithModule:(id)arg1 file:(id)arg2;
- (id)init;

@end

