//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TBJSONModel.h"

@class NSString;

@interface CNPackageProxyItem : TBJSONModel
{
    _Bool _isProxyOrder;
    NSString *_proxyOrderCode;
    long long _proxyOrderStatus;
    long long _proxyOrderOptions;
}

@property(nonatomic) long long proxyOrderOptions; // @synthesize proxyOrderOptions=_proxyOrderOptions;
@property(nonatomic) long long proxyOrderStatus; // @synthesize proxyOrderStatus=_proxyOrderStatus;
@property(retain, nonatomic) NSString *proxyOrderCode; // @synthesize proxyOrderCode=_proxyOrderCode;
@property(nonatomic) _Bool isProxyOrder; // @synthesize isProxyOrder=_isProxyOrder;
- (void).cxx_destruct;

@end

