//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString, UIImage;

@interface GDMTUserListItem : NSObject
{
    _Bool _isFailed;
    int _srcIndex;
    NSString *_imgUrl;
    NSArray *_imgUrlArray;
    NSString *_detail;
    long long _type;
    NSString *_feedId;
    NSString *_feedType;
    NSString *_accountId;
    NSString *_itemPrice;
    UIImage *_image;
    NSString *_timestamp;
    NSString *_publishTime;
    id _pubilishItem;
    NSString *_url;
}

@property(retain) NSString *url; // @synthesize url=_url;
@property _Bool isFailed; // @synthesize isFailed=_isFailed;
@property(retain) id pubilishItem; // @synthesize pubilishItem=_pubilishItem;
@property(retain, nonatomic) NSString *publishTime; // @synthesize publishTime=_publishTime;
@property(retain) NSString *timestamp; // @synthesize timestamp=_timestamp;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(nonatomic) int srcIndex; // @synthesize srcIndex=_srcIndex;
@property(retain, nonatomic) NSString *itemPrice; // @synthesize itemPrice=_itemPrice;
@property(retain, nonatomic) NSString *accountId; // @synthesize accountId=_accountId;
@property(retain, nonatomic) NSString *feedType; // @synthesize feedType=_feedType;
@property(retain, nonatomic) NSString *feedId; // @synthesize feedId=_feedId;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *detail; // @synthesize detail=_detail;
@property(retain, nonatomic) NSArray *imgUrlArray; // @synthesize imgUrlArray=_imgUrlArray;
@property(retain, nonatomic) NSString *imgUrl; // @synthesize imgUrl=_imgUrl;
- (void).cxx_destruct;

@end

