//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class TPCheckResult, TPResult;

@protocol TaoPasswordDelegate <NSObject>
- (void)didTaoPasswordRequestFinished:(TPResult *)arg1 withModelClass:(Class)arg2;

@optional
- (void)didTaoPasswordRequestStarted:(TPCheckResult *)arg1;
- (void)didPicPasswordCheckFinished:(TPCheckResult *)arg1;
- (void)didTaoPasswordCheckFinished:(TPCheckResult *)arg1;
@end

