//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface TBCartComponentFactory : NSObject
{
    NSMutableDictionary *_componentDict;
}

+ (id)componentWithKey:(id)arg1 withData:(id)arg2;
+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableDictionary *componentDict; // @synthesize componentDict=_componentDict;
- (void).cxx_destruct;
- (id)init;

@end

