//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, UIView;

@protocol TBDinamicDataBinder <NSObject>
- (void)bindData:(NSDictionary *)arg1 withAttr:(NSDictionary *)arg2 inView:(UIView *)arg3;
@end

