//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CABasicAnimation, NSMutableArray, UIButton;

@interface TBLongPressView : UIView
{
    _Bool _rowDirection;
    NSMutableArray *_btnArray;
    UIView *_animationView;
    CABasicAnimation *_animation;
    UIButton *_itemBackgroundButton;
}

@property(nonatomic) _Bool rowDirection; // @synthesize rowDirection=_rowDirection;
@property(retain, nonatomic) UIButton *itemBackgroundButton; // @synthesize itemBackgroundButton=_itemBackgroundButton;
@property(retain, nonatomic) CABasicAnimation *animation; // @synthesize animation=_animation;
@property(retain, nonatomic) UIView *animationView; // @synthesize animationView=_animationView;
@property(retain, nonatomic) NSMutableArray *btnArray; // @synthesize btnArray=_btnArray;
- (void).cxx_destruct;
- (void)changeValue:(id)arg1 Value:(double)arg2 Add:(_Bool)arg3;
- (void)showWithAnimation:(_Bool)arg1;
- (void)addButton:(id)arg1;
- (void)dismissCompletion:(CDUnknownBlockType)arg1;
- (void)removeLongPressView:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

