//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TBJSONModel.h"

@class NSString;

@interface TBMy3DFestivalDO : TBJSONModel
{
    NSString *_picUrl;
    NSString *_musicUrl;
}

@property(copy, nonatomic) NSString *musicUrl; // @synthesize musicUrl=_musicUrl;
@property(copy, nonatomic) NSString *picUrl; // @synthesize picUrl=_picUrl;
- (void).cxx_destruct;

@end

