//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TBCBaseComponent.h"

@class CALayer, NSString, UIImage, UIImageView, UILabel, UIView;

@interface TBRDVideoFavorComponent : TBCBaseComponent
{
    _Bool _isAlreadyLike;
    UIView *_favorView;
    UIView *_favorContentView;
    UILabel *_lbNum;
    UIImageView *_ivIcon;
    UILabel *_lbText;
    CALayer *_gradientLayer;
    UIImage *_zangIcon;
    UIImage *_unZangIcon;
    NSString *_likeCount;
}

+ (id)defaultStyle;
+ (id)componentTag;
@property(copy, nonatomic) NSString *likeCount; // @synthesize likeCount=_likeCount;
@property(nonatomic) _Bool isAlreadyLike; // @synthesize isAlreadyLike=_isAlreadyLike;
@property(retain, nonatomic) UIImage *unZangIcon; // @synthesize unZangIcon=_unZangIcon;
@property(retain, nonatomic) UIImage *zangIcon; // @synthesize zangIcon=_zangIcon;
@property(retain, nonatomic) CALayer *gradientLayer; // @synthesize gradientLayer=_gradientLayer;
@property(retain, nonatomic) UILabel *lbText; // @synthesize lbText=_lbText;
@property(retain, nonatomic) UIImageView *ivIcon; // @synthesize ivIcon=_ivIcon;
@property(retain, nonatomic) UILabel *lbNum; // @synthesize lbNum=_lbNum;
@property(retain, nonatomic) UIView *favorContentView; // @synthesize favorContentView=_favorContentView;
@property(retain, nonatomic) UIView *favorView; // @synthesize favorView=_favorView;
- (void).cxx_destruct;
- (void)zangAction:(id)arg1;
- (void)loadContext:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

