//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TBJSONModel.h"

@class NSMutableAttributedString, NSString;

@interface TBRecmdMoneyComponent : TBJSONModel
{
    NSString *_cent;
    NSString *_amount;
    NSString *_unit;
    NSString *_symbol;
    NSString *_yuan;
    NSString *_separator;
    NSString *_wholePriceStr;
    NSMutableAttributedString *_wholePriceAttributedStr;
}

@property(retain, nonatomic) NSMutableAttributedString *wholePriceAttributedStr; // @synthesize wholePriceAttributedStr=_wholePriceAttributedStr;
@property(retain, nonatomic) NSString *wholePriceStr; // @synthesize wholePriceStr=_wholePriceStr;
@property(retain, nonatomic) NSString *separator; // @synthesize separator=_separator;
@property(retain, nonatomic) NSString *yuan; // @synthesize yuan=_yuan;
@property(retain, nonatomic) NSString *symbol; // @synthesize symbol=_symbol;
@property(retain, nonatomic) NSString *unit; // @synthesize unit=_unit;
@property(retain, nonatomic) NSString *amount; // @synthesize amount=_amount;
@property(retain, nonatomic) NSString *cent; // @synthesize cent=_cent;
- (void).cxx_destruct;
- (id)initWithJSONDictionary:(id)arg1;

@end

