//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TBJSONModel.h"

@class NSArray, NSArray<TBSCCommentCommodityItem>, NSString, SLAttributedLabel, TBSCCommentCommodityItem;

@interface TBSCCommentParentBaseItem : TBJSONModel
{
    _Bool _isImageHadLoad;
    _Bool _isForPraise;
    int _createrContentType;
    int _parentContentType;
    unsigned long long _targetOwnerUserId;
    unsigned long long _targetId;
    unsigned long long _createrId;
    NSString *_createrName;
    NSString *_createrPic;
    unsigned long long _commentId;
    NSString *_content;
    unsigned long long _id;
    unsigned long long _time;
    unsigned long long _timestamp;
    NSString *_parentContent;
    NSString *_authorNick;
    unsigned long long _authorId;
    unsigned long long _parentId;
    NSArray<TBSCCommentCommodityItem> *_extSymbol;
    NSArray *_extSymbolArray;
    unsigned long long _type;
    NSArray<TBSCCommentCommodityItem> *_parentExtSymbol;
    NSArray *_parentExtSymbolArray;
    unsigned long long _parentType;
    NSString *_detailUrl;
    double _cellHeight;
    double _contentHeight;
    double _parentContentHeight;
    SLAttributedLabel *_contentSLabel;
    SLAttributedLabel *_parentContentSLabel;
    TBSCCommentCommodityItem *_commentCommodityItem;
    NSString *_imageName;
    TBSCCommentCommodityItem *_commentCommodityParentItem;
    NSString *_imageParentName;
    struct CGSize _contentlabelSize;
    struct CGSize _parentContentlabelSize;
}

@property(nonatomic) int parentContentType; // @synthesize parentContentType=_parentContentType;
@property(retain, nonatomic) NSString *imageParentName; // @synthesize imageParentName=_imageParentName;
@property(retain, nonatomic) TBSCCommentCommodityItem *commentCommodityParentItem; // @synthesize commentCommodityParentItem=_commentCommodityParentItem;
@property(retain, nonatomic) NSString *imageName; // @synthesize imageName=_imageName;
@property(retain, nonatomic) TBSCCommentCommodityItem *commentCommodityItem; // @synthesize commentCommodityItem=_commentCommodityItem;
@property(retain, nonatomic) SLAttributedLabel *parentContentSLabel; // @synthesize parentContentSLabel=_parentContentSLabel;
@property(retain, nonatomic) SLAttributedLabel *contentSLabel; // @synthesize contentSLabel=_contentSLabel;
@property(nonatomic) struct CGSize parentContentlabelSize; // @synthesize parentContentlabelSize=_parentContentlabelSize;
@property(nonatomic) struct CGSize contentlabelSize; // @synthesize contentlabelSize=_contentlabelSize;
@property(nonatomic) double parentContentHeight; // @synthesize parentContentHeight=_parentContentHeight;
@property(nonatomic) double contentHeight; // @synthesize contentHeight=_contentHeight;
@property(nonatomic) double cellHeight; // @synthesize cellHeight=_cellHeight;
@property(retain, nonatomic) NSString *detailUrl; // @synthesize detailUrl=_detailUrl;
@property(nonatomic) _Bool isForPraise; // @synthesize isForPraise=_isForPraise;
@property(nonatomic) _Bool isImageHadLoad; // @synthesize isImageHadLoad=_isImageHadLoad;
@property(nonatomic) unsigned long long parentType; // @synthesize parentType=_parentType;
@property(retain, nonatomic) NSArray *parentExtSymbolArray; // @synthesize parentExtSymbolArray=_parentExtSymbolArray;
@property(retain, nonatomic) NSArray<TBSCCommentCommodityItem> *parentExtSymbol; // @synthesize parentExtSymbol=_parentExtSymbol;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(retain, nonatomic) NSArray *extSymbolArray; // @synthesize extSymbolArray=_extSymbolArray;
@property(retain, nonatomic) NSArray<TBSCCommentCommodityItem> *extSymbol; // @synthesize extSymbol=_extSymbol;
@property(nonatomic) unsigned long long parentId; // @synthesize parentId=_parentId;
@property(nonatomic) unsigned long long authorId; // @synthesize authorId=_authorId;
@property(retain, nonatomic) NSString *authorNick; // @synthesize authorNick=_authorNick;
@property(retain, nonatomic) NSString *parentContent; // @synthesize parentContent=_parentContent;
@property(nonatomic) unsigned long long timestamp; // @synthesize timestamp=_timestamp;
@property(nonatomic) unsigned long long time; // @synthesize time=_time;
@property(nonatomic) unsigned long long id; // @synthesize id=_id;
@property(nonatomic) int createrContentType; // @synthesize createrContentType=_createrContentType;
@property(retain, nonatomic) NSString *content; // @synthesize content=_content;
@property(nonatomic) unsigned long long commentId; // @synthesize commentId=_commentId;
@property(retain, nonatomic) NSString *createrPic; // @synthesize createrPic=_createrPic;
@property(retain, nonatomic) NSString *createrName; // @synthesize createrName=_createrName;
@property(nonatomic) unsigned long long createrId; // @synthesize createrId=_createrId;
@property(nonatomic) unsigned long long targetId; // @synthesize targetId=_targetId;
@property(nonatomic) unsigned long long targetOwnerUserId; // @synthesize targetOwnerUserId=_targetOwnerUserId;
- (void).cxx_destruct;
- (struct CGSize)bubbleSizeWithText:(id)arg1 witFontWidth:(double)arg2 withFont:(_Bool)arg3;
- (id)getCommentParentContentCommodityItem;
- (id)getCommentContentCommodityItem;
- (id)getCommentParentContentPicName;
- (id)getCommentContentPicName;
- (void)setFeedCommentCommodityParentItem:(id)arg1;
- (void)setFeedCommentCommodityItem:(id)arg1;
- (void)getCommentCellHeight;
- (_Bool)hasParentComment;
- (id)toDictionary;
- (void)setFromDictionary:(id)arg1;

@end

