//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TBSearchAuctionIconHelper : NSObject
{
    double _iconHeight;
}

@property(nonatomic) double iconHeight; // @synthesize iconHeight=_iconHeight;
- (id)getTextOneIconData:(id)arg1 andStyleData:(id)arg2;
- (id)getImgOneIconData:(id)arg1 andStyleData:(id)arg2;
- (id)proccessIconWithSytleData:(id)arg1 andConcreteData:(id)arg2;
- (id)init;

@end

