//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TBJSONModel.h"

@class NSString, NSURL, TBSNSAccountItem, TBSNSFeedItem;

@interface TBSNSAccountFeedItem : TBJSONModel
{
    TBSNSAccountItem *_account;
    TBSNSFeedItem *_firstFeed;
    unsigned long long _timestamp;
    long long _unreadCount;
    NSURL *_imageURL;
    NSString *_time;
    NSString *_acm;
    NSString *_scm;
    _Bool _isImageHadLoad;
}

@property(retain, nonatomic) NSString *scm; // @synthesize scm=_scm;
@property(retain, nonatomic) NSString *acm; // @synthesize acm=_acm;
@property(nonatomic) _Bool isImageHadLoad; // @synthesize isImageHadLoad=_isImageHadLoad;
@property(retain, nonatomic) NSString *time; // @synthesize time=_time;
@property(nonatomic) unsigned long long timestamp; // @synthesize timestamp=_timestamp;
@property(nonatomic) long long unreadCount; // @synthesize unreadCount=_unreadCount;
@property(retain, nonatomic) TBSNSFeedItem *firstFeed; // @synthesize firstFeed=_firstFeed;
@property(retain, nonatomic) TBSNSAccountItem *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (id)toJSONDictionary;
- (id)initWithJSONDictionary:(id)arg1 error:(id *)arg2;

@end

