//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSMutableArray<TBTradeRecmdItemModel>, NSString;

@protocol TBTradeRecmdGroupModel <NSObject>
- (id)initWithData:(NSDictionary *)arg1 extraInfo:(id)arg2;
- (NSString *)triggerItemPic;
- (void)setGroupTitle:(NSString *)arg1;
- (NSString *)groupTitle;
- (NSMutableArray<TBTradeRecmdItemModel> *)itemList;
@end

