//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JceObjectV2.h"

@class NSString;

@interface JumpStarIntroduction : JceObjectV2
{
    NSString *jcev2_p_0_o_actorId;
}

+ (id)jceType;
+ (void)initialize;
@property(retain, nonatomic, getter=jce_actorId, setter=setJce_actorId:) NSString *jcev2_p_0_o_actorId; // @synthesize jcev2_p_0_o_actorId;
- (void).cxx_destruct;
- (id)init;

@end

