//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class KKMediaRootViewController, NSDictionary, NSError;

@protocol KKMediaPlayerEventProtocol <NSObject>

@optional
- (void)didMediaPlayerEventOccur:(int)arg1 userInfo:(NSDictionary *)arg2;
- (void)didMediaPlayerScreenChanged:(id <QLMediaMovieViewlayerProtocol>)arg1 fullScreen:(_Bool)arg2;
- (void)didMediaPlayerScreenChanged:(_Bool)arg1;
- (void)didMediaPlayerProgressUpdated:(double)arg1 playableDuration:(double)arg2 duration:(double)arg3 isLive:(_Bool)arg4;
- (void)didMediaPlayerProgressUpdated:(double)arg1 playableDuration:(double)arg2 duration:(double)arg3 dataID:(long long)arg4;
- (void)didMediaPlayerProgressUpdated:(double)arg1 duration:(double)arg2;
- (void)didMediaPlayerStateChanged:(int)arg1 error:(NSError *)arg2 playerCtl:(KKMediaRootViewController *)arg3;
@end

