//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CAShapeLayer.h"

@interface LOTStrokeShapeLayer : CAShapeLayer
{
}

+ (_Bool)needsDisplayForKey:(id)arg1;
- (void)display;
- (void)_commonInit;
- (id)initWithLayer:(id)arg1;
- (id)init;

// Remaining properties
@property double trimEnd; // @dynamic trimEnd;
@property double trimOffset; // @dynamic trimOffset;
@property double trimStart; // @dynamic trimStart;

@end

