//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QLMessageOperationInfo.h"

@interface QLChatRoomMsgPublishInfo : QLMessageOperationInfo
{
}

+ (id)msgPublishInfo:(id)arg1 textContent:(id)arg2 voiceData:(id)arg3 playTime:(double)arg4;
- (id)msgItemForMergeToMsgItemList:(id)arg1;
- (_Bool)shouldMergeToMsgItemList:(id)arg1 uInfo:(id)arg2;
- (void)uploadVoiceObjectFinish:(id)arg1;

@end

