//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString, UIViewController;

@protocol QLInteractiveVoteDelegate <NSObject>
@property(nonatomic) _Bool isWebviewShare;

@optional
- (NSDictionary *)getBanabaSwitchState;
- (long long)getControllerState;
- (void)showGiftButtonWithInfo:(NSDictionary *)arg1;
- (void)showAppPage:(NSDictionary *)arg1;
- (void)triggerAppRefresh:(NSDictionary *)arg1;
- (NSDictionary *)getVideoInfo;
- (void)jumpVideoWithLid:(NSString *)arg1 cid:(NSString *)arg2 vid:(NSString *)arg3 watchTime:(double)arg4 notPlayAds:(_Bool)arg5;
- (void)jumpWatchTimeInVideo:(double)arg1;
- (void)setPlayerState:(_Bool)arg1;
- (NSString *)getH5Info:(NSString *)arg1;
- (void)saveH5Info:(NSString *)arg1 withValue:(NSString *)arg2;
- (void)openWebviewWith:(NSString *)arg1;
- (void)clickInteractiveVoteShareWith:(UIViewController *)arg1;
- (void)shareToMomentGroup;
- (long long)getCurrentTime;
- (_Bool)attentionCurrentPlayVideo:(_Bool)arg1;
- (_Bool)isAttentionCurrentPlayVideo;
- (NSString *)getSuperViewFrame;
- (NSString *)getHitPointInfos;
- (void)hideTransparentView:(_Bool)arg1;
- (void)showTransparentView:(_Bool)arg1;
- (void)closeTransparentView;
@end

