//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JceObjectV2.h"

@class NSArray, NSString;

@interface QLJCEPersonalityPageResponse : JceObjectV2
{
    _Bool jcev2_p_3_o_isHaveNextPage;
    int jcev2_p_0_r_errCode;
    int jcev2_p_7_o_titleUiType;
    NSArray *jcev2_p_1_o_uiData__b0x9i_VOQLJCETempletLine;
    NSString *jcev2_p_2_o_pageContext;
    NSString *jcev2_p_5_o_title;
    NSString *jcev2_p_6_o_subTitle;
    NSString *jcev2_p_8_o_reportParams;
    NSString *jcev2_p_9_o_reportKey;
}

+ (id)jceType;
+ (void)initialize;
@property(retain, nonatomic, getter=jce_reportKey, setter=setJce_reportKey:) NSString *jcev2_p_9_o_reportKey; // @synthesize jcev2_p_9_o_reportKey;
@property(retain, nonatomic, getter=jce_reportParams, setter=setJce_reportParams:) NSString *jcev2_p_8_o_reportParams; // @synthesize jcev2_p_8_o_reportParams;
@property(nonatomic, getter=jce_titleUiType, setter=setJce_titleUiType:) int jcev2_p_7_o_titleUiType; // @synthesize jcev2_p_7_o_titleUiType;
@property(retain, nonatomic, getter=jce_subTitle, setter=setJce_subTitle:) NSString *jcev2_p_6_o_subTitle; // @synthesize jcev2_p_6_o_subTitle;
@property(retain, nonatomic, getter=jce_title, setter=setJce_title:) NSString *jcev2_p_5_o_title; // @synthesize jcev2_p_5_o_title;
@property(nonatomic, getter=jce_isHaveNextPage, setter=setJce_isHaveNextPage:) _Bool jcev2_p_3_o_isHaveNextPage; // @synthesize jcev2_p_3_o_isHaveNextPage;
@property(retain, nonatomic, getter=jce_pageContext, setter=setJce_pageContext:) NSString *jcev2_p_2_o_pageContext; // @synthesize jcev2_p_2_o_pageContext;
@property(retain, nonatomic, getter=jce_uiData, setter=setJce_uiData:) NSArray *jcev2_p_1_o_uiData__b0x9i_VOQLJCETempletLine; // @synthesize jcev2_p_1_o_uiData__b0x9i_VOQLJCETempletLine;
@property(nonatomic, getter=jce_errCode, setter=setJce_errCode:) int jcev2_p_0_r_errCode; // @synthesize jcev2_p_0_r_errCode;
- (void).cxx_destruct;
- (id)init;

@end

