//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JceObjectV2.h"

@class NSString;

@interface QLJCEPersonalityPageRequest : JceObjectV2
{
    int jcev2_p_3_o_hasCache;
    int jcev2_p_4_o_requestScenes;
    NSString *jcev2_p_0_o_type;
    NSString *jcev2_p_1_o_dataKey;
    NSString *jcev2_p_2_o_pageContext;
    NSString *jcev2_p_5_o_lastGroupId;
    NSString *jcev2_p_6_o_routeKey;
}

+ (id)jceType;
+ (void)initialize;
@property(retain, nonatomic, getter=jce_routeKey, setter=setJce_routeKey:) NSString *jcev2_p_6_o_routeKey; // @synthesize jcev2_p_6_o_routeKey;
@property(retain, nonatomic, getter=jce_lastGroupId, setter=setJce_lastGroupId:) NSString *jcev2_p_5_o_lastGroupId; // @synthesize jcev2_p_5_o_lastGroupId;
@property(nonatomic, getter=jce_requestScenes, setter=setJce_requestScenes:) int jcev2_p_4_o_requestScenes; // @synthesize jcev2_p_4_o_requestScenes;
@property(nonatomic, getter=jce_hasCache, setter=setJce_hasCache:) int jcev2_p_3_o_hasCache; // @synthesize jcev2_p_3_o_hasCache;
@property(retain, nonatomic, getter=jce_pageContext, setter=setJce_pageContext:) NSString *jcev2_p_2_o_pageContext; // @synthesize jcev2_p_2_o_pageContext;
@property(retain, nonatomic, getter=jce_dataKey, setter=setJce_dataKey:) NSString *jcev2_p_1_o_dataKey; // @synthesize jcev2_p_1_o_dataKey;
@property(retain, nonatomic, getter=jce_type, setter=setJce_type:) NSString *jcev2_p_0_o_type; // @synthesize jcev2_p_0_o_type;
- (void).cxx_destruct;
- (id)init;

@end

