//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QLMediaPosterBaseCell.h"

@class QLJCEONAMultiMediaPoster;

@interface QLJCEONAMultiMediaPosterCell : QLMediaPosterBaseCell
{
    QLJCEONAMultiMediaPoster *_mediaPoster;
}

+ (id)getCellIdentifierWithPosterObj:(id)arg1 uInfo:(id)arg2;
+ (double)getHeightWithPosterObj:(id)arg1 uInfo:(id)arg2;
@property(retain, nonatomic) QLJCEONAMultiMediaPoster *mediaPoster; // @synthesize mediaPoster=_mediaPoster;
- (void).cxx_destruct;
- (id)posterBottomView:(id)arg1 getAttentItem:(id)arg2;
- (id)posterBottomView:(id)arg1 getShareItem:(id)arg2;
- (struct CGSize)posterBottomView:(id)arg1 sizeForItemViewAtIndexPath:(id)arg2;
- (id)posterBottomView:(id)arg1 itemViewAtIndexPath:(id)arg2;
- (long long)posterBottomView:(id)arg1 numberOfActionMenu:(id)arg2;
- (id)posterAction;
- (id)bottomViewObject;
- (id)middleViewObject;
- (id)mediaContentViewObject;
- (id)topViewObject;
- (void)setObject:(id)arg1;

@end

