//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QLPseudoEditableCell.h"

#import "QLImageLoadDelegate.h"

@class NSString, QLHTMLLabel, QLMomentHeadView, QLReceivedMessageItem, QLRichLabel, QLSImageView, UIImageView, UILabel;

@interface QLMomentNewMessageCell : QLPseudoEditableCell <QLImageLoadDelegate>
{
    _Bool _hidePublishImgView;
    _Bool _hidePublishTextView;
    QLMomentHeadView *_pheadImageView;
    QLSImageView *_publishImageView;
    QLHTMLLabel *_publishTextView;
    UILabel *_nicknameLabel;
    QLRichLabel *_richNickNameLbl;
    UILabel *_ptimeLabel;
    QLHTMLLabel *_ptextLabel;
    QLReceivedMessageItem *_receivedItem;
    UIImageView *_backgroundLine;
    NSString *_ptextLabelString;
}

+ (double)generateCellHeightWithItem:(id)arg1;
+ (id)generateMutlString:(id)arg1 messageType:(int)arg2;
@property(copy, nonatomic) NSString *ptextLabelString; // @synthesize ptextLabelString=_ptextLabelString;
@property(retain, nonatomic) UIImageView *backgroundLine; // @synthesize backgroundLine=_backgroundLine;
@property(retain, nonatomic) QLReceivedMessageItem *receivedItem; // @synthesize receivedItem=_receivedItem;
@property(retain, nonatomic) QLHTMLLabel *ptextLabel; // @synthesize ptextLabel=_ptextLabel;
@property(readonly, nonatomic) UILabel *ptimeLabel; // @synthesize ptimeLabel=_ptimeLabel;
@property(readonly, nonatomic) QLRichLabel *richNickNameLbl; // @synthesize richNickNameLbl=_richNickNameLbl;
@property(readonly, nonatomic) UILabel *nicknameLabel; // @synthesize nicknameLabel=_nicknameLabel;
- (void).cxx_destruct;
- (void)setObject:(id)arg1;
- (void)layoutSubviews;
- (void)prepareForReuse;
@property(readonly, nonatomic) QLHTMLLabel *publishTextView; // @synthesize publishTextView=_publishTextView;
- (id)nameLabel;
@property(readonly, nonatomic) QLSImageView *publishImageView; // @synthesize publishImageView=_publishImageView;
@property(readonly, nonatomic) QLMomentHeadView *pheadImageView; // @synthesize pheadImageView=_pheadImageView;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (double)tableView:(id)arg1 rowHeightForObject:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

