//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QLBaseTabPageViewController.h"

#import "QLNewDetailsSubViewPresenterSubControllerProtocol.h"

@class NSArray, NSString;

@interface QLNewDetailsMutiTabFloatViewController : QLBaseTabPageViewController <QLNewDetailsSubViewPresenterSubControllerProtocol>
{
    NSString *_currentVid;
    NSString *_currentCid;
    NSString *_currentLid;
    id <QLNewDetailsMutiTabFloatViewControllerDataSourceProtocol> _dataSource;
    NSString *_dataKey;
    NSArray *_navigationList;
    NSString *_defaultDataKey;
}

@property(copy, nonatomic) NSString *defaultDataKey; // @synthesize defaultDataKey=_defaultDataKey;
@property(retain, nonatomic) NSArray *navigationList; // @synthesize navigationList=_navigationList;
@property(copy, nonatomic) NSString *dataKey; // @synthesize dataKey=_dataKey;
@property(nonatomic) __weak id <QLNewDetailsMutiTabFloatViewControllerDataSourceProtocol> dataSource; // @synthesize dataSource=_dataSource;
@property(copy, nonatomic) NSString *currentLid; // @synthesize currentLid=_currentLid;
@property(copy, nonatomic) NSString *currentCid; // @synthesize currentCid=_currentCid;
@property(copy, nonatomic) NSString *currentVid; // @synthesize currentVid=_currentVid;
- (void).cxx_destruct;
- (unsigned long long)subViewPresenterControllerDisplayStyle;
- (_Bool)disablePageScrollAnimation;
- (unsigned long long)topBarStyle;
- (id)topChannelKeyWithIndex:(long long)arg1;
- (id)topChannelControllerWithIndex:(long long)arg1;
- (id)topChannelTitleWithIndex:(long long)arg1;
- (unsigned long long)topChannelNumber;
- (double)btnNaviMaskBottomGapHeight:(id)arg1;
- (id)buttonFontForHorizMenu:(id)arg1;
- (double)horizMenuWidth;
- (double)horizMenuHeight;
- (_Bool)responseDragbackAtScreenPoint:(struct CGPoint)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)initalTabListData;
- (id)initWithDataKey:(id)arg1 withDataSource:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

