//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class QLShowRoomH5Ctl;

@protocol QLSRWebviewControlProtocol <NSObject>
@property(nonatomic) __weak QLShowRoomH5Ctl *bindingSRH5Ctl;
@property(nonatomic) __weak id <QLSRH5HandlerProtocol> bindingSRDelegate;
@end

