//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QLRequestModel.h"

@class NSString, QLASIHTTPRequest;

@interface QLVidSizeModel : QLRequestModel
{
    NSString *_vid;
    NSString *_movieId;
    unsigned long long _videoSize;
    QLASIHTTPRequest *_dataRequest;
}

+ (id)createSizeModel:(id)arg1 vid:(id)arg2;
@property(retain, nonatomic) QLASIHTTPRequest *dataRequest; // @synthesize dataRequest=_dataRequest;
@property(nonatomic) unsigned long long videoSize; // @synthesize videoSize=_videoSize;
@property(copy, nonatomic) NSString *movieId; // @synthesize movieId=_movieId;
@property(copy, nonatomic) NSString *vid; // @synthesize vid=_vid;
- (void).cxx_destruct;
- (void)request:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)requestDidFinishLoad:(id)arg1;
- (void)load:(int)arg1 more:(_Bool)arg2;
- (void)requestDidRetryRequest:(id)arg1;
- (void)cancelDataRequest;
- (void)dealloc;
- (id)initWithMovieId:(id)arg1 Vid:(id)arg2;

@end

