//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "QLRequestModelDelegate.h"
#import "QLTabBarConfigProtocol.h"

@class NSString, QLVipActivityChannelNameColorConfig, QLVipActivityLoadingViewConfig, QLVipActivityModel, QLVipActivityOpenVipConfig, QLVipActivityPullRefreshInfoConfig, QLVipActivityTabbarConfig, QLVipActivityTilteBarConfig;

@interface QLVipActivityManager : NSObject <QLRequestModelDelegate, QLTabBarConfigProtocol>
{
    QLVipActivityModel *_model;
    QLVipActivityLoadingViewConfig *_loadingViewConfig;
    QLVipActivityPullRefreshInfoConfig *_pullRefreshInfoConfig;
    QLVipActivityOpenVipConfig *_openVipConfig;
    QLVipActivityTabbarConfig *_tabbarConfig;
    QLVipActivityTilteBarConfig *_titleBarConfig;
    QLVipActivityChannelNameColorConfig *_channelNameColorConfig;
}

+ (id)sharedInstance;
@property(retain, nonatomic) QLVipActivityChannelNameColorConfig *channelNameColorConfig; // @synthesize channelNameColorConfig=_channelNameColorConfig;
@property(retain, nonatomic) QLVipActivityTilteBarConfig *titleBarConfig; // @synthesize titleBarConfig=_titleBarConfig;
@property(retain, nonatomic) QLVipActivityTabbarConfig *tabbarConfig; // @synthesize tabbarConfig=_tabbarConfig;
@property(retain, nonatomic) QLVipActivityOpenVipConfig *openVipConfig; // @synthesize openVipConfig=_openVipConfig;
@property(retain, nonatomic) QLVipActivityPullRefreshInfoConfig *pullRefreshInfoConfig; // @synthesize pullRefreshInfoConfig=_pullRefreshInfoConfig;
@property(retain, nonatomic) QLVipActivityLoadingViewConfig *loadingViewConfig; // @synthesize loadingViewConfig=_loadingViewConfig;
@property(retain, nonatomic) QLVipActivityModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (id)colorOfChannelNameColor;
- (id)titleBarSearchColor;
- (id)titleBarOpenVipBgColor;
- (id)titleBarOpenVipText;
- (id)titleBarTitle;
- (id)titleBarBackgroundImageView;
- (id)titleBarBackgroundColor;
- (_Bool)shouldShowActivityTitleBar;
- (id)tabbarButtonConfig:(unsigned long long)arg1;
- (id)tabbarBackgroundImageView;
- (id)tabbarIconColor;
- (id)tabbarTextColor;
- (id)tabbarBackgroundColor;
- (_Bool)shouldShowActivityTabbar;
- (id)wholeText;
- (id)tryLookTextForPayVideo;
- (_Bool)shouldShowActivityPromotImage;
- (id)tryLookSubscriptImageUrl;
- (id)promotImageURL;
- (id)colorOfPullRefreshBGView;
- (_Bool)shouldShowActivityPullRefreshView;
- (id)getPullFreshCover;
- (struct CGSize)getPullFreshCoverSize;
- (void)saveShowCount;
- (void)randomSelectLoadingConfig;
- (id)vipActivityLoadingBgColor;
- (_Bool)shouldShowActivityLoadingBgColor;
- (id)vipActivityLoadingSpeedColor;
- (_Bool)shouldShowActivityLoadingSpeedColor;
- (id)vipActivityLoadingGifView;
- (_Bool)shouldShowActivityLoadingView;
- (void)loadActivityConfig:(int)arg1;
- (void)requestModel:(id)arg1 didFailedLoadWithError:(id)arg2;
- (void)requestModelDidFinishLoad:(id)arg1;
- (void)vipStateChanged:(id)arg1;
- (void)loginStateChange:(id)arg1;
- (void)initConfig;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

