//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class QLVRssSubscribeSingleItemView;

@interface QLVRssSubscribeSingleItemCell : UICollectionViewCell
{
    QLVRssSubscribeSingleItemView *_itemView;
}

@property(retain, nonatomic) QLVRssSubscribeSingleItemView *itemView; // @synthesize itemView=_itemView;
- (void).cxx_destruct;
- (void)setObject:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

