//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSDictionary, NSMutableDictionary, NSString;

@interface TADFrequency : NSObject <NSCoding>
{
    NSDictionary *_orderDataMap;
    NSString *_date;
    NSMutableDictionary *_adFreeIntervalDict;
    NSDictionary *_reportedOrderMap;
}

@property(retain, nonatomic) NSDictionary *reportedOrderMap; // @synthesize reportedOrderMap=_reportedOrderMap;
@property(retain, nonatomic) NSMutableDictionary *adFreeIntervalDict; // @synthesize adFreeIntervalDict=_adFreeIntervalDict;
@property(copy, nonatomic) NSString *date; // @synthesize date=_date;
@property(retain, nonatomic) NSDictionary *orderDataMap; // @synthesize orderDataMap=_orderDataMap;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

