//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FMBidDOList.h"

@class NSString;

@interface FMBidDOList : NSObject <FMBidDOList>
{
    NSString *_bidderId;
    NSString *_bidderNick;
    NSString *_bidPrice;
    NSString *_timestamp;
    NSString *_itemId;
    NSString *_auctionId;
    long long _recordStatus;
    NSString *_iconUrl;
    NSString *_statusDesc;
}

@property(copy, nonatomic) NSString *statusDesc; // @synthesize statusDesc=_statusDesc;
@property(copy, nonatomic) NSString *iconUrl; // @synthesize iconUrl=_iconUrl;
@property(nonatomic) long long recordStatus; // @synthesize recordStatus=_recordStatus;
@property(copy, nonatomic) NSString *auctionId; // @synthesize auctionId=_auctionId;
@property(copy, nonatomic) NSString *itemId; // @synthesize itemId=_itemId;
@property(copy, nonatomic) NSString *timestamp; // @synthesize timestamp=_timestamp;
@property(copy, nonatomic) NSString *bidPrice; // @synthesize bidPrice=_bidPrice;
@property(copy, nonatomic) NSString *bidderNick; // @synthesize bidderNick=_bidderNick;
@property(copy, nonatomic) NSString *bidderId; // @synthesize bidderId=_bidderId;
- (void).cxx_destruct;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

