//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, NSNumber, UIImageView;

@interface FMMessageEmotionItemDisplayView : UIView
{
    UIImageView *_imageView;
    NSArray *_currentFaces;
    NSNumber *_currentIndex;
}

@property(retain, nonatomic) NSNumber *currentIndex; // @synthesize currentIndex=_currentIndex;
@property(retain, nonatomic) NSArray *currentFaces; // @synthesize currentFaces=_currentFaces;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;

@end

