//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FMBaseViewController.h"

@class FMPostImpressionComponent, UIButton, UILabel, UITableView;

@interface FMPostImpressionViewController : FMBaseViewController
{
    UITableView *_tableView;
    UIButton *_postBtn;
    UILabel *_bottomLine;
    FMPostImpressionComponent *_postImpressionComponent;
}

@property(retain, nonatomic) FMPostImpressionComponent *postImpressionComponent; // @synthesize postImpressionComponent=_postImpressionComponent;
@property(retain, nonatomic) UILabel *bottomLine; // @synthesize bottomLine=_bottomLine;
@property(retain, nonatomic) UIButton *postBtn; // @synthesize postBtn=_postBtn;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (void)postBtnTapAction;
- (void)binding;
- (void)viewDidLoad;
- (id)initWithURL:(id)arg1 query:(id)arg2 nativeParams:(id)arg3;
- (_Bool)isOpenedWithQuery:(id)arg1 nativeParams:(id)arg2;

@end

