//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSAttributedString, NSString, UIFont, UIImageView, UILabel;

@interface FMPostActivityCellView : UIView
{
    UILabel *_textLabel;
    CDUnknownBlockType _didSelectHandler;
    UIImageView *_arrowImageView;
    UILabel *_subContentLabel;
    _Bool hasServiceTag;
    NSString *_text;
    NSString *_content;
    NSAttributedString *_subContent;
    UIFont *_contentFont;
    UILabel *_contentLabel;
}

@property(retain, nonatomic) UILabel *contentLabel; // @synthesize contentLabel=_contentLabel;
@property(retain, nonatomic) UIFont *contentFont; // @synthesize contentFont=_contentFont;
@property(copy, nonatomic) NSAttributedString *subContent; // @synthesize subContent=_subContent;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
- (void).cxx_destruct;
- (void)setDidSelectHandler:(CDUnknownBlockType)arg1;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)setupViews;
- (id)init;

@end

