//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSMutableArray;

@interface FMSegmentedControl : UIView
{
    NSMutableArray *_items;
    id _delegate;
    unsigned long long _selectedIndex;
    _Bool _enable;
    CDUnknownBlockType _segmentChangedActionBlock;
    _Bool _isAutoSelected;
}

@property(nonatomic) _Bool isAutoSelected; // @synthesize isAutoSelected=_isAutoSelected;
@property(nonatomic) _Bool enable; // @synthesize enable=_enable;
@property(nonatomic) unsigned long long selectedIndex; // @synthesize selectedIndex=_selectedIndex;
@property(retain, nonatomic) NSMutableArray *items; // @synthesize items=_items;
@property(nonatomic) id delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (void)selectedSegmentedControlItem:(id)arg1;
- (void)setSegmentChangedAction:(CDUnknownBlockType)arg1;
- (void)setSegmentedItems:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

