//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ISecurityGuardOpenSecurityBody.h"

@class NSString;

@interface SecurityGuardOpenSecurityBody : NSObject <ISecurityGuardOpenSecurityBody>
{
}

- (id)urlEncodeString:(id)arg1;
- (id)assembleExtendParam:(id)arg1;
- (Class)getMetaClass;
- (id)getSecurityBodyDataEx:(id)arg1 appKey:(id)arg2 authCode:(id)arg3 extendParam:(id)arg4 flag:(int)arg5 env:(int)arg6 error:(id *)arg7;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

