//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "EODCommonRateReviewCell.h"

@class EODOrderRateModel;

@interface EODShopRatedCell : EODCommonRateReviewCell
{
    EODOrderRateModel *_orderRate;
}

@property(retain, nonatomic) EODOrderRateModel *orderRate; // @synthesize orderRate=_orderRate;
- (void).cxx_destruct;
- (void)configUI;
- (id)initWithOrderRate:(id)arg1;

@end

