//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ESPShoppingViewController.h"

#import "UINavigationControllerDelegate.h"
#import "UIViewControllerPreviewingDelegate.h"

@class ESPCartContextDataContainer, ESPDeliveryBottomView, ESPFoodListDataProvider, ESPQualityFoodCategoryTableView, ESPQualityFoodListTableView, ESPRestaurant, ESPVirtualFood, MASConstraint, NSString, NVMFoodIdentity, NVMViewController, UIImageView;

@interface ESPQualityRestaurantGoodViewController : ESPShoppingViewController <UIViewControllerPreviewingDelegate, UINavigationControllerDelegate>
{
    _Bool _didAddLoginNotification;
    _Bool _autoFocusEssentialCategoryOnViewDidAppear;
    NVMFoodIdentity *_targetFoodIdentity;
    NSString *_restaurantID;
    NVMViewController *_qualityViewController;
    MASConstraint *_topConstraint;
    ESPQualityFoodListTableView *_foodListView;
    ESPQualityFoodCategoryTableView *_categoryListView;
    ESPFoodListDataProvider *_foodListData;
    ESPCartContextDataContainer *_cartContextContainer;
    ESPVirtualFood *_currentFood;
    ESPDeliveryBottomView *_deliveryBottomView;
    UIImageView *_transitionImageView;
    UIImageView *_bannerImageView;
}

@property(nonatomic) _Bool autoFocusEssentialCategoryOnViewDidAppear; // @synthesize autoFocusEssentialCategoryOnViewDidAppear=_autoFocusEssentialCategoryOnViewDidAppear;
@property(retain, nonatomic) UIImageView *bannerImageView; // @synthesize bannerImageView=_bannerImageView;
@property(retain, nonatomic) UIImageView *transitionImageView; // @synthesize transitionImageView=_transitionImageView;
@property(retain, nonatomic) ESPDeliveryBottomView *deliveryBottomView; // @synthesize deliveryBottomView=_deliveryBottomView;
@property(retain, nonatomic) ESPVirtualFood *currentFood; // @synthesize currentFood=_currentFood;
@property(nonatomic) _Bool didAddLoginNotification; // @synthesize didAddLoginNotification=_didAddLoginNotification;
@property(retain, nonatomic) ESPCartContextDataContainer *cartContextContainer; // @synthesize cartContextContainer=_cartContextContainer;
@property(retain, nonatomic) ESPFoodListDataProvider *foodListData; // @synthesize foodListData=_foodListData;
@property(retain, nonatomic) ESPQualityFoodCategoryTableView *categoryListView; // @synthesize categoryListView=_categoryListView;
@property(retain, nonatomic) ESPQualityFoodListTableView *foodListView; // @synthesize foodListView=_foodListView;
@property(retain, nonatomic) MASConstraint *topConstraint; // @synthesize topConstraint=_topConstraint;
@property(nonatomic) __weak NVMViewController *qualityViewController; // @synthesize qualityViewController=_qualityViewController;
@property(copy, nonatomic) NSString *restaurantID; // @synthesize restaurantID=_restaurantID;
@property(copy, nonatomic) NVMFoodIdentity *targetFoodIdentity; // @synthesize targetFoodIdentity=_targetFoodIdentity;
- (void).cxx_destruct;
- (void)previewingContext:(id)arg1 commitViewController:(id)arg2;
- (id)previewingContext:(id)arg1 viewControllerForLocation:(struct CGPoint)arg2;
- (id)navigationController:(id)arg1 animationControllerForOperation:(long long)arg2 fromViewController:(id)arg3 toViewController:(id)arg4;
- (id)navigationController:(id)arg1 interactionControllerForAnimationController:(id)arg2;
- (id)transitionViewForFood:(id)arg1;
- (id)qualityRestaurantViewController;
- (void)updateDeliveryBottomViewFromRestaurant:(id)arg1;
- (void)showEmpty;
- (void)deselectCategoryListViewAnimated:(_Bool)arg1;
- (void)showFoodsInCategory:(id)arg1 animated:(_Bool)arg2;
- (void)showEssentialButtonWithCatwgory:(id)arg1;
- (void)showCategory:(id)arg1 animated:(_Bool)arg2;
- (void)selectDefaultCategoryIfNeeded;
- (void)selectTargetFood:(id)arg1;
- (void)highlightEssentialCell;
- (void)focusEssentialCategory;
- (void)notifiedFocusEssentialCategory;
- (void)alertWithTitle:(id)arg1 message:(id)arg2;
- (void)gotoFoodFloatingLayerViewWithFoods:(id)arg1;
- (void)updateWithCartContext:(id)arg1 rebuyDescription:(id)arg2 boughtFoods:(id)arg3;
- (id)categories;
@property(readonly, nonatomic) ESPRestaurant *restaurant;
- (void)flushPage:(id)arg1;
- (void)tapBannerView;
- (void)updateBannerImageView;
- (void)addBannerImageView;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

