//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NVMAddressManager : NSObject
{
}

+ (void)showChangePlaceViewController;
+ (id)changePlaceViewControllerWithDidSelectLocationAction:(CDUnknownBlockType)arg1;
+ (id)confirmAddressViewControllerWithContext:(id)arg1 initialAddress:(id)arg2 didSelectedAddressAction:(CDUnknownBlockType)arg3;
+ (id)addressSearchViewControllerWithInitialGeohash:(id)arg1 didSelectAddressAction:(CDUnknownBlockType)arg2;
+ (id)addAddressViewControllerIsNeedAccurateAddress:(_Bool)arg1 didUpdatedAddressAction:(CDUnknownBlockType)arg2;
+ (id)addressListViewController;

@end

