//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NVMPullToRefreshView;

@interface NVMScrollViewBackgroundView : UIView
{
    NVMPullToRefreshView *_view;
}

@property(nonatomic) __weak NVMPullToRefreshView *view; // @synthesize view=_view;
- (void).cxx_destruct;
- (void)willMoveToSuperview:(id)arg1;

@end

