//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NVMTradingRiskControlReporter : NSObject
{
}

+ (void)reportMakeOrderRCInfoWithMakeOrder:(id)arg1 checkoutInfo:(id)arg2;
+ (id)commonParamsForRCInfoWithCheckoutInfo:(id)arg1;
+ (void)reportCartWithCheckoutInfo:(id)arg1;

@end

