//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewHeaderFooterView.h"

@class NVMImageView, NVMUser, NVMUserHeaderButton, NVMUserSuperVIP, OAStackView, UIButton, UIImageView, UILabel, UIView;

@interface NVMUserHeaderView : UITableViewHeaderFooterView
{
    NVMImageView *_avatarImageView;
    NVMUser *_user;
    CDUnknownBlockType _headButtonAction;
    CDUnknownBlockType _goMyBalanceAction;
    CDUnknownBlockType _goMyRedEnvelopeAction;
    CDUnknownBlockType _goMyPointAction;
    UIView *_topBackgroundView;
    UIView *_buttonBackgroundView;
    UILabel *_userNameLabel;
    UILabel *_userMobileLabel;
    UILabel *_loginHintLabel;
    UILabel *_hintLabel;
    UIImageView *_mobileImage;
    NVMUserHeaderButton *_balanceButton;
    NVMUserHeaderButton *_redEnveloperButton;
    NVMUserHeaderButton *_pointButton;
    UIImageView *_vipIconView;
    UIView *_accessoryView;
    NVMUserSuperVIP *_superVip;
    UIButton *_superVipIcon;
    OAStackView *_nameStackView;
}

@property(retain, nonatomic) OAStackView *nameStackView; // @synthesize nameStackView=_nameStackView;
@property(retain, nonatomic) UIButton *superVipIcon; // @synthesize superVipIcon=_superVipIcon;
@property(retain, nonatomic) NVMUserSuperVIP *superVip; // @synthesize superVip=_superVip;
@property(retain, nonatomic) UIView *accessoryView; // @synthesize accessoryView=_accessoryView;
@property(retain, nonatomic) UIImageView *vipIconView; // @synthesize vipIconView=_vipIconView;
@property(retain, nonatomic) NVMUserHeaderButton *pointButton; // @synthesize pointButton=_pointButton;
@property(retain, nonatomic) NVMUserHeaderButton *redEnveloperButton; // @synthesize redEnveloperButton=_redEnveloperButton;
@property(retain, nonatomic) NVMUserHeaderButton *balanceButton; // @synthesize balanceButton=_balanceButton;
@property(retain, nonatomic) UIImageView *mobileImage; // @synthesize mobileImage=_mobileImage;
@property(retain, nonatomic) UILabel *hintLabel; // @synthesize hintLabel=_hintLabel;
@property(retain, nonatomic) UILabel *loginHintLabel; // @synthesize loginHintLabel=_loginHintLabel;
@property(retain, nonatomic) UILabel *userMobileLabel; // @synthesize userMobileLabel=_userMobileLabel;
@property(retain, nonatomic) UILabel *userNameLabel; // @synthesize userNameLabel=_userNameLabel;
@property(retain, nonatomic) UIView *buttonBackgroundView; // @synthesize buttonBackgroundView=_buttonBackgroundView;
@property(retain, nonatomic) UIView *topBackgroundView; // @synthesize topBackgroundView=_topBackgroundView;
@property(copy, nonatomic) CDUnknownBlockType goMyPointAction; // @synthesize goMyPointAction=_goMyPointAction;
@property(copy, nonatomic) CDUnknownBlockType goMyRedEnvelopeAction; // @synthesize goMyRedEnvelopeAction=_goMyRedEnvelopeAction;
@property(copy, nonatomic) CDUnknownBlockType goMyBalanceAction; // @synthesize goMyBalanceAction=_goMyBalanceAction;
@property(copy, nonatomic) CDUnknownBlockType headButtonAction; // @synthesize headButtonAction=_headButtonAction;
@property(retain, nonatomic) NVMUser *user; // @synthesize user=_user;
@property(retain, nonatomic) NVMImageView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
- (void).cxx_destruct;
- (void)accessibilitySetting;
- (void)goMyPoint;
- (void)goMyRedEnvelope;
- (void)goMyBalance;
- (void)headButton;
- (void)setGuestMode:(_Bool)arg1;
- (void)goToVipPage;
- (void)updateWithSuperVip:(id)arg1;
- (void)setVipIcon;
- (void)updateUserInfo;
- (void)loadButtons;
- (void)loadUserInfoView;
- (void)loadUserNameView;
- (void)loadView;
- (id)initWithReuseIdentifier:(id)arg1;

@end

